.travis.yml
packages/app/testem.js
packages/core/testem.js
packages/dashboards/testem.js
packages/data/testem.js
packages/reports/testem.js
packages/visualizations/testem.js

Use chrome headless ci mode

---

README.md

Add navi build status icon

---

packages/app/app/styles/common/defaults.less
packages/app/app/styles/components/nav-bar.less
packages/app/app/templates/components/nav-bar.hbs

- Update buttons to match design language:
- Nav bar style updates:

App style updates

---

.travis.yml

- Remove PhantomJS from travis

Remove PhantomJS from travis

---

.travis.yml
package.json
scripts/ci-publish.sh

Needs https://github.com/yahoo/navi/pull/58
- Automate prerelease package publishing
- Add `travis_wait` to longer running steps

Automate prerelease package publishing

---

README.md

Make build badge link to travis

Make build badge link to travis

---

packages/core/addon/utils/classes/interval.js
packages/core/tests/unit/utils/classes/interval-test.js
packages/data/addon/services/keg.js
packages/data/tests/unit/services/keg-test.js
packages/reports/addon/consumers/request/filter.js
packages/reports/addon/templates/components/report-builder.hbs
packages/reports/config/environment.js
packages/reports/tests/acceptance/navi-report-test.js
packages/reports/tests/integration/components/navi-date-range-picker-test.js
packages/reports/tests/integration/components/report-builder-test.js
packages/reports/tests/unit/models/delivery-rule-test.js

Sync phase v

---

CONTRIBUTING.md

Add changelog convention to contributing documention

Docs: Add changelog convention to contributing doc

---

package.json

Enforce eslint convention for commit messages (fixes #69)

Update: Enforce eslint convention for commit messages (fixes #69)

---

packages/reports/addon/components/common-actions/schedule.js
packages/reports/addon/templates/components/common-actions/schedule.hbs
packages/reports/tests/integration/components/common-actions/schedule-test.js

* enhancement: show close button after save schedule

Update: show close button after save schedule

---

README.md
packages/reports/addon/templates/components/navi-date-range-picker.hbs

Update: Update fili links to point to fili.io

---

packages/visualizations/addon/components/navi-visualizations/metric-label.js
packages/visualizations/addon/models/metric-label.js
packages/visualizations/addon/serializers/metric-label.js
packages/visualizations/app/serializers/metric-label.js
packages/visualizations/tests/dummy/app/controllers/metric-label.js
packages/visualizations/tests/dummy/app/templates/metric-label.hbs
packages/visualizations/tests/helpers/request.js
packages/visualizations/tests/integration/components/navi-visualizations/metric-label-test.js
packages/visualizations/tests/unit/helpers/default-config-test.js
packages/visualizations/tests/unit/models/line-chart-test.js
packages/visualizations/tests/unit/models/metric-label-test.js
packages/visualizations/tests/unit/serializers/metric-label-test.js

This is the metric label part of #71

Breaking: Refactor metric label metric to be an object (refs #71)

---

packages/visualizations/addon/components/number-format-selector.js
packages/visualizations/addon/components/visualization-config/metric-label.js
packages/visualizations/addon/models/metric-label.js
packages/visualizations/addon/templates/components/number-format-selector.hbs
packages/visualizations/addon/templates/components/visualization-config/metric-label.hbs
packages/visualizations/addon/utils/enums/number-formats.js
packages/visualizations/app/components/number-format-selector.js
packages/visualizations/app/styles/navi-visualizations/components/index.less
packages/visualizations/app/styles/navi-visualizations/components/number-format-selector.less
packages/visualizations/app/styles/navi-visualizations/components/visualization-config/goal-gauge.less
packages/visualizations/app/styles/navi-visualizations/components/visualization-config/metric-label.less
packages/visualizations/app/utils/enums/number-formats.js
packages/visualizations/blueprints/navi-visualizations/index.js
packages/visualizations/package.json
packages/visualizations/tests/dummy/app/styles/app.less
packages/visualizations/tests/integration/components/number-format-selector-test.js
packages/visualizations/tests/integration/components/visualization-config/metric-label-test.js

Add number format selector component

New: Add number format selector component (fixes #78)

---

packages/visualizations/addon/components/cell-renderers/metric.js
packages/visualizations/addon/components/cell-renderers/threshold.js
packages/visualizations/addon/components/navi-visualizations/table.js
packages/visualizations/addon/models/table.js
packages/visualizations/addon/serializers/table.js
packages/visualizations/addon/templates/components/cell-renderers/dimension.hbs
packages/visualizations/addon/templates/components/navi-visualizations/table.hbs
packages/visualizations/app/serializers/table.js
packages/visualizations/tests/acceptance/table-test.js
packages/visualizations/tests/dummy/app/controllers/table.js
packages/visualizations/tests/integration/components/cell-renderers/date-time-test.js
packages/visualizations/tests/integration/components/cell-renderers/dimension-test.js
packages/visualizations/tests/integration/components/cell-renderers/metric-test.js
packages/visualizations/tests/integration/components/cell-renderers/threshold-test.js
packages/visualizations/tests/integration/components/cell-renderers/total-test.js
packages/visualizations/tests/integration/components/navi-visualizations/table-print-test.js
packages/visualizations/tests/integration/components/navi-visualizations/table-test.js
packages/visualizations/tests/integration/components/table-cell-renderer-test.js
packages/visualizations/tests/unit/component/navi-visualizations/table-test.js
packages/visualizations/tests/unit/models/table-test.js
packages/visualizations/tests/unit/serializers/table-test.js

Refers to #71 
The field property of each column is now always an object.

Refactor table visualization metric 

---

packages/app/package.json
packages/dashboards/package.json
packages/data/addon/mirage/routes/bard-lite.js
packages/reports/addon/components/missing-intervals-warning.js
packages/reports/addon/components/report-view.js
packages/reports/addon/mirage/fixtures/reports.js
packages/reports/addon/templates/components/missing-intervals-warning.hbs
packages/reports/addon/templates/components/report-view.hbs
packages/reports/addon/transitions.js
packages/reports/app/components/missing-intervals-warning.js
packages/reports/app/styles/navi-reports/components/index.less
packages/reports/app/styles/navi-reports/components/missing-intervals-warning.less
packages/reports/app/styles/navi-reports/components/report-view.less
packages/reports/app/transitions.js
packages/reports/blueprints/navi/index.js
packages/reports/package.json
packages/reports/tests/integration/components/missing-intervals-warning-test.js

Collapsed:
Expanded:
Animations:

Update: Add missing intervals warning component

---

packages/reports/tests/acceptance/report-visualizations-test.js
packages/visualizations/addon/components/navi-visualizations/table.js
packages/visualizations/tests/integration/components/navi-visualizations/table-test.js

* Metric object was being passed where metricName was expected
* sort direction couldn't be found for dateTime sort
* Added sorting acceptance tests that would have caught this

Fix: Table sorting doesn't work

---

packages/data/addon/mirage/fixtures/bard-meta-metrics.js
packages/reports/addon/consumers/report/table-visualization.js
packages/reports/addon/services/report-action-dispatcher.js
packages/reports/addon/templates/components/report-view.hbs
packages/reports/addon/templates/components/report-visualization.hbs
packages/reports/tests/acceptance/metric-parameters-test.js
packages/reports/tests/dummy/config/environment.js
packages/reports/tests/integration/components/metric-selector-test.js
packages/reports/tests/integration/components/print-report-view-test.js
packages/reports/tests/integration/components/report-view-test.js
packages/reports/tests/unit/consumers/report/table-visualization-test.js
packages/visualizations/addon/components/navi-visualizations/table.js
packages/visualizations/addon/helpers/default-column-name.js
packages/visualizations/addon/models/table.js
packages/visualizations/addon/templates/components/navi-visualizations/table.hbs
packages/visualizations/app/helpers/default-column-name.js
packages/visualizations/config/environment.js
packages/visualizations/tests/dummy/config/environment.js
packages/visualizations/tests/integration/components/navi-visualizations/table-test.js
packages/visualizations/tests/integration/helpers/default-column-name-test.js

Update: Add consumer to handle table column update

---

packages/data/addon/mirage/routes/bard-lite.js
packages/data/addon/models/bard-dimension.js
packages/reports/addon/components/filter-values/dimension-select.js
packages/reports/tests/.eslintrc.js
packages/reports/tests/acceptance/navi-report-test.js

* Added an  isEqual function to selectedDimensions so
object equality is not needed.

Fix: Dimensions loaded from server now show as selected in dropdown

---

packages/visualizations/addon/models/table.js
packages/visualizations/tests/unit/models/table-test.js

Update: Table modal to make user config persistent

---

packages/visualizations/addon/components/cell-renderers/metric.js
packages/visualizations/tests/integration/components/cell-renderers/metric-test.js
packages/visualizations/tests/integration/components/navi-visualizations/table-print-test.js
packages/visualizations/tests/integration/components/navi-visualizations/table-test.js
packages/visualizations/tests/integration/components/table-cell-renderer-test.js

Fix: Metric table cell default format

---

packages/reports/app/styles/navi-reports/vendor/index.less
packages/reports/app/styles/navi-reports/vendor/number-format-dropdown.less
packages/visualizations/app/styles/navi-visualizations/components/number-format-dropdown.less
packages/visualizations/app/styles/navi-visualizations/visualizations/table.less

* Make trigger clickable area bigger
* Add background color
* adjust position in navi-report

Update: Improve table editing style

---

packages/visualizations/addon/components/navi-visualizations/table.js
packages/visualizations/addon/helpers/default-column-name.js
packages/visualizations/addon/models/table.js
packages/visualizations/addon/templates/components/navi-visualizations/table.hbs
packages/visualizations/addon/templates/components/visualization-config/table.hbs
packages/visualizations/app/styles/navi-visualizations/visualizations/table.less
packages/visualizations/tests/acceptance/table-test.js
packages/visualizations/tests/unit/component/navi-visualizations/table-test.js
packages/visualizations/tests/unit/models/table-test.js

Update: Add edited column state to table

---

packages/reports/addon/components/report-builder.js
packages/reports/addon/routes/reports/new.js
packages/reports/tests/unit/components/report-builder-test.js

This allows for an alphabetic sort for the tables dropdown.

Fix: Sort list of tables in table dropdown

---

packages/directory/addon/controllers/directory.js
packages/directory/addon/routes/directory.js
packages/directory/addon/templates/directory.hbs
packages/directory/app/controllers/directory.js
packages/directory/app/routes/directory.js
packages/directory/app/styles/navi-directory.less
packages/directory/app/styles/navi-directory/index.less
packages/directory/app/styles/navi-directory/routes/directory.less
packages/directory/app/styles/navi-directory/routes/index.less
packages/directory/app/templates/directory.js
packages/directory/ember-cli-build.js
packages/directory/package.json
packages/directory/tests/dummy/app/router.js
packages/directory/tests/dummy/app/styles/app.less
packages/directory/tests/dummy/app/templates/application.hbs
packages/directory/tests/unit/controllers/directory-test.js
packages/directory/tests/unit/routes/directory-test.js

- Directory Route
- Directory Controller
- Support for query params - type, filter

Update: Add new directory route

---

packages/dashboards/app/styles/navi-dashboards/common.less
packages/dashboards/app/styles/navi-dashboards/components/navi-dashboard.less
packages/dashboards/tests/acceptance/dashboards-test.js
packages/reports/addon/components/common-actions/schedule.js
packages/reports/addon/templates/components/common-actions/delete.hbs
packages/reports/addon/templates/components/common-actions/schedule.hbs
packages/reports/app/styles/navi-reports/common/report.less
packages/reports/app/styles/navi-reports/components/reports-index.less
packages/reports/app/styles/navi-reports/components/schedule-modal.less
packages/reports/tests/acceptance/navi-report-test.js
packages/reports/tests/acceptance/schedule-modal-test.js

- Listen to format changes in the delivery rule
- Apply secondary styles to delete button
- Proper Pill and input styling for schedule modal

Fix Schedule Modal Bugs

---

packages/data/addon/request-decorators/replace-null.js
packages/data/index.js

Use `get` to fetch properties from request

Fix: Use `get` to fetch properties from request

---

packages/directory/addon/templates/directory.hbs
packages/directory/app/styles/navi-directory/components/dir-sidebar.less
packages/directory/app/styles/navi-directory/routes/directory.less

Use CSS Grid
- Felt the grid layout was more suitable for this view

Update: Switch css from flex to grid

---

packages/directory/addon/controllers/directory.js
packages/directory/addon/routes/directory.js
packages/directory/addon/routes/directory/my-directory.js
packages/directory/addon/templates/components/dir-sidebar.hbs
packages/directory/addon/utils/enums/directories.js
packages/directory/app/styles/navi-directory/components/dir-sidebar.less
packages/directory/app/styles/navi-directory/routes/directory.less
packages/directory/tests/acceptance/dir-sidebar-test.js
packages/directory/tests/integration/components/dir-sidebar-test.js

- Filter query param support
- updated sidebar styles

Directory query params - Filter support

---

packages/core/addon/utils/search.js
packages/directory/addon/components/dir-search-bar.js
packages/directory/addon/controllers/directory.js
packages/directory/addon/routes/directory.js
packages/directory/addon/routes/directory/my-directory.js
packages/directory/addon/templates/components/dir-search-bar.hbs
packages/directory/addon/templates/directory.hbs
packages/directory/app/components/dir-search-bar.js
packages/directory/app/styles/navi-directory/components/dir-search-bar.less
packages/directory/app/styles/navi-directory/components/index.less
packages/directory/tests/acceptance/dir-search-bar-test.js
packages/directory/tests/integration/components/dir-search-bar-test.js

- New: Search-bar component
- New query param `q` for search query

New: Search-bar component

---

packages/core/addon/components/pick-container.js
packages/data/addon/mirage/routes/bard-lite.js
packages/data/tests/unit/adapters/bard-facts-test.js
packages/data/tests/unit/adapters/dimensions/bard-test.js
packages/reports/addon/components/dimension-selector.js
packages/reports/addon/routes/reports/report.js
packages/reports/addon/routes/reports/report/view.js
packages/visualizations/addon/components/navi-visualizations/line-chart.js
packages/visualizations/addon/components/navi-visualizations/pie-chart.js
packages/visualizations/tests/dummy/app/controllers/goal-gauge.js
packages/visualizations/tests/dummy/app/controllers/line-chart.js
packages/visualizations/tests/dummy/app/controllers/metric-label.js
packages/visualizations/tests/dummy/app/controllers/pie-chart.js
packages/visualizations/tests/dummy/app/controllers/table.js
packages/visualizations/tests/integration/components/cell-renderers/total-test.js
packages/visualizations/tests/integration/components/navi-visualizations/table-test.js
packages/visualizations/tests/unit/component/navi-visualizations/line-chart-test.js
packages/visualizations/tests/unit/component/navi-visualizations/table-test.js

Update: Cleanup all jquery extends

Update: Cleanup all jquery extends

---

packages/directory/addon/components/dir-table.js
packages/directory/addon/controllers/directory/my-directory.js
packages/directory/addon/mixins/search-filter.js
packages/directory/addon/routes/directory.js
packages/directory/addon/routes/directory/my-directory.js
packages/directory/addon/templates/components/dir-search-bar.hbs
packages/directory/addon/templates/directory/my-directory.hbs
packages/directory/app/controllers/directory/my-directory.js
packages/directory/app/styles/navi-directory/components/dir-search-bar.less
packages/directory/tests/acceptance/dir-search-bar-test.js
packages/directory/tests/unit/mixins/search-filter-test.js

- Do not refresh model when search query changes
- Update search bar styles
- Add clear search icon

Do not refresh model when search query changes

---

packages/app/app/router.js
packages/app/app/styles/app.less
packages/app/app/styles/components/nav-bar.less
packages/app/app/styles/components/top-bar.less
packages/app/app/styles/views/landing.less
packages/app/app/templates/components/nav-bar.hbs
packages/app/app/templates/components/top-bar.hbs
packages/app/app/templates/landing.hbs
packages/app/package.json
packages/app/public/img/navi-graph.svg
packages/app/server-lib/utils.js

- Fix Mirage to use the right user
- Integrate Directory in App
- Restyle the landing page

Integrate directory in app

---

packages/core/app/styles/navi-core/common/dropdowns.less
packages/directory/addon/components/dir-new-button.js
packages/directory/addon/components/dir-table.js
packages/directory/addon/routes/directory.js
packages/directory/addon/templates/components/dir-table.hbs
packages/directory/addon/templates/directory/my-directory.hbs
packages/directory/addon/utils/enums/file-types.js
packages/directory/app/styles/navi-directory/components/dir-search-bar.less
packages/directory/app/styles/navi-directory/components/dir-table-filter.less
packages/directory/app/styles/navi-directory/components/dir-table.less
packages/directory/app/styles/navi-directory/components/index.less
packages/directory/package.json
packages/directory/tests/acceptance/dir-table-test.js

New: Add Table Filter Dropdown

New: Add Table Filter Dropdown

---

packages/directory/.npmignore

Fix: Remove bower.json from npmignore

Fix: Remove bower.json from npmignore

---

packages/directory/addon/components/dir-table-filter.js
packages/directory/addon/components/dir-table.js
packages/directory/addon/templates/components/dir-table-filter.hbs
packages/directory/addon/templates/components/dir-table.hbs
packages/directory/addon/templates/directory.hbs
packages/directory/addon/templates/directory/my-directory.hbs
packages/directory/app/components/dir-table-filter.js
packages/directory/app/styles/navi-directory/components/dir-new-button.less
packages/directory/app/styles/navi-directory/components/dir-table.less
packages/directory/app/styles/navi-directory/routes/directory.less

Directory style updates

---

packages/directory/addon/templates/components/dir-table.hbs
packages/directory/addon/templates/directory/my-directory.hbs
packages/directory/package.json
packages/directory/tests/integration/components/dir-table-test.js

Fix: Loader for the table that depends on the route model

---

packages/app/bower.json
packages/app/config/environment.js

- Remove faker from bower in app

Fix: Fix bower in app

---

packages/directory/addon/components/dir-table.js
packages/directory/addon/mixins/search-filter.js
packages/directory/addon/routes/directory/my-directory.js
packages/directory/addon/templates/components/dir-table.hbs
packages/directory/addon/templates/directory/my-directory.hbs
packages/directory/app/styles/navi-directory/components/dir-table.less
packages/directory/tests/integration/components/dir-table-test.js
packages/directory/tests/unit/mixins/search-filter-test.js

- Fix table loader
- Update info message styles and message on invalid search query

Fix Directory Table

---

packages/directory/addon/components/dir-sidebar.js
packages/directory/addon/templates/components/dir-sidebar.hbs

Update: Make favorites and recentlyUpdated global filters
Behaviour remains the same, and already tested in acceptance tests

Update: Make favorites and recentlyUpdated global filters

---

packages/directory/addon/routes/directory.js
packages/directory/tests/acceptance/directory-test.js

Update: Redirect from directory automatically to `my-directory`

Update: Redirect from directory automatically to `my-directory`

---

packages/directory/package.json

Build: Make light table and ember-responsive direct dependencies

Build: Make light table and ember-responsive direct dependencies

---

packages/directory/addon/controllers/directory.js
packages/directory/addon/controllers/directory/my-directory.js
packages/directory/addon/mixins/search-filter.js
packages/directory/addon/routes/directory.js
packages/directory/addon/routes/directory/index.js
packages/directory/addon/routes/directory/my-directory.js
packages/directory/app/routes/directory/index.js
packages/directory/tests/unit/mixins/search-filter-test.js

New: Move the redirect to the index route

New: Move the redirect to the index route

---

packages/core/addon/services/user.js
packages/core/app/services/user.js
packages/core/tests/.eslintrc.js
packages/core/tests/dummy/mirage/config.js
packages/core/tests/unit/services/user-test.js
packages/reports/app/services/user.js

Update: Move user service to core

Update: Move user service to core

---

packages/app/.eslintrc.js
packages/core/.eslintrc.js
packages/core/addon/components/navi-visualizations/table.js
packages/core/tests/.eslintrc.js
packages/core/tests/unit/components/navi-visualizations/table-test.js
packages/dashboards/.eslintrc.js
packages/directory/tests/.eslintrc.js
packages/reports/.eslintrc.js
packages/reports/tests/.eslintrc.js

The new public method is `computeColumnTotal`.

Update: Extract computation of metric column total to an overridable method

---

packages/directory/addon/templates/components/dir-new-button.hbs
packages/directory/tests/integration/components/dir-new-button-test.js

Singularize types new menu

---

packages/app/config/environment.js
packages/app/tests/acceptance/delete-transition-test.js
packages/reports/addon/consumers/item.js

Transition to directory when the 'enableDirectory' feature flag is enabled

Fix: Transition to directory on item deletion

---

packages/core/addon/models/deliverable-item.js
packages/core/tests/unit/models/deliverable-item-test.js

Add modelId property to deliverable-item
resolves #214

New: Add modelId property

---

packages/directory/addon/controllers/directory.js
packages/directory/addon/templates/directory.hbs
packages/directory/app/styles/navi-directory/components/dir-new-button.less
packages/directory/app/styles/navi-directory/components/dir-search-bar.less
packages/directory/app/styles/navi-directory/components/dir-table-filter.less
packages/directory/app/styles/navi-directory/routes/directory.less
packages/directory/tests/acceptance/directory-test.js

Update: Add table title

---

packages/data/addon/adapters/bard-facts.js

* Allow for overriding behavior based on format

Update: Adds options to dimension path in adapter

---

packages/dashboards/app/styles/navi-dashboards/components/navi-collection.less
packages/dashboards/app/styles/navi-dashboards/components/navi-dashboard.less

Before:
After:
Before: 
After:

Fix: Dashboard actions style in dashboard view

---

packages/core/addon/helpers/smart-format-number.js
packages/core/tests/integration/components/cell-renderers/metric-test.js
packages/core/tests/integration/components/navi-visualizations/table-test.js
packages/core/tests/integration/components/table-cell-renderer-test.js
packages/core/tests/unit/helpers/smart-format-number-test.js

* Detects if value has a decimal point in it.
* Uses that knowledge to figure if it should force decimal points in the formatter for numbers 0, and 1 through 100.

Update: Metric formatter only forces decimals when needed.

---

packages/data/.eslintignore
packages/data/.eslintrc.js
packages/data/.gitignore
packages/data/.npmignore
packages/data/.template-lintrc.js
packages/data/config/ember-try.js
packages/data/package.json
packages/data/testem.js
packages/data/tests/dummy/config/optional-features.json
packages/data/tests/integration/helpers/metric-format-test.js

Upgrade: Upgrade Data to 3.4

---

packages/reports/addon/templates/components/navi-table-select.hbs
packages/reports/addon/templates/partials/report-actions.hbs
packages/reports/app/styles/navi-reports/components/navi-table-select.less

Fix: Tooltip rendering messes up dropdown elements

---

packages/reports/addon/components/filter-values/date-range.js
packages/reports/addon/components/filter-values/date.js
packages/reports/addon/templates/components/filter-values/date.hbs
packages/reports/app/components/filter-values/date.js
packages/reports/app/styles/navi-reports/components/filter-collection.less
packages/reports/app/styles/navi-reports/components/filter-values.less
packages/reports/app/styles/navi-reports/components/navi-date-picker.less
packages/reports/app/styles/navi-reports/components/navi-date-range-picker.less
packages/reports/tests/integration/components/filter-values/date-test.js

Splitting up PR #253 
Single date selection filter value

Update: Add date filter value for selecting single date

---

packages/app/package.json
packages/core/addon/models/bard-request/fragments/filter.js
packages/core/package.json
packages/dashboards/package.json
packages/data/addon/mirage/fixtures/bard-meta-dimensions.js
packages/data/addon/models/metadata/dimension.js
packages/directory/package.json
packages/reports/addon/components/filter-builders/date-dimension.js
packages/reports/addon/components/filter-collection.js
packages/reports/addon/consumers/request/filter.js
packages/reports/app/components/filter-builders/date-dimension.js
packages/reports/package.json
packages/reports/tests/acceptance/date-filter-test.js
packages/reports/tests/dummy/config/environment.js
packages/reports/tests/integration/components/dimension-selector-test.js

Uses the date and date-range filter values to construct filters for dimensions with date values.

Update: Add date-dimension filter builder

---

packages/reports/addon/templates/components/filter-collection.hbs
packages/reports/addon/templates/components/report-builder.hbs
packages/reports/app/styles/navi-reports/components/report-builder.less
packages/reports/tests/integration/components/filter-collection-test.js

Moves the filter collection message to the top right of the filter collection container. This saves some vertical space.
Before: 
After:

Update: Move filter collection message

---

packages/core/app/styles/navi-core/components/navi-loader.less

Fixes height in for all loaders, and fix for firefox loaders as well.

Fix: Navi loader height

---

packages/core/addon/mirage/fixtures/report-collections.js
packages/core/addon/services/user.js
packages/core/app/mirage/fixtures/dashboard-collection.js
packages/dashboards/tests/unit/routes/dashboard-collections/index-test.js

Also made the user service handle server errors a bit better

Update: Add some new asset collections to mirage

---

packages/data/.eslintignore
packages/data/.eslintrc.js
packages/data/.gitignore
packages/data/.npmignore
packages/data/.travis.yml
packages/data/LICENSE.md
packages/data/README.md
packages/data/config/ember-try.js
packages/data/package.json

Update: Update navi-data to 3.7.x
Resolves #309

Update: Update navi-data to 3.7.x

---

packages/core/test-support/helpers/visit-without-wait.js
packages/core/test-support/helpers/wait-for-element.js
packages/dashboards/addon/routes/dashboards/dashboard/widgets/widget/edit.js
packages/dashboards/addon/templates/dashboards/dashboard/widgets/widget.hbs
packages/dashboards/app/routes/dashboards/dashboard/widgets/widget/edit.js
packages/dashboards/tests/.eslintrc.js
packages/dashboards/tests/acceptance/explore-widget-test.js
packages/dashboards/tests/helpers/start-app.js
packages/reports/addon/controllers/print/reports/report.js
packages/reports/addon/controllers/reports/report.js
packages/reports/addon/routes/print/reports/report.js
packages/reports/addon/routes/reports/report.js
packages/reports/addon/routes/reports/report/edit.js
packages/reports/addon/routes/reports/report/view.js
packages/reports/addon/templates/components/report-actions/save-as.hbs
packages/reports/addon/templates/components/report-view.hbs
packages/reports/addon/templates/reports/report.hbs
packages/reports/addon/templates/reports/report/edit.hbs
packages/reports/addon/templates/reports/report/view.hbs
packages/reports/app/controllers/print/reports/report.js
packages/reports/app/routes/reports/report/edit.js
packages/reports/app/styles/navi-reports/common/report.less
packages/reports/app/styles/navi-reports/components/index.less
packages/reports/app/styles/navi-reports/components/report-actions/save-as.less
packages/reports/tests/.eslintrc.js
packages/reports/tests/acceptance/navi-report-test.js
packages/reports/tests/helpers/start-app.js
packages/reports/tests/unit/controllers/reports/report-test.js

- Update: Add visit-without-wait & wait-for-element
- Update: Allow reports/widgets to be canceled  …
- Added `cancelReport` action
- Removed `setMode` action
- Extracted button from `save-as` model component
resolves #188

Cancel request

---

.github/PULL_REQUEST_TEMPLATE.md

New: PR Templates

---

README.md

Resolves #270, Resolves #272, Resolves #274, Resolves  #275 
Update to README
[Rendered](https://github.com/yahoo/navi/blob/8d7bcc172001c7f4818dfe5f8dffc64925fc2fd0/README.md)
- Added TOC
- Added a License section
- Added a Installation section
- Added a Contribution section
- NA

Update: Update the README

---

packages/core/tests/unit/models/bard-request/fragments/dimension-test.js
packages/core/tests/unit/models/bard-request/fragments/filter-test.js
packages/core/tests/unit/models/bard-request/fragments/sort-test.js
packages/core/tests/unit/models/bard-request/request-test.js
packages/core/tests/unit/models/dashboard-widget-test.js
packages/core/tests/unit/models/report-test.js
packages/core/tests/unit/models/user-test.js
packages/core/tests/unit/transforms/dimension-test.js
packages/core/tests/unit/transforms/metric-test.js
packages/core/tests/unit/transforms/table-test.js
packages/dashboards/addon/services/dashboard-data.js
packages/dashboards/tests/unit/routes/dashboards/dashboard/clone-test.js
packages/dashboards/tests/unit/routes/dashboards/dashboards-test.js
packages/dashboards/tests/unit/services/dashboard-data-test.js
packages/reports/tests/integration/components/print-report-view-test.js
packages/reports/tests/integration/components/report-view-test.js
packages/reports/tests/unit/consumers/delivery-rule-test.js
packages/reports/tests/unit/routes/reports/new-test.js

Apply global dashboard filters to widget requests if applicable.  Otherwise inject an error into the request response for that widget request.
- Apply global dashboard filters to widget requests if applicable.
- Otherwise inject an error into the request response for that widget request.
- Test

Apply dashboard filters

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

- Bug report Template
- Feature Request Template
Resolves #379

Create new issue templates

---

package-lock.json
packages/app/package-lock.json
packages/core/package-lock.json
packages/dashboards/package-lock.json
packages/data/package-lock.json
packages/directory/package-lock.json
packages/reports/package-lock.json

Fixes high severity vulnerability
```
│ Package       │ handlebars                                                   │
│ Dependency of │ lerna [dev]                                                  │
│ Path          │ lerna > conventional-changelog-cli > conventional-changelog  │
│               │ > conventional-changelog-core >                              │
│               │ conventional-changelog-writer > handlebars                   │
│ More info     │ https://nodesecurity.io/advisories/755  
```
- Update lock files

Fix: High severity vulnerability

---

package-lock.json
package.json

Resolves #369 
Bump lerna to latest version in package.json
NA
NA

Update: Bump lerna version

---

package-lock.json
package.json

This reverts commit 1920c65b9ccb8f9563052cf484efdf5be2c22b35.
- Reverting until we can figure out a solution for the publish failure

Revert "Update: Update lerna version"

---

packages/reports/index.js
packages/reports/package-lock.json
packages/reports/package.json

Latest json-url changed it's dist install. In the long run we need to change this over to ember-auto-import. But until we merge in 3.x reports upgrade this will have to do for now.
Update json-url and change import to reflect new file layout.

Fix: Adjust json-url import

---

packages/app/package-lock.json
packages/core/package-lock.json
packages/dashboards/package-lock.json
packages/data/package-lock.json
packages/directory/package-lock.json
packages/reports/package-lock.json

There are many references to our internal npm registry in our package-lock files.
- Remove references to internal npm registry

Update: Remove all internal registry references in package-lock files

---

packages/reports/addon/templates/components/filter-values/multi-value-input.hbs

Allows spaces in contains input.
- Allows spaces in multi value input tags.

Update: Change multi value input to allow spaces in tags.

---

packages/dashboards/app/styles/navi-dashboards/views/print-navi-dashboard.less

Allows multiple widgets to be printed.
- Fix

Fix: Print scrolling

---

packages/dashboards/app/styles/navi-dashboards/views/print-navi-dashboard.less

Turns out the fix didn't fix anything.  This is a fix to fix the fix.
- Fix the fix

Fix dashboard scroll

---

packages/core/addon/serializers/dashboard.js
packages/core/package-lock.json
packages/core/tests/unit/serializers/dashboard-test.js
packages/dashboards/package-lock.json
packages/data/package-lock.json

Existing dashboard models would not have an array value for filters so dashboard filters would throw errors when turned on.
- Normalize dashboard filter values that are null to be empty arrays

Fix: Normalize null dashboard filter values to empty array

---

packages/core/addon/adapters/base-json-adapter.js
packages/core/package-lock.json
packages/core/package.json

Part of #226 
Does not fully resolve it.
Update base json adapter to use fetch
- Use the AdapterFetch mixin provided by `ember-fetch`
NA

Update: Update base json adapter to use fetch

---

packages/core/addon/components/navi-visualizations/bar-chart.js
packages/core/addon/components/navi-visualizations/line-chart.js
packages/core/addon/components/visualization-config/line-chart.js
packages/core/addon/models/line-chart.js
packages/core/addon/templates/components/visualization-config/chart-type/date-time.hbs
packages/core/addon/templates/components/visualization-config/chart-type/metric.hbs
packages/core/addon/templates/components/visualization-config/line-chart.hbs
packages/core/addon/templates/components/visualization-config/wrapper.hbs
packages/core/app/styles/navi-core/common/buttons.less
packages/core/app/styles/navi-core/components/visualization-config/line-chart.less
packages/core/app/styles/navi-core/components/visualization-config/table.less
packages/core/app/styles/navi-core/utils/colors.less
packages/core/app/styles/navi-core/variables/colors.less
packages/core/app/styles/navi-core/visualizations/line-chart.less
packages/core/tests/acceptance/line-chart-test.js
packages/core/tests/integration/components/visualization-config/chart-type/date-time-test.js
packages/core/tests/integration/components/visualization-config/chart-type/metric-test.js
packages/core/tests/unit/components/navi-visualizations/line-chart-test.js
packages/core/tests/unit/models/line-chart-test.js

Add line style and area options to line charts.
- Add configuration section to line/bar charts
- for line charts add option to toggle line style between line, spline, and step
- Add toggle for area.
- Update chart colors. 

Line chart options

---

packages/core/addon/helpers/format-dimension.js
packages/core/package-lock.json
packages/core/tests/unit/helpers/format-dimension-test.js
packages/dashboards/addon/components/dashboard-filters-collapsed-filter.js
packages/dashboards/addon/templates/components/dashboard-filters-collapsed-filter.hbs

We had some inconsistent formatting of dimension names in the dashboard filters collapsed view compared to elsewhere in Navi.
- Use the dimension formatter for displaying dimension values in the dashboard filters collapsed view
- Add a field param to the formatDimension helper function

Update: Use dimension formatter for dashboard filters

---

.travis.yml

travis running tests twice, this doesn't seem to be the intention

Fix: Travis build runs tests twice

---

packages/app/config/environment.js
packages/core/addon/components/navi-visualizations/line-chart.js
packages/core/addon/components/visualization-config/line-chart.js
packages/core/addon/templates/components/visualization-config/line-chart.hbs
packages/core/app/styles/navi-core/components/visualization-config/line-chart.less
packages/core/config/environment.js
packages/core/tests/dummy/config/environment.js
packages/core/tests/integration/components/visualization-config/line-chart-test.js
packages/core/tests/unit/components/navi-visualizations/line-chart-test.js
packages/reports/tests/dummy/config/environment.js

Add stacked option to line and bar charts.
- Add toggle for stacked if chart has grouping or multiple metrics.

Stacked chart option

---

package-lock.json
packages/app/app/styles/views/application.less
packages/app/app/styles/views/dashboards.less
packages/app/app/styles/views/index.less
packages/app/app/styles/views/reports.less

Style changes in navi added a gray background to dashboards
- Adjust padding so that gray background stretches to left and right edges of window

Navi app style update

---

package-lock.json
package.json
packages/app/package-lock.json
packages/core/package-lock.json
packages/dashboards/package-lock.json
packages/directory/package-lock.json
packages/reports/package-lock.json

Resolves #429
Update lerna and navi version in package.json
- Update lerna and navi version in package.json
Premajor Update:

Update: Update lerna

---

packages/core/test-support/helpers/reorder.js

Resolves #433
Tests have flaked out lately
- Testing this now as I can no longer get these to flake out on my local machine. 

Fix: Flaky tests

---

.npmrc
packages/app/.npmrc
packages/core/.npmrc
packages/dashboards/.npmrc
packages/data/.npmrc
packages/directory/.npmrc
packages/reports/.npmrc

Create .npmrc configs

---

packages/app/package-lock.json
packages/data/package-lock.json

Update: Update package-lock.json files

---

packages/directory/addon/controllers/directory.js
packages/directory/addon/controllers/directory/my-data.js
packages/directory/addon/routes/directory.js
packages/directory/addon/templates/directory.hbs
packages/directory/addon/templates/directory/my-data.hbs
packages/directory/package-lock.json
packages/directory/package.json

Part of #451 
Remove direct route action invocation from navi-directory
- convert them to actions in controllers
NA

Update: Remove route-action from navi-directory

---

packages/app/package-lock.json
packages/core/addon/components/table-cell-renderer.js
packages/core/addon/templates/components/chart-series-config.hbs
packages/core/package-lock.json
packages/core/package.json
packages/core/tests/dummy/config/deprecation-workflow.js
packages/dashboards/package-lock.json
packages/data/package-lock.json
packages/directory/addon/templates/components/dir-table-filter.hbs
packages/directory/package-lock.json
packages/reports/addon/templates/components/navi-list-selector.hbs
packages/reports/addon/templates/reports/report/edit.hbs
packages/reports/package-lock.json
packages/reports/tests/dummy/config/deprecation-workflow.js

Need to update some libraries to get projects working easier
- update package-locks, and ember-intl to latest stable.
- updating added to template lint, forbidding adding event handlers on certain components without the `role` attribute.
- updating seems to have stricter names for `{{component}}` tag requiring dasherizing the name
- added a deprecation to deprecation workflow, it's an easy one to fix, but we would need to drop support for ember 2.x

Update: Dependencies

---

packages/reports/addon/routes/reports/new.js

Found issue in which deserialized reports no longer work
- instead of trying to mutate something already in the store, clone a newly created record.

Fix: Clone model for deserialized model

---

packages/app/package-lock.json
packages/core/addon/models/dashboard.js
packages/core/addon/models/fragments/layout.js
packages/core/addon/models/fragments/presentation.js
packages/core/app/models/fragments/layout.js
packages/core/package-lock.json
packages/dashboards/addon/components/navi-widget.js
packages/dashboards/addon/routes/dashboards/dashboard.js
packages/dashboards/addon/routes/dashboards/dashboard/clone.js
packages/dashboards/addon/routes/dashboards/dashboard/view.js
packages/dashboards/addon/routes/dashboards/dashboard/widgets/add.js
packages/dashboards/addon/templates/components/navi-dashboard.hbs
packages/dashboards/addon/templates/components/navi-widget.hbs
packages/dashboards/addon/templates/dashboards/dashboard/view.hbs
packages/dashboards/package-lock.json
packages/dashboards/tests/acceptance/dashboards-test.js
packages/dashboards/tests/unit/routes/dashboards/dashboard/widgets/add-test.js
packages/dashboards/tests/unit/routes/dashboards/dashboards-test.js
packages/data/package-lock.json
packages/directory/package-lock.json
packages/reports/package-lock.json

A number of issues with dashboards causing issues:
* Events being handled in non-deterministic order causing strange behavior.
* Rehydration of gridstack causes strange behavior.
* replacing whole layout object causing slow performance
- Change `layout` to a fragment array so changes and state can be observed easier.
- columns passed to ember-gridstack changed to prop to prevent double rendering.
- get rid of redundant events and `_stagedLayout`. in favor of one change event handler.
- Make sure that one way binding is handled correctly down to ember-grid-items.

Fix: Dashboard misbehavior

---

packages/core/addon/models/dashboard.js
packages/core/addon/models/fragments/presentation.js
packages/dashboards/addon/routes/dashboards/dashboard.js
packages/dashboards/addon/routes/dashboards/dashboard/clone.js
packages/dashboards/tests/unit/routes/dashboards/dashboards-test.js

Though tested in a Ember 2.x, the PR changes that were done before the PR merged broke 2.x compatibility.
- Restore Ember 2.x compatibility.

Fix: Ember 2.x fixes

---

packages/core/tests/acceptance/table-test.js

Test is failing and is not in a reproducible state due to buggy reorder helper
- SKip for now, issued open to visit this problem later.

Build: SKip flaky test

---

.travis.yml

Resolves #
Bower install breaking publish build
- remove bower run in travis.

Fix: Bower breaking publish

---

scripts/gh-pages-publish.sh

- Apparently `travis_wait` doesn't exist during deploy stage https://github.com/travis-ci/travis-ci/issues/7961
- Just revert for now

Update: Fix no travis_wait in deploy

---

packages/core/addon/components/navi-button.js
packages/core/addon/templates/components/navi-button.hbs
packages/core/app/components/navi-button.js
packages/core/app/styles/navi-core/components/index.less
packages/core/app/styles/navi-core/components/navi-button.less
packages/core/tests/dummy/app/router.js
packages/core/tests/dummy/app/routes/buttons.js
packages/core/tests/dummy/app/styles/app.less
packages/core/tests/dummy/app/templates/application.hbs
packages/core/tests/dummy/app/templates/buttons.hbs
packages/core/tests/integration/components/navi-button-test.js
packages/reports/addon/templates/reports/report.hbs
packages/reports/tests/acceptance/navi-report-test.js

Refactor buttons with NaviButton components
Needs Ember 3.4 or https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill
- Add NaviButton component
- Add NaviButton to dummy app
- Use NaviButton in reports footer

Navi button

---

README.md

Include npm badges in the readme

Update: Include npm badges to readme

---

packages/core/app/styles/navi-core/common/spinner.less
packages/core/package-lock.json
packages/dashboards/package-lock.json
packages/data/package-lock.json
packages/directory/package-lock.json
packages/reports/addon/components/navi-loading-message.js
packages/reports/addon/templates/components/common-actions/delete.hbs
packages/reports/addon/templates/components/common-actions/schedule.hbs
packages/reports/addon/templates/components/dimension-bulk-import.hbs
packages/reports/addon/templates/components/dimension-selector.hbs
packages/reports/addon/templates/components/metric-selector.hbs
packages/reports/addon/templates/components/navi-loading-message.hbs
packages/reports/app/components/loading-message.js
packages/reports/app/components/navi-loading-message.js
packages/reports/app/styles/navi-reports/components/index.less
packages/reports/app/styles/navi-reports/components/navi-loading-message.less
packages/reports/app/styles/navi-reports/components/navi-modal.less
packages/reports/app/styles/navi-reports/components/schedule-modal.less
packages/reports/package-lock.json
packages/reports/tests/integration/components/dimension-bulk-import-test.js
packages/reports/tests/integration/components/navi-loading-message-test.js

Resolves #38 
- Namespace loading message component
- rename component to `navi-loading-message`
- Did not move to core as specified in the issue since this component is only used in reports
NA

Update: Namespace loading-message component

---

packages/core/README.md
packages/core/package-lock.json
packages/core/package.json
packages/core/tests/.eslintrc.js
packages/core/tests/dummy/config/environment.js
packages/core/tests/integration/components/navi-vis-c3-chart-test.js
packages/core/tests/integration/components/navi-visualizations/pie-chart-test.js
packages/core/tests/integration/components/navi-visualizations/table-print-test.js
packages/core/tests/integration/components/navi-visualizations/table-test.js
packages/core/tests/unit/helpers/default-config-test.js
packages/core/tests/unit/helpers/navi-get-display-list-test.js
packages/core/tests/unit/helpers/navi-get-display-name-test.js
packages/data/package-lock.json

Blocked by #559 
Update Core to Ember.12
-

Update Core to Ember 3.12

---

packages/core/blueprints/navi-core/index.js
packages/reports/blueprints/navi-reports/index.js

Resolves #
Add blueprints to add default dependencies
Needs #561
n/a 

Add blueprints to add default dependencies

---

packages/app/config/environment.js
packages/core/addon/components/navi-visualization-config/line-chart.js
packages/core/config/environment.js
packages/core/tests/dummy/config/environment.js
packages/reports/tests/dummy/config/environment.js

Removes feature flag that's no longer needed.
- Remove feature flag

Update: Cleanup unneeded feature flag chart stack

---

packages/reports/.eslintrc.js
packages/reports/addon/components/navi-table-select-trigger.js
packages/reports/addon/templates/components/navi-table-select-item.hbs
packages/reports/addon/templates/components/navi-table-select-trigger.hbs
packages/reports/addon/templates/components/navi-table-select.hbs
packages/reports/app/components/navi-table-select-trigger.js
packages/reports/app/styles/navi-reports/components/index.less
packages/reports/app/styles/navi-reports/components/navi-table-select-item.less
packages/reports/app/styles/navi-reports/components/navi-table-select-trigger.less
packages/reports/app/styles/navi-reports/components/navi-table-select.less
packages/reports/package-lock.json
packages/reports/package.json
packages/reports/tests/integration/components/navi-table-select-test.js

Refactor table selector
- Add babel-eslint to navi-reports
- Style table selector similar to other power selects
- Use info icon for tooltips as done with metrics and dimensions
Before:
After:

Table selector

---

packages/webservice/README.md

The docs for webservice should be a little more friendly
Add better docs for installing. [Rendered output](https://github.com/yahoo/navi/blob/57cdeaef5202087bcad17265d63a3fea96bc4561/packages/webservice/README.md)

Update: Webservice installation docs

---

packages/reports/addon/templates/components/navi-table-select-item.hbs

Remove unneeded table tooltip code
Remove unneeded table tooltip code
`

Update: Remove unneeded table tooltip code

---

packages/dashboards/tests/acceptance/dashboards-test.js

Adds test verifying #584 (I checked back and made sure this fails when `shouldBackgroundReloadRecord` returns `true`)

Update: Add test verifying dashboard behavior

---

packages/app/package-lock.json
packages/core/package-lock.json
packages/core/package.json
packages/dashboards/package-lock.json
packages/dashboards/package.json
packages/directory/package-lock.json
packages/directory/package.json
packages/notifications/package-lock.json
packages/reports/package-lock.json
packages/reports/package.json

Resolves #578 
Upgrade version of ember-cp-validations
- Upgrade version of ember-cp-validations

Upgrade: Upgrade ember-cp-validations (fixes #578)

---

packages/data/addon/models/bard-facts.js
packages/data/addon/models/navi-facts.js
packages/data/addon/services/bard-facts.js
packages/data/app/models/bard-facts.js
packages/data/app/models/navi-facts.js
packages/data/package-lock.json
packages/data/tests/unit/models/bard-facts-model-test.js
packages/data/tests/unit/models/navi-facts-model-test.js
packages/data/tests/unit/services/bard-facts-test.js

**BREAKING CHANGE**
-  Rename the bard-facts model to something more appropriate 
- Move the fetchNext and fetchPrevious methods from model to service

Rename bard facts model

---

packages/webservice/build.gradle.kts
packages/webservice/models/build.gradle.kts

Bump elide version in webservice package and added/modified necessary packages for the build to work.
- Bump elide version in webservice package
- Publish sources jar for webservice models

Bump elide

---

packages/app/package-lock.json
packages/app/package.json
packages/core/app/styles/navi-core/variables/colors.less
packages/core/package-lock.json
packages/core/package.json
packages/directory/package-lock.json
packages/directory/package.json
packages/reports/addon/components/navi-request-column-config/base.js
packages/reports/addon/components/navi-request-preview.js
packages/reports/addon/templates/components/navi-request-column-config/base.hbs
packages/reports/addon/templates/components/navi-request-preview.hbs
packages/reports/app/components/navi-request-column-config/base.js
packages/reports/app/components/navi-request-preview.js
packages/reports/app/styles/navi-reports/components/index.less
packages/reports/app/styles/navi-reports/components/navi-request-column-config.less
packages/reports/app/styles/navi-reports/components/navi-request-preview.less
packages/reports/package-lock.json
packages/reports/package.json
packages/reports/tests/integration/components/navi-request-config/base-test.js
packages/reports/tests/integration/components/navi-request-preview-test.js

We want to work towards the new design for Navi's report builder. The first step is implementing the request preview. This will just add the component to Navi, but not actually instantiate it anywhere.
- Add `navi-request-preview` component
- Add `navi-request-column-config/base` component to use as a base for upcoming column configs

Update: Add Navi Request Preview Component

---

packages/reports/app/styles/navi-reports/components/grouped-list.less

Add pointer cursor to group header
Add pointer cursor to group header

Update: Add cursor to group header

---

packages/core/package-lock.json
packages/dashboards/package-lock.json
packages/dashboards/package.json
packages/reports/package-lock.json
packages/reports/package.json

Update: Update liquid-fire versions to the latest

Update: Update liquid-fire versions to the latest

---

packages/app/app/templates/components/top-bar.hbs
packages/app/app/templates/landing.hbs
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/User.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/permissions/PermissionExpressions.kt

Found a few issues when integrating models
- Add a @JvmField to PermissionExpressions.expressions so that Java code can access the field.
- Need to add a @get field so join table is correct for favorited dashboards
- Absolutely link img assets.

Fix: Webservice integration issues.

---

packages/core/addon/components/navi-visualizations/table.js
packages/core/addon/templates/components/chart-series-config.hbs
packages/core/addon/templates/components/navi-visualizations/table.hbs
packages/core/addon/templates/components/table-renderer-vertical-collection.hbs
packages/core/addon/templates/components/table-renderer.hbs
packages/core/package-lock.json
packages/core/package.json
packages/core/tests/integration/components/navi-visualizations/table-print-test.js
packages/core/tests/test-helper.js
packages/dashboards/package-lock.json
packages/dashboards/package.json
packages/directory/package-lock.json
packages/directory/package.json
packages/reports/package-lock.json
packages/reports/package.json
packages/reports/tests/acceptance/report-visualizations-test.js

When using a table widget on a dashboard, dragging the name would attempt to reorder the column, but would also move the widget itself
- Update ember-sortable
- Disable dragging when inside of a widget

Update: Disable column reordering inside navi widget

---

packages/app/app/templates/components/top-bar.hbs
packages/app/app/templates/landing.hbs

Update: Demo app logo url

---

packages/reports/addon/components/navi-date-picker.js
packages/reports/tests/integration/components/navi-date-picker-test.js

calendar couldn't change center
ember set

Update: Calendar nav

---

packages/data/addon/builder/request.js

Overriding the computed properties kept throwing warnings and it was too noisy for me

Update: Native classify request builder

---

packages/core/.bowerrc

Update: Remove .bowerrc

---

.travis.yml
packages/core/.eslintrc.js
packages/core/addon/components/lazy-render.js
packages/core/tests/integration/components/lazy-render-test.js
packages/dashboards/.eslintrc.js
packages/dashboards/tests/acceptance/dashboards-test.js
packages/dashboards/tests/acceptance/schedule-modal-test.js
packages/dashboards/tests/acceptance/share-link-test.js
packages/data/blueprints/navi-data/index.js
packages/directory/addon/components/dir-asset-row-actions.js
packages/directory/tests/integration/components/dir-asset-row-actions-test.js
packages/reports/.eslintrc.js
packages/reports/tests/acceptance/navi-report-test.js
packages/reports/tests/acceptance/schedule-modal-test.js
packages/reports/tests/acceptance/share-link-test.js

Resolves #658 
Resolves #635 
Resolves #669 
- Updates eslint rules
- Get rid of .travis.yml warnings
- remove a little jquery 🎉 

Some minor cleanup

---

packages/data/addon/mirage/routes/bard-lite.js
packages/data/package-lock.json

Update: BardLite - Allow any key in dimension value beyond just id and description

Update: BardLite - Allow any key in dimension value

---

packages/app/package-lock.json
packages/core/package-lock.json
packages/dashboards/package-lock.json
packages/notifications/.editorconfig
packages/notifications/.eslintrc.js
packages/notifications/.template-lintrc.js
packages/notifications/README.md
packages/notifications/config/ember-try.js
packages/notifications/package-lock.json
packages/notifications/package.json
packages/notifications/testem.js
packages/notifications/tests/dummy/app/app.js
packages/notifications/tests/dummy/app/resolver.js
packages/notifications/tests/dummy/app/router.js
packages/notifications/tests/dummy/app/templates/application.hbs
packages/notifications/tests/dummy/config/optional-features.json
packages/reports/package-lock.json

Resolves #608 
Upgrade notification to octane

Update: Upgrade notifications to octane

---

packages/data/.editorconfig
packages/data/.eslintrc.js
packages/data/.template-lintrc.js
packages/data/README.md
packages/data/config/ember-try.js
packages/data/package-lock.json
packages/data/package.json
packages/data/testem.js
packages/data/tests/dummy/app/app.js
packages/data/tests/dummy/app/resolver.js
packages/data/tests/dummy/app/router.js
packages/data/tests/dummy/config/optional-features.json
packages/data/tests/integration/helpers/metric-format-test.js

Resolves #606 
Upgrade data to octane

Update: Upgrade data to octane

---

package.json

Update: Add lerna stream to npm test
Update: Add lerna stream to npm test

Update: Add lerna stream to npm test

---

packages/app/package.json
packages/dashboards/package-lock.json
packages/dashboards/package.json
packages/directory/ember-cli-build.js
packages/directory/package.json
packages/reports/index.js
packages/reports/package-lock.json
packages/reports/package.json
packages/search/package.json

resolves #701
Remove optional-chaining as it is in babel now
Remove optional-chaining as it is in babel now
n/a

Update: Remove optional-chaining as it is in babel

---

packages/core/index.js
packages/dashboards/index.js
packages/data/index.js
packages/directory/index.js
packages/notifications/index.js
packages/reports/index.js
packages/search/index.js

Set `isDevelopingAddon` to $DEV_NAVI
1. `$ export DEV_NAVI=true`
2. `$ ember s`
3.  Save a file in a navi package
4. ✨🎩✨ (live reload app/addon)

Update: Set isDevelopingAddon to $DEV_NAVI

---

packages/core/app/helpers/ember-array.js
packages/core/package-lock.json
packages/core/package.json
packages/dashboards/package-lock.json
packages/dashboards/package.json
packages/directory/package-lock.json
packages/directory/package.json
packages/reports/package-lock.json
packages/reports/package.json

`ember-composable-helpers` to `3.1.1` 

Update: Ember-composable-helpers to 3.1.1

---

packages/reports/addon-test-support/report-builder.js
packages/reports/addon/components/navi-column-config/metric.js
packages/reports/addon/templates/components/metric-config.hbs
packages/reports/addon/templates/components/navi-column-config/base.hbs
packages/reports/addon/templates/components/navi-column-config/metric.hbs
packages/reports/app/styles/navi-reports/components/navi-column-config.less
packages/reports/app/styles/navi-reports/components/navi-column-config/item.less
packages/reports/tests/acceptance/column-config-test.js
packages/reports/tests/acceptance/metric-parameters-test.js
packages/reports/tests/integration/components/metric-config-test.js
packages/reports/tests/integration/components/navi-column-config/metric-test.js

Resolves some small issues we've found in the column config
- Font family not being applied so bold doesn't work as expected
- Searching a metrics parameters is not working
- Column relabeling was visible in the UI, but not functional so we've hidden it for now

Column config fixups

---

packages/reports/addon/templates/components/dimension-selector.hbs
packages/reports/addon/templates/components/metric-selector.hbs
packages/reports/addon/templates/components/navi-column-config/item.hbs
packages/reports/app/styles/navi-reports/components/navi-column-config/item.less
packages/reports/app/styles/navi-reports/components/report-builder.less

Distinguish between dimensions and metrics in column config

Update: Distinguish between dimensions and metrics in column config

---

packages/reports/addon/components/navi-column-config/metric.js
packages/reports/addon/components/report-view.js
packages/reports/addon/templates/components/metric-selector.hbs
packages/reports/addon/templates/components/navi-column-config/metric.hbs
packages/reports/app/styles/navi-reports/components/report-builder.less
packages/reports/app/styles/navi-reports/components/report-view.less
packages/reports/tests/integration/components/navi-column-config/metric-test.js

Some small cleanup
- missing metric selector icon
- smaller metric/dimension selector
- less margin for visualization
- don't show parameters id
Before | After

Update: Small UX cleanup for column config

---

packages/dashboards/addon/templates/dashboard-collections/index.hbs

Global Dashboard Collection route no longer works
- Fix closing bracket in template

Fix: Wrong closing bracket

---

packages/dashboards/.eslintrc.js
packages/dashboards/addon/routes/dashboards.ts
packages/dashboards/addon/routes/dashboards/dashboard.js
packages/dashboards/config/environment.d.ts
packages/dashboards/index.js
packages/dashboards/package-lock.json
packages/dashboards/package.json
packages/dashboards/tests/dummy/app/config/environment.d.ts
packages/dashboards/tests/dummy/config/deprecation-workflow.js
packages/dashboards/tests/dummy/config/environment.d.ts
packages/dashboards/tests/integration/components/dashboard-actions/add-widget-test.js
packages/dashboards/tests/integration/components/dashboard-dimension-selector-test.js
packages/dashboards/tests/integration/components/navi-dashboard-test.js
packages/dashboards/tests/integration/components/navi-widget-test.js
packages/dashboards/tests/integration/components/report-actions/add-to-dashboard-test.js
packages/dashboards/tests/test-helper.ts
packages/dashboards/tests/unit/controllers/dashboards/dashboard/view-test.js
packages/dashboards/tests/unit/routes/dashboards/dashboard/widgets/widget-test.js
packages/dashboards/tests/unit/routes/dashboards/dashboards-test.js
packages/dashboards/tests/unit/routes/dashboards/index-test.js
packages/dashboards/tsconfig.json
packages/dashboards/types/ember-data/types/registries/model.d.ts
packages/dashboards/types/global.d.ts

Set up typescript for navi-dashboards
- some eslint/prettier fixes

Install typescript navi dashboards

---

packages/dashboards/tests/acceptance/dashboard-collections-test.js

Adds Test for PR: #762 
- First PR was created in a hurry to fix production issue.
- Follow up test.

Fix: Add test

---

packages/reports/addon/components/editable-label.js
packages/reports/addon/templates/components/dimension-bulk-import-simple.hbs
packages/reports/addon/templates/components/dimension-selector.hbs
packages/reports/addon/templates/components/dropdown-date-picker.hbs
packages/reports/addon/templates/components/editable-label.hbs
packages/reports/tests/dummy/app/templates/application.hbs
packages/reports/tests/integration/components/editable-label-test.js

Some small octane template changes

Update: Some cleanup

---

packages/search/.eslintrc.js
packages/search/addon/components/navi-search-result/definition.ts
packages/search/addon/services/navi-search/navi-definition-search-provider.js
packages/search/config/environment.d.ts
packages/search/package-lock.json
packages/search/package.json
packages/search/tests/dummy/app/config/environment.d.ts
packages/search/tests/dummy/config/ember-intl.js
packages/search/tests/dummy/config/targets.js
packages/search/tests/integration/components/navi-search-result/asset-test.js
packages/search/tsconfig.json
packages/search/types/@ember/service/index.d.ts
packages/search/types/ember-data/types/registries/model.d.ts
packages/search/types/global.d.ts

Resolves #777 
Install tyepscript
- small eslint fixes, the usual

Install typescript navi search

---

packages/reports/addon/components/filter-builders/base.js
packages/reports/addon/components/filter-builders/date-dimension.js
packages/reports/addon/components/filter-builders/date-time.js
packages/reports/addon/components/filter-builders/dimension.js
packages/reports/addon/components/filter-builders/metric.js
packages/reports/addon/templates/components/filter-builders/base.hbs
packages/reports/addon/templates/components/filter-builders/collapsed.hbs
packages/reports/addon/templates/components/filter-builders/dimension.hbs
packages/reports/addon/templates/components/filter-builders/metric.hbs
packages/reports/addon/templates/components/filter-collection.hbs
packages/reports/tests/integration/components/filter-builders/base-test.js
packages/reports/tests/unit/components/filter-builders/dimension-test.js
packages/reports/tests/unit/components/filter-builders/metric-test.js

Resolves #782 
Convert filter builder components to octane

Update: Octane filter builders

---

packages/notifications/.eslintrc.js
packages/notifications/config/environment.d.ts
packages/notifications/package-lock.json
packages/notifications/package.json
packages/notifications/tests/dummy/app/config/environment.d.ts
packages/notifications/tests/dummy/app/controllers/application.ts
packages/notifications/tests/dummy/mirage/config.js
packages/notifications/tests/test-helper.ts
packages/notifications/tsconfig.json
packages/notifications/types/@ember/service/index.d.ts
packages/notifications/types/global.d.ts
packages/search/package-lock.json

Resolves #778 
Install typescript
- Set up typescript support, but ember-cli-flash types are out of date

Install typescript navi notifications

---

packages/core/addon/mirage/utils/rsql-utils.js
packages/search/addon/services/navi-search/navi-asset-search-provider.js
packages/search/tests/integration/components/navi-search-result/asset-test.js
packages/search/tests/unit/services/navi-search/navi-asset-search-provider-test.js

Resolves #
Improvements on Asset search provider
- Limit number of results returned
- Sort returned results by relevance to the query
- Update author query

Update: Update asset provider

---

packages/reports/addon/components/navi-column-config.js
packages/reports/tests/integration/components/navi-column-config-test.js

Fixes a bug with column config where we don't pass the datasource
- Pass the datasource

Fix: Multi data source support in column config

---

packages/reports/addon/components/dimension-selector.js
packages/reports/addon/components/navi-column-config.js
packages/reports/addon/components/navi-column-config/item.js
packages/reports/addon/consumers/request/time-grain.js
packages/reports/addon/controllers/reports/report.js
packages/reports/addon/templates/components/dimension-selector.hbs
packages/reports/addon/templates/components/navi-column-config.hbs
packages/reports/addon/templates/components/navi-column-config/base.hbs
packages/reports/addon/templates/components/navi-column-config/item.hbs
packages/reports/app/styles/navi-reports/components/grouped-list.less
packages/reports/tests/acceptance/column-config-test.js
packages/reports/tests/acceptance/report-test.js
packages/reports/tests/integration/components/dimension-selector-test.js
packages/reports/tests/integration/components/navi-column-config-test.js
packages/reports/tests/unit/consumers/request/time-grain-test.js

Column config accordion
- Only one open column at a time
- Enable clicking Date Time in the dimension selector even if it's already added. The action will open and highlight the column, if it's not already open.

Update: Column config accordion

---

packages/core/addon/chart-builders/date-time.js
packages/core/addon/chart-builders/metric.js
packages/core/addon/components/navi-cell-renderers/date-time.js
packages/core/addon/components/navi-cell-renderers/dimension.js
packages/core/addon/components/navi-cell-renderers/metric.js
packages/core/addon/components/navi-cell-renderers/threshold.js
packages/core/addon/components/navi-cell-renderers/total.js
packages/core/addon/components/navi-visualizations/bar-chart.js
packages/core/addon/components/navi-visualizations/goal-gauge.js
packages/core/addon/components/navi-visualizations/line-chart.js
packages/core/addon/components/navi-visualizations/metric-label.js
packages/core/addon/components/navi-visualizations/pie-chart.js
packages/core/addon/components/navi-visualizations/table-print.js
packages/core/addon/components/navi-visualizations/table.js
packages/core/addon/templates/components/navi-cell-renderers/date-time.hbs
packages/core/addon/templates/components/navi-cell-renderers/metric.hbs
packages/core/addon/templates/components/navi-cell-renderers/threshold.hbs
packages/core/addon/templates/components/navi-cell-renderers/total.hbs
packages/core/addon/templates/components/navi-visualizations/metric-label.hbs
packages/core/addon/utils/chart-data.js

Ember get is bad
- Remove bad ember get from navi visualizations components

Update: Remove Ember get from navi-visualizations

---

packages/app/config/environment.js
packages/core/app/styles/navi-core/vendor/navi-ember-basic-dropdown.less
packages/core/app/styles/navi-core/vendor/navi-ember-power-select.less
packages/dashboards/app/styles/navi-dashboards/components/dashboard-filters.less
packages/reports/app/styles/navi-reports/components/filter-builder.less
packages/reports/app/styles/navi-reports/components/filter-collection.less
packages/reports/app/styles/navi-reports/components/filter-values.less
packages/reports/app/styles/navi-reports/components/grouped-list.less
packages/reports/app/styles/navi-reports/components/navi-column-config.less
packages/reports/app/styles/navi-reports/components/navi-column-config/base.less
packages/reports/app/styles/navi-reports/components/navi-column-config/item.less
packages/reports/tests/dummy/config/environment.js

Normalize font sizes and spacing
- Use `@font-size-basse` (14px) in most places
- Less margin around column config
- Enable request preview by default (hope the tests pass :) )

Update: Normalize font sizes and spacing

---

README.md

Use the travis-ci.com link from the readme

Update: Build link to travis-ci.com

---

packages/core/app/styles/navi-core/vendor/navi-ember-power-select.less

- Wrap power select multiple options 
- Wrap power select multiple options 

Update: Wrap power select multiple options

---

packages/admin/addon/controllers/admin.ts
packages/admin/addon/templates/admin.hbs
packages/admin/app/controllers/admin.js
packages/admin/app/styles/navi-admin.less
packages/admin/app/styles/navi-admin/index.less
packages/admin/app/styles/navi-admin/views/admin.less
packages/admin/app/styles/navi-admin/views/index.less
packages/admin/package-lock.json
packages/admin/package.json
packages/admin/public/assets/img/navi-graph.svg
packages/admin/public/assets/img/navi-logo.svg
packages/admin/public/robots.txt
packages/admin/tests/acceptance/admin-test.ts
packages/admin/tests/dummy/app/styles/app.less
packages/admin/tests/dummy/app/templates/application.hbs
packages/admin/tests/dummy/public/assets/img/navi-graph.svg
packages/admin/tests/dummy/public/assets/img/navi-logo.svg

Resolves #
Add Admin route view
- Add Admin route view

New: Implement admin route view

---

packages/reports/addon/components/filter-values/advanced-interval-input.js
packages/reports/addon/components/filter-values/current-period.js
packages/reports/addon/components/filter-values/date-range.js
packages/reports/addon/components/filter-values/date.js
packages/reports/addon/components/filter-values/dimension-date-range.js
packages/reports/addon/components/filter-values/dimension-select.js
packages/reports/addon/components/filter-values/invalid-value.js
packages/reports/addon/components/filter-values/lookback-input.js
packages/reports/addon/components/filter-values/multi-value-input.js
packages/reports/addon/components/filter-values/range-input.js
packages/reports/addon/components/filter-values/since-input.js
packages/reports/addon/components/filter-values/value-input.js
packages/reports/addon/templates/components/filter-values/date-range.hbs
packages/reports/addon/templates/components/filter-values/dimension-date-range.hbs
packages/reports/addon/templates/components/filter-values/lookback-input.hbs
packages/reports/addon/templates/components/filter-values/multi-value-input.hbs
packages/reports/addon/templates/components/navi-column-config/base.hbs
packages/reports/addon/templates/report-collections/collection.hbs
packages/reports/addon/templates/report-collections/error.hbs
packages/reports/addon/templates/report-collections/index.hbs
packages/reports/addon/templates/report-collections/loading.hbs

Resolves #856 
Some octane upgrades for reports

Reports octane small

---

packages/dashboards/addon/templates/components/dashboard-action-list.hbs
packages/dashboards/addon/templates/dashboards/dashboard/widgets/widget.hbs
packages/reports/addon/components/common-actions/delete.js
packages/reports/addon/components/common-actions/get-api.js
packages/reports/addon/components/common-actions/schedule.js
packages/reports/addon/components/common-actions/share.js
packages/reports/addon/templates/components/common-actions/delete.hbs
packages/reports/addon/templates/components/common-actions/get-api.hbs
packages/reports/addon/templates/components/common-actions/schedule.hbs
packages/reports/addon/templates/components/common-actions/share.hbs
packages/reports/addon/templates/partials/report-actions.hbs
packages/reports/addon/templates/report-collections/loading.hbs
packages/reports/addon/templates/reports/report/loading.hbs
packages/reports/app/styles/navi-reports/components/navi-collection.less
packages/reports/tests/integration/components/common-actions/delete-test.js
packages/reports/tests/integration/components/common-actions/get-api-test.js
packages/reports/tests/integration/components/common-actions/schedule-test.js
packages/reports/tests/integration/components/common-actions/share-test.js

Octane common-actions in reports

Reports octane another

---

packages/data/addon/adapters/bard-facts-v2.ts
packages/data/addon/adapters/bard-facts.ts
packages/data/addon/adapters/fact-interface.ts

Resolves #855
Add async fetch adapter interface
- Add async fetch adapter interface based on async RFC

Update: Add async fetch adapter interface

---

packages/reports/addon/components/report-builder.js
packages/reports/addon/controllers/reports/report.js
packages/reports/addon/templates/components/favorite-item.hbs
packages/reports/addon/templates/components/navi-date-picker.hbs
packages/reports/addon/templates/components/navi-loading-message.hbs
packages/reports/addon/templates/components/navi-table-select-item.hbs
packages/reports/addon/templates/components/print-report-view.hbs
packages/reports/addon/templates/components/report-builder.hbs
packages/reports/addon/templates/components/report-view.hbs
packages/reports/addon/templates/components/report-visualization.hbs
packages/reports/addon/templates/components/unauthorized-table.hbs
packages/reports/addon/templates/reports-print/reports/report.hbs
packages/reports/addon/templates/reports-print/reports/report/view.hbs
packages/reports/addon/templates/reports/error.hbs
packages/reports/addon/templates/reports/index.hbs
packages/reports/addon/templates/reports/report.hbs
packages/reports/addon/templates/reports/report/error.hbs
packages/reports/addon/templates/reports/report/unauthorized.hbs

A few more octane fixups for reports

Some more reports octane

---

packages/core/addon/templates/components/navi-cell-renderers/total.hbs
packages/core/addon/templates/components/navi-table-sort-icon.hbs
packages/dashboards/addon/templates/components/navi-dashboard.hbs
packages/dashboards/addon/templates/dashboards/dashboard/widgets/widget.hbs
packages/dashboards/app/styles/navi-dashboards/components/navi-collection.less
packages/dashboards/tests/acceptance/schedule-modal-test.js
packages/reports/addon/components/navi-action-list.js
packages/reports/addon/components/navi-email-tag.js
packages/reports/addon/components/navi-tag-input/tag.js
packages/reports/addon/templates/components/common-actions/schedule.hbs
packages/reports/addon/templates/components/navi-action-list.hbs
packages/reports/addon/templates/components/navi-tag-input.hbs
packages/reports/addon/templates/components/navi-tag-input/tag.hbs
packages/reports/addon/templates/components/power-select-bulk-import-trigger.hbs
packages/reports/addon/templates/components/power-select-collection-options.hbs
packages/reports/addon/templates/components/power-select-search-trigger.hbs
packages/reports/addon/templates/components/report-actions/multiple-format-export.hbs
packages/reports/app/styles/navi-reports/components/navi-collection.less
packages/reports/app/styles/navi-reports/components/reports-index.less
packages/reports/app/styles/navi-reports/vendor/ember-tag-input.less
packages/reports/tests/acceptance/schedule-modal-test.js
packages/reports/tests/integration/components/navi-email-tag-test.js

More octane template fixups for reports
- ignore power select templates until we upgrade

Almost done with reports octane

---

packages/data/addon/adapters/elide-facts.ts
packages/data/addon/adapters/elide-metadata.ts
packages/data/addon/adapters/fact-interface.ts
packages/data/addon/gql/mutations/async-facts-cancel.ts
packages/data/addon/gql/mutations/async-facts.ts
packages/data/addon/gql/queries/async-facts.ts
packages/data/addon/gql/schema.js
packages/data/addon/services/navi-elide-apollo.ts
packages/data/tests/unit/adapters/elide-facts-test.ts

Update elide fact adapter
- Implement fetchDataForRequest
- Align to elide contracts
- Organize elide fact adapter
- Update tests

Update: Update elide fact adapter

---

packages/data/addon/serializers/bard-facts.ts
packages/data/addon/serializers/elide-facts.ts
packages/data/addon/serializers/fact-interface.ts
packages/data/addon/services/navi-facts.ts
packages/data/app/serializers/elide-facts.js
packages/data/tests/unit/serializers/elide-facts-test.ts

Add Elide fact serializer
- Update: Add `request` object to normalize param
- Update: Add initial elide serializer

Elide fact serializer

---

packages/webservice/models/build.gradle.kts

Hopefully #903 
Round 2, updated artifactory plugins and published locally

Fix artifactory publish

---

packages/webservice/models/build.gradle.kts

Hopefully #903
Accidentally had artifacts from leftover builds so I thought it was working. Should be good this time

Update: Should actually fix artifactory deploys

---

packages/admin/package.json
packages/core/package-lock.json
packages/core/package.json
packages/dashboards/package-lock.json
packages/dashboards/package.json
packages/directory/package-lock.json
packages/directory/package.json
packages/notifications/package-lock.json
packages/notifications/package.json
packages/reports/package-lock.json
packages/reports/package.json
packages/search/package-lock.json
packages/search/package.json

Resolves #816 and #817
Version bump for typescript to keep all packages aligned

Update: Newer typescript and ember-cli-typescript

---

.travis.yml

Dashboard build keeps timing out so we'll just disable it for now

Update: Temporarily disable dashboards build

---

packages/data/addon/adapters/facts/elide.ts
packages/data/addon/gql/schema.js
packages/data/addon/mirage/factories/time-dimension-grain.js
packages/data/addon/mirage/factories/time-dimension.js
packages/data/addon/mirage/handlers/graphql.js
packages/data/addon/serializers/facts/elide.ts
packages/data/tests/dummy/mirage/factories/time-dimension-grain.js
packages/data/tests/dummy/mirage/scenarios/elide-one.ts
packages/data/tests/dummy/mirage/scenarios/elide-two.ts
packages/data/tests/unit/serializers/facts/elide-test.ts
packages/data/tests/unit/services/elide-metadata-test.ts
packages/data/tests/unit/services/navi-facts-elide-test.js
packages/data/tests/unit/services/navi-metadata-test.ts

Reopened #942 for merging into request v2

Test graphql mock with args

---

packages/data/addon/adapters/dimensions/interface.ts
packages/data/addon/models/navi-dimension.ts
packages/data/addon/serializers/dimensions/interface.ts
packages/data/app/models/navi-dimension.js
packages/data/tests/unit/models/navi-dimension-test.ts

Add Navi dimension interfaces
- Dimension adapter infterface
- Dimension serializer interface
- Dimension base model

Update: Add Navi dimension interfaces

---

packages/data/addon/adapters/dimensions/interface.ts
packages/data/addon/serializers/dimensions/interface.ts
packages/data/addon/services/navi-dimension.ts
packages/data/app/services/navi-dimension.js
packages/data/tests/unit/services/navi-dimension-test.ts

Resolves #914 
Add navi-dimension service
- Add basic  navi-dimension service
- Update dimension adapter & serializer interfaces

Update: Add navi-dimension service

---

.travis.yml
package-lock.json
package.json
scripts/npm-publish-beta.sh

Resolves #968
Config for publishing to a `beta` dist tag and `-beta` series builds for the request-v2 branch
Should hopefully work, open to suggestions instead of `beta`

Update: Beta publishing for request-v2

---

.travis.yml
packages/app/app/routes/application.js
packages/app/config/environment.js
packages/core/config/environment.js
packages/data/addon/adapters/facts/bard.ts
packages/data/tests/unit/adapters/facts/bard-test.ts
packages/reports/addon/consumers/request/column.js
packages/reports/config/environment.js
packages/search/tests/unit/services/navi-search/navi-definition-search-provider-test.js

Small fixups
- Fixed directory and added back as required for travis
- Fixed search and added back as required for travis
- Fixed some lint errors

Update: Request v2 directory and search

---

packages/core/addon/chart-builders/metric.js
packages/core/addon/mirage/fixtures/dashboard-widget.js
packages/core/addon/mirage/fixtures/dashboard.js
packages/core/addon/mirage/fixtures/reports.js
packages/core/addon/models/dashboard.ts
packages/core/addon/serializers/dashboard.js
packages/core/tests/unit/serializers/dashboard-test.js
packages/dashboards/addon/components/dashboard-dimension-selector.js
packages/dashboards/addon/components/dashboard-filters.js
packages/dashboards/addon/controllers/dashboards/dashboard/view.js
packages/dashboards/addon/routes/dashboards/dashboard/view.js
packages/dashboards/addon/routes/dashboards/dashboard/widgets/new.js
packages/dashboards/addon/services/dashboard-data.js
packages/dashboards/tests/acceptance/dashboard-filter-test.js
packages/dashboards/tests/acceptance/dashboards-test.js
packages/dashboards/tests/acceptance/explore-widget-test.js
packages/dashboards/tests/acceptance/mutli-datasource-dashboards-test.js
packages/dashboards/tests/acceptance/report-action-test.js
packages/dashboards/tests/integration/components/dashboard-dimension-selector-test.js
packages/dashboards/tests/integration/components/dashboard-filters-test.js
packages/dashboards/tests/integration/components/navi-dashboard-test.js
packages/dashboards/tests/unit/controllers/dashboards/dashboard/view-test.js
packages/dashboards/tests/unit/routes/dashboards/dashboard/view-test.js
packages/dashboards/tests/unit/routes/dashboards/dashboard/widgets/new-test.js
packages/dashboards/tests/unit/services/dashboard-data-test.js
packages/data/addon/mirage/fixtures/bard-meta-metrics.js
packages/data/addon/mirage/routes/bard-meta.js
packages/reports/addon/components/filter-builders/base.js
packages/reports/addon/components/filter-collection.js
packages/reports/addon/components/filter-values/dimension-select.js

Resolves #972
Get basic dashboard functionality working. A lot of it is still failing because reports are not working
- Fix some unit/integration tests for dashboards
- Replace some more blockhead/dummy references
- Set up `${tableName}.dateTime` in v2 normalization
- Dashboards now normalize v1 filters to v2 filters (although still serialize back to the v1 format for now)

Request v2 dashboard fixups

---

packages/data/addon/adapters/dimensions/bard.ts
packages/data/addon/adapters/dimensions/interface.ts
packages/data/addon/adapters/facts/interface.ts
packages/data/addon/services/bard-dimensions.ts
packages/data/addon/services/navi-dimension.ts
packages/data/tests/dummy/mirage/config.js
packages/data/tests/unit/adapters/dimensions/bard-test.ts
packages/data/tests/unit/builder/request-test.js

Resolves #1008
Implement NaviDimensionAdapter in Bard Dimension Adapter
- Implement NaviDimensionAdapter in Bard Dimension Adapter
- Give fili dimension mock a faker seed
- Update bard-dimenion service

Update: Use interface in bard dim adapter

---

packages/webservice/app/build.gradle.kts
packages/webservice/app/src/main/kotlin/com/yahoo/navi/ws/App.kt
packages/webservice/app/src/main/kotlin/com/yahoo/navi/ws/filters/AuthFilter.kt
packages/webservice/app/src/main/kotlin/com/yahoo/navi/ws/security/NaviUserDetails.kt
packages/webservice/app/src/main/kotlin/com/yahoo/navi/ws/security/NaviUserDetailsService.kt
packages/webservice/app/src/main/kotlin/com/yahoo/navi/ws/security/UserRepository.kt
packages/webservice/app/src/main/resources/application.yaml
packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/framework/IntegrationTest.kt
packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/AsyncQueryTest.kt
packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/RoleTest.kt
packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/UserTest.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/User.kt

Add Elide Async example and set role for user in security context
Change User Role relationship to ManyToMany

Add: Elide Async example and set role for user in security context

---

packages/reports/addon/consumers/request/filter.ts

Fix: Import in filter consumer

---

package-lock.json
package.json

Alternative to dependabot's failing builds
- Update lerna which updates lodash,node-fetch and handlebars

Update: Lerna

---

packages/data/addon/adapters/facts/bard.ts
packages/data/addon/adapters/facts/elide.ts
packages/data/addon/adapters/facts/interface.ts
packages/data/addon/services/navi-facts.ts
packages/data/tests/unit/adapters/facts/bard-test.ts

Resolves #
Add urlForDownloadQuery function which will be used for async data export implementation

Data export

---

packages/webservice/app/build.gradle.kts
packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/UserTest.kt
packages/webservice/models/build.gradle.kts
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/Dashboard.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/DashboardWidget.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/Report.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/Role.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/User.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/checks/DefaultAuthorCheck.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/checks/DefaultSameUserCheck.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/hooks/UserValidationHook.kt

Build using latest elide version
Update @include annotation for Navi Beans (https://github.com/yahoo/elide/pull/1549/files)

Update: Build using latest elide version and update Include rootLevel property

---

packages/data/addon/adapters/facts/elide.ts
packages/data/tests/unit/adapters/facts/elide-test.ts

Update: Add not between operator to elide

---

packages/data/addon/adapters/facts/elide.ts
packages/data/tests/unit/adapters/facts/elide-test.ts

Navi escaped commas and quotes

---

packages/data/addon/models/navi-fact-response.ts
packages/data/tests/unit/models/navi-fact-response-test.ts

Resolves #1069 
Add getIntervalForTimeDimension method
- Add getIntervalForTimeDimension method

Update: Add getIntervalForTimeDimension method

---

packages/data/addon/models/navi-fact-response.ts
packages/data/tests/unit/models/navi-fact-response-test.ts

Add cache to getTimeDimensionAsMoments
-  Add cache to getTimeDimensionAsMoments

Update: Add cache to getTimeDimensionAsMoments

---

packages/reports/addon/templates/components/navi-table-select-item.hbs
packages/reports/app/styles/navi-reports/components/navi-table-select-item.less
packages/reports/app/styles/navi-reports/components/navi-table-select-trigger.less
packages/reports/app/styles/navi-reports/components/navi-table-select.less

Fix: Table select overflow issue
- Fix: Table select overflow issue
Before:
After:

Fix: Table select overflow issue

---

.travis.yml
packages/app/app/initializers/config.js
packages/app/mirage/bard-meta-stub.js
packages/app/tests/acceptance/custom-reports-test.js
packages/reports/addon/consumers/request/filter.ts

The app package needed some small updates to work with request v2

Update: Fix app package for request-v2

---

packages/core/addon/models/bard-request-v2/request.ts
packages/core/addon/navi-visualization-manifests/bar-chart.ts
packages/core/addon/navi-visualization-manifests/base.ts
packages/core/addon/navi-visualization-manifests/goal-gauge.ts
packages/core/addon/navi-visualization-manifests/line-chart.ts
packages/core/addon/navi-visualization-manifests/metric-label.ts
packages/core/addon/navi-visualization-manifests/pie-chart.ts
packages/core/tests/unit/navi-visualization-manifests/bar-chart-test.ts
packages/core/tests/unit/navi-visualization-manifests/goal-gauge-test.ts
packages/core/tests/unit/navi-visualization-manifests/line-chart-test.ts
packages/core/tests/unit/navi-visualization-manifests/metric-label-test.ts
packages/core/tests/unit/navi-visualization-manifests/pie-chart-test.ts

Resolves #1085 
With `gte`, `lte`, etc date filter operators we longer are guaranteed an explicit requested interval
- update visualization manifests to use more lenient checks

Update: Visualization manifests to be more lenient

---

packages/core/tests/integration/components/navi-visualizations/bar-chart-test.ts

Fix: Typscript error in test

---

build-scripts/setup-chrome.sh
screwdriver.yaml
scripts/gh-pages-publish.sh

Screwdriver

---

README.md

Add SD build badge
- Add SD build badge

Docs: Add SD build badge

---

package.json
packages/webservice/app/build.gradle.kts
packages/webservice/models/build.gradle.kts
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/hooks/UserValidationHook.kt

Resolves #
carried from old PR which was closed due to branch getting too much outdated.
the bootrun was running into dependency issues. Overall process was not smooth.
- control node version and have gradle download it irrespective of what is on local system
- related changes

improve bootrun

---

package.json
packages/admin/tests/dummy/config/environment.js
packages/app/app/components/top-bar.js
packages/app/app/initializers/config.js
packages/app/config/environment.js
packages/app/config/environments.json
packages/app/mirage/config.js
packages/app/server-lib/use-config-middleware.js
packages/app/tests/test-helper.js
packages/app/tests/unit/initializers/config-test.js
packages/core/config/environment.js
packages/data/addon/adapters/metadata/elide.ts
packages/data/addon/mirage/routes/graphql.js
packages/data/addon/services/navi-elide-apollo.ts
packages/data/tests/dummy/config/environment.js
packages/data/tests/unit/adapters/facts/elide-test.ts
packages/data/tests/unit/adapters/metadata/elide-test.ts
packages/data/tests/unit/services/navi-elide-apollo-test.js
packages/directory/tests/dummy/config/environment.js
packages/reports/config/environment.js
packages/webservice/app/build.gradle.kts
packages/webservice/app/src/main/kotlin/com/yahoo/navi/ws/config/DataSource.kt
packages/webservice/app/src/main/kotlin/com/yahoo/navi/ws/config/NaviConfig.kt
packages/webservice/app/src/main/kotlin/com/yahoo/navi/ws/config/WebConfig.kt
packages/webservice/app/src/main/kotlin/com/yahoo/navi/ws/controllers/ServerGeneratedConfig.kt
packages/webservice/app/src/main/kotlin/com/yahoo/navi/ws/filters/AuthFilter.kt
packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/ServerGeneratedConfigTest.kt
packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/StaticAssetServingTest.kt
screwdriver.yaml

Connect Web Service with UI
- Change UI `rootURL` to `ui/`
- Fix topbar `rootURL` property
- Refactor sever generated config shape
- Refactor web service asset seving logic
- Fix datasourceName configuration in elide metadata query 
- Remove invalid addon config settings
- Run webservice tests in screwdriver

Connect Web Service with UI

---

packages/data/addon/gql/queries/tables.ts
packages/data/addon/gql/schema.js
packages/data/addon/mirage/factories/table.js
packages/data/addon/mirage/routes/graphql.js
packages/data/package-lock.json
packages/data/package.json
packages/webservice/app/src/main/resources/demo-configs/models/tables/DemoTables.hjson

Only request fact tables from elide
- Only request fact tables from elide

Update: Only request fact tables from elide

---

packages/core/addon/chart-builders/dimension.ts
packages/core/addon/chart-builders/metric.ts
packages/core/addon/components/navi-visualizations/pie-chart.hbs
packages/core/addon/components/navi-visualizations/pie-chart.ts
packages/core/tests/integration/components/navi-visualizations/pie-chart-test.ts
packages/core/tests/unit/chart-builders/dimension-test.ts
packages/core/tests/unit/chart-builders/metric-test.ts

Support non time dim visualizations
- Support non time dim visualizations
- Fix render pie chart label on alias update
- Fix Pie undefined seriesConfig (teardown) case

Support non time dim visualizations

---

packages/data/addon/adapters/facts/elide.ts
packages/data/tests/unit/adapters/facts/elide-test.ts

Resolves #
Tested with real elide instance and found a few escape issues.
- Fix Elide filter escaping

Fix: Elide filter escaping

---

screwdriver.yaml

Fix workflow so publish triggers on EITHER main OR alpha-main
- change workflow requirements to be OR

Fix: Build workflow

---

screwdriver.yaml
scripts/artifactory-publish.sh
scripts/npm-publish.sh

Branch detection doesn't work because SD has old git version. 
- Update command to get current branch in publish scripts

Fix: Branch detection for old git experiment.

---

packages/core/addon/mirage/fixtures/reports.js
packages/core/tests/integration/components/chart-series-config-test.ts
packages/core/tests/unit/models/report-test.js
packages/reports/tests/acceptance/column-config-test.js
packages/reports/tests/acceptance/date-filter-test.js
packages/reports/tests/acceptance/error-route-test.js
packages/reports/tests/acceptance/invalid-route-test.js
packages/reports/tests/acceptance/print-report-test.js
packages/reports/tests/acceptance/report-test.js
packages/reports/tests/acceptance/report-visualizations-test.js
packages/reports/tests/unit/serializers/report-test.js

Initial changes a few more modules tests fully passing.
Navi-Report testing module is closer to passing
-

Initial Test Fixes

---

packages/webservice/app/build.gradle.kts
packages/webservice/app/src/main/resources/application-test.yaml
packages/webservice/app/src/main/resources/application.yaml
packages/webservice/models/build.gradle.kts

Disabling the Async Cleanup in test cases.
A separate profile for `test` sets the flag to false.

Disable Async Cleanup in Tests

---

packages/webservice/app/build.gradle.kts
packages/webservice/app/src/main/kotlin/com/yahoo/navi/ws/config/ElideConfig.kt
packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/CorsFilterTest.kt
packages/webservice/models/build.gradle.kts
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/checks/DefaultAuthorCheck.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/checks/DefaultDashboardAuthorCheck.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/checks/DefaultEditorsCheck.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/checks/DefaultEverybodyCheck.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/checks/DefaultNobodyCheck.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/checks/DefaultSameUserCheck.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/hooks/UserValidationHook.kt

Upgrade to latest elide and fix imports.

Use latest elide version

---

packages/webservice/app/src/main/resources/demo-configs/models/tables/DemoTables.hjson

Updating the Netflix demo model to have a category per Dim/Metrics.

---

packages/core/addon/components/navi-visualizations/goal-gauge.ts
packages/core/addon/validators/request-metric-exist.ts

Fix: Adding & Editing gauge widget
- Fix: Adding & Editing gauge widget

Fix: Adding & Editing gauge widget

---

packages/webservice/app/build.gradle.kts
packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/DemoDataSourceTest.kt

demodata source test

---

packages/reports/addon/components/power-select-bulk-import-trigger.js
packages/reports/addon/templates/components/power-select-bulk-import-trigger.hbs
packages/reports/tests/integration/components/power-select-bulk-import-trigger-test.js

Resolves #
Remove code and skip tests involving bulk imports for filters on paste

remove bulk import

---

packages/dashboards/addon/components/dashboard-dimension-selector.js
packages/dashboards/addon/components/dashboard-filters.js
packages/dashboards/addon/controllers/dashboards/dashboard/view.js
packages/dashboards/addon/templates/dashboards/dashboard/widgets/widget.hbs
packages/dashboards/tests/dummy/config/environment.js
packages/reports/addon/components/filter-values/null-input.hbs
packages/reports/addon/components/filter-values/null-input.ts

Dashboard filters were not showing up/updating correctly
- update computed key
- fix demo app config so that it runs correctly

Update: Fix Dashboard filters and demo app

---

packages/app/config/environment.js
packages/dashboards/addon/templates/dashboards/dashboard/widgets/widget.hbs
packages/dashboards/tests/acceptance/explore-widget-test.js
packages/dashboards/tests/dummy/config/environment.js
packages/reports/addon/components/common-actions/schedule.js
packages/reports/addon/components/report-actions/multiple-format-export.js
packages/reports/addon/templates/components/navi-action-list.hbs
packages/reports/addon/templates/components/report-actions.hbs
packages/reports/config/environment.js
packages/reports/tests/acceptance/report-test.js
packages/reports/tests/dummy/config/environment.js
packages/reports/tests/integration/components/common-actions/schedule-test.js

Resolves #
Put feature flag behind a feature flag
-

Update: Feature flag export

---

packages/webservice/app/build.gradle.kts
packages/webservice/app/src/main/resources/demo-configs/models/tables/DemoTables.hjson
packages/webservice/models/build.gradle.kts

Update Elide to 5.0.0-pr29

---

packages/core/addon/templates/chart-tooltips/date.hbs
packages/core/addon/templates/chart-tooltips/dimension.hbs
packages/core/addon/templates/chart-tooltips/metric.hbs
packages/core/addon/templates/chart-tooltips/pie-chart.hbs
packages/core/app/styles/navi-core/visualizations/index.less
packages/core/app/styles/navi-core/visualizations/line-chart.less
packages/core/app/styles/navi-core/visualizations/pie-chart.less
packages/core/app/styles/navi-core/visualizations/tooltips.less
packages/core/tests/acceptance/line-chart-test.ts
packages/core/tests/dummy/app/templates/application.hbs

Chart tooltips
- Update: Add series names to chart tooltips
- Update: Add pie-chart nav button to dummy app

Chart tooltips

---

packages/reports/addon/templates/components/navi-list-selector.hbs
packages/reports/app/styles/navi-reports/components/grouped-list.less
packages/reports/app/styles/navi-reports/components/navi-list-selector.less
packages/reports/app/styles/navi-reports/components/report-builder.less
packages/reports/tests/integration/components/navi-list-selector-test.js

[Resolves](url) #
Change Yavin reports search (dimensions and metrics) to denali search
-
Before
After

denali search

---

packages/webservice/app/build.gradle.kts
packages/webservice/models/build.gradle.kts
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/checks/DefaultAuthorCheck.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/checks/DefaultSameUserCheck.kt

Upgrade to Elide 5.0.0-pr30

---

packages/app/app/components/top-bar.hbs
packages/core/addon/components/lazy-render.js
packages/directory/addon/components/dir-icon.hbs
packages/directory/addon/components/dir-new-button.hbs
packages/directory/addon/components/dir-sidebar-toggle.hbs
packages/directory/addon/components/dir-sidebar-toggle.ts
packages/directory/addon/components/dir-sidebar.hbs
packages/directory/addon/components/dir-table.ts
packages/directory/addon/controllers/directory.ts
packages/directory/addon/routes/directory.ts
packages/directory/addon/templates/directory.hbs
packages/directory/app/components/dir-sidebar-toggle.js
packages/directory/tests/acceptance/dir-sidebar-toggle-test.ts
packages/directory/tests/dummy/app/templates/application.hbs
packages/directory/tests/integration/components/dir-sidebar-toggle-test.ts

Use a hamburger menu on mobile screens to expose the directory sidebar
https://user-images.githubusercontent.com/12093492/106190703-a1474a00-616f-11eb-85eb-7be1a2b0c099.mov

Update: Better mobile view for directory

---

packages/app/config/environment.js
packages/directory/addon/components/dir-sidebar-toggle.ts
packages/directory/addon/components/dir-table-filter.hbs
packages/directory/addon/templates/directory.hbs
packages/directory/app/styles/navi-directory/components/dir-search-bar.scss
packages/directory/app/styles/navi-directory/components/dir-sidebar-toggle.scss
packages/directory/app/styles/navi-directory/components/index.scss

Better mobile styling for directory
- Temporary fix for Denali Inputs on safari
- Smaller width design

Update: Mobile styling for directory

---

packages/app/app/styles/views/reports.scss
packages/core/addon/services/screen.ts
packages/core/app/services/screen.js
packages/core/tests/unit/services/screen-test.ts
packages/dashboards/addon/templates/components/navi-dashboard.hbs
packages/dashboards/addon/templates/dashboards/dashboard/widgets/widget.hbs
packages/dashboards/app/styles/navi-dashboards.scss
packages/dashboards/app/styles/navi-dashboards/index.less
packages/dashboards/app/styles/navi-dashboards/index.scss
packages/dashboards/app/styles/navi-dashboards/navi-report-widget.scss
packages/dashboards/tests/acceptance/explore-widget-test.js
packages/data/addon/mirage/routes/bard-lite.ts
packages/reports/addon/components/filter-builders/base.hbs
packages/reports/addon/controllers/reports/report.js
packages/reports/addon/routes/reports/report.js
packages/reports/addon/templates/components/report-builder.hbs
packages/reports/addon/templates/reports/report.hbs
packages/reports/app/styles/navi-reports/common/index.less
packages/reports/app/styles/navi-reports/common/index.scss
packages/reports/app/styles/navi-reports/common/report.scss
packages/reports/app/styles/navi-reports/components/report-view.less
packages/reports/tests/acceptance/mobile-test.ts

Better behavior for mobile UI
- Better styling for mobile
- collapse column config and filters on mobile by default
- fix issue with bard lite generating the same values for different dimensions

Mobile report view

---

packages/dashboards/app/styles/navi-dashboards/components/navi-dashboard.less

Quick fix for dashboard header alignment

Fix: Dashboard header alignment

---

packages/dashboards/addon/components/dashboard-actions/export.js
packages/dashboards/addon/routes/dashboard-collections/collection.js
screwdriver.yaml

Found typo in gsheet export link
- upon searching for 'dashbord' found another typo

Fix: Typo in export link

---

screwdriver.yaml

needs the flag in master as well

Fix: Alpha build

---

README.md

Docs: Update community link to GH discussions

---

packages/reports/addon/templates/components/report-view.hbs
packages/reports/app/styles/navi-reports/components/report-view.less
packages/reports/tests/acceptance/report-test.js

Resolves #
Update Visualization config header
- Update Visualization config header

Update: Visualization config header

---

packages/directory/app/styles/navi-directory/components/dir-asset-row-actions.scss
packages/notifications/app/styles/navi-notifications.scss
packages/reports/addon/components/navi-tag-input/tag.hbs
packages/reports/app/styles/navi-reports/vendor/ember-tag-input.scss
packages/reports/tests/acceptance/schedule-modal-test.js
packages/reports/tests/integration/components/filter-values/multi-value-input-test.ts
packages/reports/tests/integration/components/navi-email-input-test.js
packages/reports/tests/integration/components/navi-tag-input-test.js

Style fixes
- Notification z-index
- Modal visibility in directory view
- Close icon cursor on navi-tag-input tags

Fix: Style fixes

---

packages/reports/addon/components/navi-column-config/base.hbs
packages/reports/addon/templates/components/report-view.hbs
packages/reports/app/styles/navi-reports/components/report-view.less

Resolves #
Small style updates
- Update: Replace custom styles with denali
- Update: Column param select to medium size

Update: Replace custom styles with denali

---

packages/webservice/app/src/main/resources/application.yaml

Adds a permanent database file to persist changes across service restarts.

Update: Added relative database file for saves across service restarts

---

README.md
packages/app/config/environment.js

Docs: Update README.md

---

packages/webservice/app/.gitignore
packages/webservice/app/build.gradle.kts
packages/webservice/models/build.gradle.kts

build: update Elide to 5.0.0-pr32

---

packages/core/addon/models/bard-request-v2/fragments/base.ts
packages/dashboards/tests/acceptance/explore-widget-test.js
packages/dashboards/tests/acceptance/mutli-datasource-dashboards-test.js
packages/dashboards/tests/integration/components/dashboard-filters-test.js
packages/reports/addon/components/filter-builders/base.hbs
packages/reports/addon/components/filter-builders/base.ts
packages/reports/app/styles/navi-reports/components/filter-builder.scss
packages/reports/tests/acceptance/column-config-test.ts
packages/reports/tests/acceptance/fili-datasource-test.ts
packages/reports/tests/acceptance/multi-datasource-test.js
packages/reports/tests/acceptance/report-test.js
packages/reports/tests/integration/components/filter-builders/dimension-test.ts

Update: Use chips for parameters in filter builder display

---

packages/core/addon/models/bard-request-v2/fragments/base.ts
packages/data/addon/models/metadata/column-function.ts
packages/data/addon/models/metadata/column.ts
packages/data/addon/models/metadata/dimension.ts
packages/data/addon/models/metadata/metric.ts
packages/data/addon/models/metadata/registry.ts
packages/data/addon/models/metadata/request-constraint.ts
packages/data/addon/models/metadata/table.ts
packages/data/addon/models/metadata/time-dimension.ts
packages/data/addon/models/navi-dimension.ts
packages/data/addon/models/navi-fact-response.ts
packages/data/addon/models/navi-facts.ts
packages/data/addon/services/navi-metadata.ts
packages/reports/addon/components/visualization-toggle.ts
packages/reports/tests/unit/services/request-constrainer-test.ts

Resolves #
Refactor metadata registry and imports
- Refactor metadata registry and imports

Update: Refactor metadata registry and imports

---

packages/data/addon/adapters/facts/elide.ts
packages/data/addon/adapters/facts/interface.ts
packages/data/addon/gql/mutations/export-facts.ts
packages/data/tests/unit/adapters/facts/elide-test.ts

Resolves #
Navi data changes for table export
-

Export - navi data changes

---

packages/webservice/app/build.gradle.kts
screwdriver.yaml

Update SD to build using lts node 14

Update: Build using latest lts

---

packages/reports/addon/templates/components/report-actions.hbs
packages/reports/tests/integration/components/common-actions/delete-test.js

Resolves #
- Update: Small code clean up

Update: Small code clean up

---

packages/directory/app/styles/navi-directory/components/dir-search-bar.scss

Remove style fixup for search bar
This is how it looks with the latest denali and the fixup

Update: Remove unneeded search icon fixup

---

packages/reports/addon/components/dropdown-parameter-picker.hbs
packages/reports/addon/components/dropdown-parameter-picker.ts
packages/reports/addon/components/dropdown-parameter-trigger.hbs
packages/reports/addon/components/filter-builders/base.hbs
packages/reports/addon/components/filter-builders/base.ts
packages/reports/app/components/dropdown-parameter-picker.js
packages/reports/app/components/dropdown-parameter-trigger.js
packages/reports/app/styles/navi-reports/components/dropdown-parameter-picker.scss
packages/reports/app/styles/navi-reports/components/filter-builder.scss
packages/reports/app/styles/navi-reports/components/index.scss
packages/reports/tests/acceptance/dropdown-parameter-picker-test.ts
packages/reports/tests/acceptance/multi-datasource-test.js
packages/reports/tests/integration/components/dropdown-parameter-picker-test.ts
packages/reports/tests/integration/components/filter-builders/dimension-test.ts

Add dropdown functionality to click on parameter chips and be able to change filter parameters in the filter builder.

Parameter chip

---

packages/webservice/app/build.gradle.kts
packages/webservice/app/src/main/resources/demo-configs/models/tables/DemoTables.hjson
packages/webservice/models/build.gradle.kts

Update to latest version of Elide.

build: Update Elide to PR34

---

packages/data/addon/adapters/metadata/interface.ts
packages/data/addon/services/navi-metadata.ts
packages/data/tests/unit/services/navi-metadata-test.ts

Resolves #
Cache metadata promises per datasource
- Cache metadata promises per datasource

Update: Cache metadata promises per datasource

---

packages/dashboards/tests/dummy/config/environment.js
packages/data/addon/adapters/dimensions/bard.ts
packages/data/addon/utils/adapter.ts
packages/data/config/navi-config.d.ts
packages/data/tests/dummy/config/environment.js
packages/data/tests/unit/adapters/dimensions/bard-test.ts
packages/data/tests/unit/services/bard-dimensions-test.js
packages/data/tests/unit/services/navi-dimension-test.ts
packages/reports/tests/dummy/config/environment.js
packages/reports/tests/integration/components/report-builder-test.ts

Resolves #
- Update: Make fili search feature configurable
**TODO** add `options` to server-generated-config model

Update: Make fili search feature configurable

---

packages/reports/addon/components/dropdown-parameter-picker.hbs
packages/reports/addon/components/filter-builders/base.hbs
packages/reports/addon/components/filter-values/time-dimension/lookback-trigger.hbs
packages/reports/addon/components/filter-values/time-dimension/lookback-trigger.ts
packages/reports/addon/components/report-builder/source-selector.hbs
packages/reports/addon/consumers/request/fili.ts
packages/reports/tests/acceptance/fili-datasource-test.ts
packages/reports/tests/integration/components/filter-values/time-dimension/lookback-test.ts
packages/reports/tests/unit/consumers/request/fili-test.ts

Resolves #1350 
- changing dimension field on filter clears values
- lookback input gets reset on focusout if it was cleared
- tooltip displays on body

Update: Small bug fixes

---

packages/core/addon/templates/components/table-renderer-vertical-collection.hbs
packages/core/addon/templates/components/table-renderer.hbs
packages/core/app/styles/navi-core/components/navi-visualizations/table.scss

Resolves #
- Fix: Metric cell text alignment

Fix: Metric cell text alignment

---

packages/app/tests/acceptance/custom-reports-test.js
packages/core/addon/models/bard-request-v2/request.ts
packages/core/tests/unit/services/compression-test.ts
packages/dashboards/tests/acceptance/dashboards-test.js
packages/dashboards/tests/acceptance/explore-widget-test.js
packages/dashboards/tests/acceptance/mutli-datasource-dashboards-test.js
packages/dashboards/tests/unit/routes/dashboards/dashboard/widgets/new-test.js
packages/reports/tests/acceptance/column-config-test.ts
packages/reports/tests/acceptance/dropdown-parameter-picker-test.ts
packages/reports/tests/acceptance/fili-datasource-test.ts
packages/reports/tests/acceptance/multi-datasource-test.js
packages/reports/tests/acceptance/report-test.js
packages/reports/tests/unit/routes/reports/new-test.ts

Resolves #
Update: Remove default datasource
-

Update: Remove default datasource

---

packages/data/addon/adapters/facts/elide.ts
packages/data/tests/unit/adapters/facts/elide-test.ts

Resolves #
Pass through headers in options of elide fact calls.
- Pass through headers in options of elide fact calls.

Fix: Pass through headers in elide-fact calls

---

packages/dashboards/addon/components/dashboard-filters.hbs
packages/dashboards/app/styles/navi-dashboards/components/dashboard-filters.scss
packages/dashboards/tests/acceptance/dashboard-filter-test.js
packages/dashboards/tests/acceptance/dashboards-test.js
packages/dashboards/tests/acceptance/mutli-datasource-dashboards-test.js
packages/dashboards/tests/integration/components/dashboard-filters-test.js
packages/reports/addon/components/filter-collection.hbs
packages/reports/addon/components/report-builder.hbs
packages/reports/app/styles/navi-reports/components/report-builder.scss

Resolves #
- New dashboard filter UX
https://user-images.githubusercontent.com/2983409/122832904-b012d280-d2b1-11eb-9add-c2b59d929c57.mov

Update: Refactor dashboard filters UX

---

packages/webservice/app/src/main/kotlin/com/yahoo/navi/ws/checks/AdminCheck.kt
packages/webservice/app/src/main/resources/db/changelog/changelog.xml
packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/DeliveryRulesTest.kt
packages/webservice/build.gradle.kts
packages/webservice/models/build.gradle.kts
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/Dashboard.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/DeliveryRule.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/Report.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/enums/DeliveryFrequency.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/enums/DeliveryType.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/DeliveryFormat.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/SchedulingRules.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/checks/DefaultAdminCheck.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/validations/EmailList.kt

Resolves #
Needs #1430 
- Add delivery rules

Delivery rule models

---

packages/data/addon/serializers/facts/interface.ts

Update: Add Missing Interval

---

packages/core/addon/models/bard-request/fragments/rollup.js
packages/core/addon/models/bard-request/request.js
packages/core/addon/serializers/bard-request/request.js
packages/core/addon/transforms/dimension.js
packages/core/app/models/bard-request/fragments/rollup.js
packages/core/config/environment.js
packages/core/tests/dummy/config/environment.js
packages/core/tests/unit/models/bard-request/request-test.js
packages/core/tests/unit/models/dashboard-widget-test.js
packages/core/tests/unit/models/report-test.js
packages/core/tests/unit/serializers/bard-request/request-test.js
packages/dashboards/tests/unit/routes/dashboards/dashboard/widgets/new-test.js
packages/data/addon/mirage/routes/bard-lite.js
packages/data/tests/dummy/app/router.js
packages/data/tests/dummy/app/routes/mirage.js
packages/data/tests/dummy/mirage/config.js
packages/reports/addon/consumers/request/dimension.js
packages/reports/addon/consumers/request/rollup.js
packages/reports/addon/services/request-action-dispatcher.js
packages/reports/app/consumers/request/rollup.js
packages/reports/tests/unit/consumers/request/rollup-test.js
packages/reports/tests/unit/routes/reports/new-test.js
packages/reports/tests/unit/serializers/report-test.js

Adds rollup fragment for fili subtotal feature
- Add rollup fragment and add it to request model with supporting methods
- Add feature flag and remove rollup from serialize rollup if it's off
- Adjust dimension transform so dateTime works correctly
- Add the rollup consumers

New: Rollup model, serializers and consumers

---

packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/DashboardWidgetTest.kt
packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/DeliveryRulesTest.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/DashboardWidget.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/DeliveryRule.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/RequestList.kt

Resolves #
- Add delivery-rule `dataSources` field

Delivery rule datasource

---

packages/app/app/styles/views/dashboards.scss
packages/dashboards/addon/components/dashboard-filters.ts
packages/dashboards/addon/components/dashboard-header.hbs
packages/dashboards/addon/components/navi-dashboard.hbs
packages/dashboards/addon/components/navi-dashboard.ts
packages/dashboards/app/styles/navi-dashboards/components/dashboard-header.scss
packages/dashboards/app/styles/navi-dashboards/components/navi-dashboard.scss

Resolves #
- Fix: Scroll issue with widget grid
- Update: Add scroll shadow to dashboard header
https://user-images.githubusercontent.com/2983409/128796913-f0ed079c-e50a-4b9b-ac12-4687a410d96a.mov

Dashboard style updates

---

packages/core/addon/serializers/table.ts
packages/data/addon/utils/metric.ts

Normalize parameter type

---

packages/webservice/app/build.gradle.kts
packages/webservice/app/src/main/kotlin/com/yahoo/navi/ws/security/NaviUserDetailsService.kt
packages/webservice/app/src/main/resources/application.yaml
packages/webservice/app/src/main/resources/logback-access-spring.xml
packages/webservice/app/src/main/resources/logback-spring.xml
packages/webservice/models/build.gradle.kts

- Upgrade to Elide 5.0.8
- UserService MDC logs the user ID
- Remove response logging in access log
- Added dependency that turns on access logs for spring boot

Update: Enable logging best practices.

---

packages/dashboards/addon/templates/dashboards/dashboard/widgets/widget.hbs

Fix issue where forgot widgets have their own column config
- Add rollup actions to widget column config

Fix: Widget column config missing actions

---

package-lock.json
packages/core/addon/serializers/table.ts
packages/core/addon/utils/request.ts
packages/core/tests/unit/serializers/table-test.ts
packages/core/tests/unit/utils/request-test.ts

- add support for all grain and relax table serializer (allow for missing request or table columns)

Fix: Normalize v1 to v2 for all grain

---

packages/reports/addon/templates/components/report-actions.hbs

Fix: Schedule report icon

---

packages/webservice/app/src/main/kotlin/com/yahoo/navi/ws/checks/JobRunnerCheck.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/DeliveryRule.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/checks/DefaultJobRunnerCheck.kt

Resolves #
- Update: Add job runner user check
- Update: Let job runner update lastDeliveredOn

Last delivered on

---

packages/data/addon/adapters/facts/bard.ts
packages/data/tests/unit/adapters/facts/bard-test.ts
packages/reports/addon/consumers/request/column.ts

Port of subtotal adapter from alpha branch
- Since reqv2 uses CIDs rather than dimensions, we have to normalize to dimension names in the adapter.

New: Subtotal bard adapter.

---

packages/data/addon/mirage/routes/bard-lite.ts

Resolves #
- Allow custom `dateTime` formatting in bard-lite

Update: Allow `dateTime` formatting in bard-lite

---

packages/core/addon/services/interfaces/navi-notifications.ts

Update: Add htmlSafe() type SafeString to messageOptions title

---

packages/app/config/environments.json
packages/app/tests/test-helper.js
packages/dashboards/tests/dummy/config/environment.js
packages/data/config/navi-config.d.ts
packages/directory/tests/dummy/config/environment.js
packages/reports/addon/components/report-builder/sidebar.hbs
packages/reports/addon/components/report-builder/sidebar.ts
packages/reports/addon/components/report-builder/source-selector-list.hbs
packages/reports/addon/components/report-builder/source-selector-list.ts
packages/reports/addon/components/report-builder/source-selector.hbs
packages/reports/addon/components/report-builder/source-selector.ts
packages/reports/app/components/report-builder/source-selector-list.js
packages/reports/app/styles/navi-reports/components/report-builder/sidebar.scss
packages/reports/app/styles/navi-reports/components/report-builder/source-selector.scss
packages/reports/tests/dummy/config/environment.js
packages/reports/tests/integration/components/report-builder/sidebar-test.ts
packages/reports/tests/integration/components/report-builder/source-selector-list-test.ts
packages/reports/tests/integration/components/report-builder/source-selector-test.ts
packages/webservice/app/src/main/kotlin/com/yahoo/navi/ws/config/DataSource.kt
packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/ServerGeneratedConfigTest.kt

Add suggested sources to source selector (and some styling changes)
New datasource property: `suggestedDataTables: string[]`

New: Suggested tables

---

packages/admin/package-lock.json
packages/admin/package.json
packages/app/package-lock.json
packages/app/package.json
packages/core/addon/services/gsheet-export.ts
packages/core/addon/services/interfaces/navi-notifications.ts
packages/core/app/mirage/routes/gsheet.js
packages/core/app/services/gsheet-export.js
packages/core/package-lock.json
packages/core/package.json
packages/core/tests/dummy/mirage/config.js
packages/core/tests/unit/services/gsheet-export-test.ts
packages/dashboards/package-lock.json
packages/dashboards/package.json
packages/dashboards/tests/dummy/mirage/config.js
packages/dashboards/tests/integration/components/dashboard-actions/export-test.js
packages/directory/package-lock.json
packages/directory/package.json
packages/notifications/package-lock.json
packages/notifications/package.json
packages/reports/addon/components/report-actions/multiple-format-export.ts
packages/reports/package-lock.json
packages/reports/package.json
packages/reports/tests/dummy/mirage/config.js
packages/reports/tests/integration/components/report-actions/multiple-format-export-test.js
packages/search/package-lock.json
packages/search/package.json

New: Gsheet exporting service

---

packages/reports/addon/components/report-builder/source-selector.hbs

Fix: Suggested tables icon padding

---

packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/hooks/UserValidationHook.kt

Remove requirement to extend DefaultAdminCheck

Update: Expect UserCheck not DefaultAdminCheck

---

packages/core/addon/utils/enums/number-formats.ts

- Due to changes in fili formatting, we should offer this as a choosable format option, Since this format will be used a lot more.
- Add Percentage formatter to list.

New: Add decimal formatter to number formatters.

---

packages/reports/app/styles/navi-reports/components/dropdown-parameter-picker.scss
packages/reports/app/styles/navi-reports/components/filter-builder.scss

Update: Max filter dropdown height

---

packages/app/app/templates/application-loading.hbs
packages/webservice/app/src/main/kotlin/com/yahoo/navi/ws/config/WebConfig.kt
packages/webservice/app/src/main/kotlin/com/yahoo/navi/ws/controllers/ServerGeneratedConfig.kt
packages/webservice/app/src/main/kotlin/com/yahoo/navi/ws/interceptor/CacheInterceptor.kt
packages/webservice/app/src/main/resources/application.yaml
packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/StaticAssetServingTest.kt

Adds compression/caching to static assets 

Update: Configure static assets

---

packages/data/addon/mirage/fixtures/bard-meta-tables.ts
packages/data/addon/mirage/routes/bard-meta.js
packages/data/tests/unit/adapters/metadata/bard-test.ts
packages/reports/addon/components/column-selector.hbs
packages/reports/addon/components/column-selector.ts
packages/reports/addon/components/grouped-list.hbs
packages/reports/addon/components/grouped-list.ts
packages/reports/tests/acceptance/multi-datasource-test.js
packages/reports/tests/integration/components/column-selector-test.ts
packages/reports/tests/integration/components/grouped-list-test.js
packages/reports/tests/integration/components/report-builder/sidebar-test.ts
packages/search/tests/unit/services/navi-search/navi-definition-search-provider-test.js

don't show categories for columns with only one category

---

packages/reports/addon/components/common-actions/share.ts

Update: Change url getter to an action

---

packages/data/addon/services/navi-formatter.ts

Workaround for numbro bug
- We realized we don't need to specify a large mantissa and just setting thousand separated works

Fix: Issue with large mantissa work around

---

packages/reports/addon/components/report-actions/multiple-format-export.ts
packages/reports/tests/dummy/mirage/config.js

Added model attribute

---

packages/reports/addon/components/report-actions/multiple-format-export.ts
packages/reports/tests/dummy/mirage/config.js

Reverts yavin-dev/framework#1528
Broke export

Revert "Added model attribute"

---

packages/dashboards/addon/components/dashboard-actions/export.ts
packages/reports/addon/components/report-actions/multiple-format-export.ts
packages/reports/tests/dummy/mirage/config.js
packages/reports/tests/integration/components/report-actions/multiple-format-export-test.js

Gsheet model query param bug fix

---

packages/core/addon/components/navi-cell-renderers/dimension.ts
packages/core/addon/components/navi-cell-renderers/url.hbs
packages/core/addon/components/navi-cell-renderers/url.ts
packages/core/addon/components/navi-table-cell-renderer.ts
packages/core/app/components/navi-cell-renderers/url.js
packages/core/tests/integration/components/navi-cell-renderers/url-test.ts
packages/core/tests/integration/components/navi-table-cell-renderer-test.ts
packages/data/addon/mirage/fixtures/bard-meta-dimensions.ts
packages/data/addon/mirage/routes/bard-lite.ts
packages/data/addon/serializers/metadata/bard.ts
packages/data/tests/unit/adapters/metadata/bard-test.ts
packages/reports/tests/acceptance/report-test.js
packages/reports/tests/integration/components/column-selector-test.ts

Render an anchor element for columns with `valueType='url'`

URL table cell renderer

---

packages/reports/addon/routes/reports/report.ts

Update: Replace visualization merge

Update: Replace visualization merge

---

packages/core/addon/models/request/filter.ts
packages/data/addon/utils/classes/interval.ts
packages/data/tests/unit/utils/classes/interval-test.ts
packages/reports/addon/components/filter-builders/time-dimension.ts
packages/reports/addon/components/filter-values/time-dimension/advanced.hbs
packages/reports/addon/components/filter-values/time-dimension/advanced.ts
packages/reports/addon/components/filter-values/time-dimension/base-interval.ts
packages/reports/addon/templates/components/report-view.hbs
packages/reports/app/components/filter-values/time-dimension/advanced.js
packages/reports/tests/acceptance/report-test.js
packages/reports/tests/integration/components/filter-values/time-dimension/advanced-test.ts
packages/reports/tests/unit/components/filter-builders/time-dimension-test.ts

Adds back the advanced date picker option
- validates that between timeDimension filters contain valid intervals
https://user-images.githubusercontent.com/12093492/149562964-57f731bc-8644-4239-9164-566942bdd858.mov

Update: Add advanced date filter option

---

package-lock.json
packages/app/config/environment.js
packages/core/addon/mirage/fixtures/delivery-rules.ts
packages/core/addon/models/delivery-rule.ts
packages/core/tests/unit/models/delivery-rule-test.js
packages/reports/addon/components/common-actions/schedule.hbs
packages/reports/addon/components/common-actions/schedule.ts
packages/reports/tests/integration/components/common-actions/schedule-test.js
packages/webservice/app/src/main/resources/db/changelog/changelog.xml
packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/DeliveryRulesTest.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/DeliveryRule.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/enums/Delivery.kt

Update: Schedule no delivery

---

packages/reports/addon/components/common-actions/schedule.hbs
packages/reports/addon/components/common-actions/schedule.ts
packages/reports/app/styles/navi-reports/components/common-actions/schedule-modal.scss
packages/reports/tests/acceptance/schedule-modal-test.js
packages/reports/tests/integration/components/common-actions/schedule-test.js

Adds overwrite toggle to some formats (just gsheet for now)
- Add overwrite toggle.

New: Overwrite File in schedule modal

---

packages/core/addon/mirage/fixtures/delivery-rules.ts
packages/core/addon/models/delivery-rule.ts
packages/core/tests/unit/models/delivery-rule-test.js
packages/reports/tests/integration/components/common-actions/schedule-test.js
packages/webservice/app/src/main/resources/db/changelog/changelog.xml
packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/DeliveryRulesTest.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/DeliveryRule.kt

Update: Add is Disabled attribute to delivery rules

---

packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/DeliveryRule.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/hooks/DeliveryRuleConditionalRecipientsHook.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/hooks/VerifyDeliveryRuleRecipientsHook.kt

Update: Fix the delivery rule recipients verification

---

screwdriver.yaml

Build: Add pr builds for vis-v2 branch

---

packages/core/addon/models/visualization-v2.ts
packages/core/addon/models/visualization.ts
packages/core/addon/serializers/report.ts
packages/core/addon/serializers/visualization.ts
packages/core/addon/services/visualization.ts

Adds compatibility layer for legacy manifests in new visualization service

Update: Add compat adapter for legacy manifests

---

packages/core/tests/integration/components/navi-visualizations/table-test.js

Fix flaky tests related to total/subtotaling

Update: Fix flaky test

---

packages/perspective/package.json

Fix: Set publish access to public

---

packages/data/addon/services/navi-dimension.ts
packages/data/addon/utils/classes/cache.ts
packages/data/addon/utils/search.ts
packages/data/config/environment.js
packages/data/config/navi-config.d.ts
packages/data/tests/unit/services/navi-dimension-test.ts
packages/data/tests/unit/utils/classes/cache-test.ts

Caching dimension filter values

---

packages/app/mirage/fixtures/reports.js
packages/app/mirage/fixtures/users.js
packages/core/addon/initializers/visualization-v2-transform.ts
packages/core/addon/mixins/models/has-visualization.ts
packages/core/addon/models/bar-chart.ts
packages/core/addon/models/goal-gauge.ts
packages/core/addon/models/line-chart.ts
packages/core/addon/models/metric-label.ts
packages/core/addon/models/pie-chart.ts
packages/core/addon/models/table.ts
packages/core/addon/models/visualization-v2.ts
packages/core/addon/models/visualization.ts
packages/core/addon/serializers/report.ts
packages/core/addon/serializers/visualization-v2.ts
packages/core/addon/serializers/visualization.ts
packages/core/addon/visualization/manifest.ts
packages/core/addon/visualization/model.ts
packages/core/tests/integration/components/navi-visualizations/wrapper-test.js
packages/core/tests/unit/initializers/visualization-v2-transform-test.ts
packages/core/tests/unit/serializers/goal-gauge-test.ts
packages/dashboards/addon/routes/dashboards/dashboard/widgets/widget/clone-to-report.ts
packages/dashboards/tests/unit/routes/dashboards/dashboard/widgets/widget/clone-to-report-test.js
packages/reports/tests/integration/components/print-report-view-test.js
packages/reports/tests/integration/components/report-view-test.js
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/DashboardWidgetVisualization.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/Visualization.kt

Use the legacy visualization as a base fragment for visualization-v2 and explicitly set a polymorphic key to the model we expect to instantiate

Update: Add namespace field to vis fragment

---

packages/data/config/navi-config.d.ts
packages/reports/addon/components/report-builder/sidebar.ts
packages/reports/addon/components/report-builder/source-selector-list.hbs
packages/reports/addon/components/report-builder/source-selector.ts
packages/reports/tests/dummy/config/environment.js
packages/reports/tests/integration/components/report-builder/sidebar-test.ts
packages/webservice/app/src/main/kotlin/com/yahoo/navi/ws/config/DataSource.kt
packages/webservice/app/src/main/kotlin/com/yahoo/navi/ws/config/NaviConfig.kt
packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/ServerGeneratedConfigTest.kt

Update: Hide datasources from UI

---

packages/core/addon/services/visualization.ts
packages/reports/addon/components/report-view.hbs
packages/reports/addon/components/report-view.ts
packages/reports/addon/components/visualization-toggle.hbs
packages/reports/addon/components/visualization-toggle.ts
packages/reports/app/styles/navi-reports/components/index.scss
packages/reports/app/styles/navi-reports/components/report-view.scss
packages/reports/app/styles/navi-reports/components/visualization-toggle.scss
packages/reports/tests/acceptance/report-test.js
packages/reports/tests/integration/components/visualization-toggle-test.ts

Show visualization categories in the selector
https://user-images.githubusercontent.com/12093492/155744694-8ef6b476-6d26-4730-bf97-af2dd89d236b.mov

Update: Visualization Selector with categories

---

packages/admin/package-lock.json
packages/admin/package.json
packages/core/addon/utils/chart.ts
packages/core/package-lock.json
packages/core/package.json
packages/dashboards/package-lock.json
packages/dashboards/package.json
packages/data/package-lock.json
packages/data/package.json
packages/directory/package-lock.json
packages/directory/package.json
packages/notifications/package-lock.json
packages/notifications/package.json
packages/perspective/package-lock.json
packages/perspective/package.json
packages/reports/package-lock.json
packages/reports/package.json
packages/search/package-lock.json
packages/search/package.json

Update to the latest typescript for some useful [new features](https://devblogs.microsoft.com/typescript/announcing-typescript-4-6/)

Update: All to latest typescript

---

packages/perspective/addon/components/perspective.hbs
packages/perspective/addon/components/perspective.ts
packages/perspective/tests/integration/components/perspective-test.ts

Update: Refactor perspective event handling

---

packages/perspective/tests/integration/components/perspective-test.ts

Fix: Wait longer in perspective test

---

package.json
packages/admin/package.json
packages/app/package.json
packages/core/package.json
packages/dashboards/package.json
packages/data/package.json
packages/directory/package.json
packages/notifications/package.json
packages/perspective/app/styles/yavin-ui-perspective.scss
packages/perspective/package-lock.json
packages/perspective/package.json
packages/reports/package.json
packages/search/package.json

Set up volta, update perspective to latest and fix the status bar arrow, column edit, and 
Some new features have since been added that don't yet support themeable icons

Update: Perspective to 1.3.5

---

packages/reports/addon/components/navi-action-list.hbs
packages/reports/tests/acceptance/report-test.js

New: Added edit route to report-table popup actions

---

packages/perspective/addon/components/perspective.hbs
packages/perspective/addon/components/perspective.ts
packages/perspective/tests/integration/components/perspective-test.ts

This PR fixes a race condition when loading a perspective config
-

Fix: Perspective config loading

---

packages/core/addon/models/delivery-rule.ts
packages/core/tests/unit/models/delivery-rule-test.js
packages/webservice/app/src/main/resources/db/changelog/changelog.xml
packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/DeliveryRulesTest.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/DeliveryRule.kt

Update: Failure Count

---

packages/perspective/addon/components/perspective.hbs
packages/perspective/addon/components/perspective.ts
packages/perspective/tests/integration/components/perspective-test.ts

Update: Don't save panel state & readonly support

---

packages/core/addon/utils/search.js
packages/core/tests/unit/utils/search-test.js

https://user-images.githubusercontent.com/55207313/161556749-1e7ff428-9d90-4298-952f-aa2f5751e18b.mov

Fix: Better special character search behavior

---

packages/data/addon/adapters/facts/bard.ts
packages/data/tests/unit/adapters/facts/bard-test.ts
packages/reports/addon/components/filter-builders/time-dimension.ts
packages/reports/tests/unit/components/filter-builders/time-dimension-test.ts

Resolves #
Add equals time dimension operator
- Add equals time dimension operator

Update: Add equals time dimension operator

---

packages/reports/addon/routes/reports/report/clone.ts
packages/reports/tests/acceptance/report-test.js

Fix: Let users rename cloned reports

---

packages/dashboards/addon/components/dashboard-actions/add-widget.hbs
packages/dashboards/tests/integration/components/dashboard-actions/add-widget-test.js

https://user-images.githubusercontent.com/55207313/164308923-70dcb360-eb0c-4b9b-abc1-50e57be1b41c.mov

Fix: Allow search when adding widgets

---

packages/reports/tests/unit/components/navi-collection-test.ts

Typescript fixup for [npm publish step](https://cd.screwdriver.cd/pipelines/6102/builds/789281/steps/publish)

Fix: NPM Publish

---

packages/webservice/app/build.gradle.kts
packages/webservice/app/src/main/kotlin/com/yahoo/navi/ws/config/ElideConfig.kt
packages/webservice/build.gradle.kts
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/hooks/UserValidationHook.kt

Update: Upgrade to Elide 6.1.5

---

packages/client/package.json

Fix: Publish config for @yavin/client

---

packages/client/package-lock.json
packages/client/package.json
packages/client/src/utils/classes/duration.ts
packages/client/test/tests/unit/utils/classes/duration-test.ts
packages/client/tsconfig-base.json
packages/data/addon/utils/classes/interval.ts
packages/data/addon/utils/duration-utils.ts
packages/data/app/utils/classes/duration.js
packages/data/tests/unit/utils/classes/interval-test.ts
packages/data/tests/unit/utils/duration-utils-test.ts
packages/reports/addon/components/filter-builders/time-dimension.ts
packages/reports/addon/components/filter-values/time-dimension/lookback.ts
packages/reports/addon/helpers/format-interval-inclusive-inclusive.js
packages/reports/tests/unit/helpers/format-interval-inclusive-inclusive-test.js

Update: Move the duration class to @yavin/client

---

packages/data/addon/services/data-availability.ts
packages/data/addon/services/navi-dimension.ts
packages/data/addon/utils/classes/cache.ts
packages/data/tests/unit/utils/classes/cache-test.ts

When checking for item in cache, remove stale items from cache prior to check
Remove parameter getCacheKey from class constructor

Fix: Update cache

---

packages/client/src/utils/search.ts
packages/reports/addon/components/common-actions/schedule.hbs
packages/reports/addon/components/common-actions/schedule.ts

Fixes:
- Make the type of searchRecords generic for more accurate return values
- Path to schedule image

Fix: Path to schedule image and searchRecords types

---

packages/data/addon/adapters/facts/elide.ts
packages/data/tests/unit/adapters/facts/elide-test.ts
packages/reports/tests/integration/components/common-actions/get-api-test.js

Update: Row limit logic for Elide facts

---

packages/client/src/plugins/fili/adapter/facts.ts
packages/data/tests/unit/adapters/facts/bard-test.ts

Update: Fili limit logic

---

packages/client/.eslintrc.cjs
packages/client/src/config/datasource-plugins.ts
packages/client/src/index.ts
packages/client/src/plugins/elide-apollo-client.ts
packages/client/src/plugins/elide.ts
packages/client/src/plugins/elide/adapters/facts.ts
packages/client/src/plugins/elide/adapters/metadata.ts
packages/client/src/plugins/elide/serializers/facts.ts
packages/client/src/plugins/fili.ts
packages/data/addon/services/yavin-client.ts

Automatically include the bard and elide adapters and serializers, plus the default service implementations in the client

Update: Include default client plugins

---

packages/client/src/gql/mutations/export-facts-cancel.graphql

Fix: CancelTableExport mutation

---

packages/webservice/build.gradle.kts

Upgrade to latest Elide version
Upgrade to latest Elide version
NA

[Update]: Elide to 6.1.7

---

packages/reports/tests/integration/components/common-actions/schedule-test.js
packages/webservice/app/src/main/kotlin/com/yahoo/navi/ws/config/ElideConfig.kt
packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/DeliveryRulesTest.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/DeliveryRule.kt
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/hooks/DisableDeliveryRuleHook.kt

Disable delivery rule

---

packages/client/.eslintrc.cjs
packages/client/build.mjs
packages/model-types/.gitignore
packages/model-types/.npmrc
packages/model-types/LICENSE.md
packages/model-types/README.md
packages/model-types/lib/index.d.ts
packages/model-types/lib/models/dashboard-widget.d.ts
packages/model-types/lib/models/dashboard.d.ts
packages/model-types/lib/models/delivered-items.d.ts
packages/model-types/lib/models/delivery-rule.d.ts
packages/model-types/lib/models/json-api.d.ts
packages/model-types/lib/models/report.d.ts
packages/model-types/lib/models/role.d.ts
packages/model-types/lib/models/user.d.ts
packages/model-types/lib/models/visualization.d.ts
packages/model-types/package-lock.json
packages/model-types/package.json
packages/model-types/tests/index.ts
packages/model-types/tsconfig.json
screwdriver.yaml

Adds a new library with TS definitions to help when querying the webservice

Update: Add @yavin/model-types with ts defs for json:api queries

---

packages/client/package-lock.json
packages/client/package.json
packages/client/src/errors/navi-adapter-error.ts

Effection error fix 
- Upgrade effection to version that fixes the root issue:  https://github.com/thefrontside/effection/issues/675
- Revert temporary workaround in #1710 

Fix: Effection update to fix timeout errors

---

CONTRIBUTING.md
README.md
packages/app/package.json
packages/c3/package.json
packages/client/package.json
packages/core/package.json
packages/dashboards/package.json
packages/data/package.json
packages/directory/package.json
packages/model-types/package.json
packages/notifications/package.json
packages/perspective/package.json
packages/reports/package.json
packages/webservice/models/build.gradle.kts
scripts/maven-publish.sh
scripts/npm-publish.sh

We're still checking for "master" branch in our publish scripts.

Update: Publish from main branch

---

packages/client/src/gql/schema.graphql
packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/enums/DeliveryType.kt

Add `anomaly` as valid delivery type
- Add `anomaly` as valid delivery type

Update: Add Anomaly Alert as valid deliverytype.
