- packages/reports/addon/components/dimension-selector.js
- packages/reports/addon/components/filter-builders/date-time.js
- packages/reports/addon/components/report-builder.js
- packages/reports/addon/consumers/request/logical-table.js
- packages/reports/addon/mirage/fixtures/reports.js
- packages/reports/addon/models/bard-request/fragments/logical-table.js
- packages/reports/addon/templates/components/report-builder.hbs
- packages/reports/app/styles/navi-reports/components/report-builder.less
- packages/reports/tests/acceptance/navi-report-test.js
- packages/reports/tests/unit/models/bard-request/fragments/logical-table-test.js
- packages/reports/tests/unit/models/bard-request/request-test.js
* Would crash UI otherwise
* Likely to happen when users share reports to a table that
one user doesn't have access
* Also hides components that would crash without metadata
that user wouldn't be able to use anyway
* Allows users to select a valid table.
* Changes error message to reflect the actual problem
> Fix: Shows error when report has invalid logical table

- packages/data/addon/services/bard-metadata.js
- packages/data/tests/unit/services/bard-metadata-test.js
* The call for the extended metadata getting blocked by check in the keg since the nonextended meta data already exists in the keg.
* Split the functionality of checking the keg first in new method `findById` so `fetchById` always fetches from metadata as intended.
* Looks like the original intention of preventing duplicate metadata would not break by moving the "already in the keg" guard.
> Fix: tooltip metadata call not happening

- packages/dashboards/app/mirage/fixtures/dashboard-widget.js
- packages/dashboards/tests/unit/models/dashboard-widget-test.js
- packages/visualizations/addon/components/navi-visualizations/goal-gauge.js
- packages/visualizations/addon/models/goal-gauge.js
- packages/visualizations/addon/serializers/goal-gauge.js
- packages/visualizations/app/serializers/goal-gauge.js
- packages/visualizations/tests/dummy/app/controllers/goal-gauge.js
- packages/visualizations/tests/dummy/app/routes/goal-gauge.js
- packages/visualizations/tests/integration/components/navi-visualizations/goal-gauge-test.js
- packages/visualizations/tests/unit/models/goal-gauge-test.js
- packages/visualizations/tests/unit/serializers/goal-gauge-test.js
Updates goal gauge visualization to use a metric object instead of a string
Part of #71
> Breaking: Update goal gauge model metric to be an object (refs #71)

- packages/visualizations/addon/components/navi-visualizations/line-chart.js
- packages/visualizations/addon/components/navi-visualizations/pie-chart.js
- packages/visualizations/addon/helpers/tooltip-value-formatter.js
- packages/visualizations/addon/templates/chart-tooltips/date.hbs
- packages/visualizations/addon/templates/chart-tooltips/dimension.hbs
- packages/visualizations/addon/templates/chart-tooltips/metric.hbs
- packages/visualizations/addon/templates/chart-tooltips/pie-chart.hbs
- packages/visualizations/tests/dummy/app/controllers/pie-chart.js
With the metric reshaping in the visualizations, we can get rid of some of the things that we pass to the tooltips. This does mean that apps that use navi-visualizations and override the 
tooltip-value-formatter helper will need an update to handle the metric object.
> Breaking: Refactor tooltips to use new metric object shape in visualizations (refs #71)

- packages/visualizations/addon/validators/request-metric-exist.js
having just {} as default request was causing chart-data util to fail.
This broke when you refreshed goal gauge reports for example
> Fix: Better default request for validator

- packages/reports/config/environment.js
- packages/reports/tests/integration/components/navi-date-range-picker-test.js
remove predefined ranges for All timegrain since CURRENT macro is not supported for all timegrain in fili
> remove predefined ranges for All timegrain

- packages/reports/addon/consumers/report/table-visualization.js
- packages/reports/tests/unit/consumers/report/table-visualization-test.js
Reordering a metric whose name is changed, breaks the report
https://digits-ziggurat-zigguratcomponent-prod.gq1-1.paas.yahoo.com:4443/reports/8888/view
reordering the table columns in the above report breaks
> Fix: Reorder table column error

- packages/reports/addon/models/bard-request/request.js
- packages/reports/tests/unit/models/bard-request/request-test.js
Clone parameters with metrics when cloning requests
> Fix: Clone parameters with metrics when cloning requests

- packages/dashboards/app/styles/navi-dashboards/components/navi-dashboard.less
- packages/dashboards/package.json
Before: 
After: 
Adds some space between the bottom widget and the bottom of the dashboard body. 
Also updated ember-cli-dependency-checker because the app would not run locally for me otherwise.
> Update: Add margin to bottom of dashboard

- packages/visualizations/addon/models/table.js
- packages/visualizations/tests/unit/models/table-test.js
to reproduce:
1) Choose a few paramterized metric off the same base metric, run report
2) See column names are all different as expected.
3) add another metric or dimension, run report
4) See the parameterized metric all have the same display name.
> Fix: Parameterized metrics get renamed the same

- packages/app/config/environment.js
- packages/visualizations/addon/components/navi-visualizations/table.js
- packages/visualizations/addon/templates/components/navi-visualizations/table.hbs
- packages/visualizations/app/styles/navi-visualizations/visualizations/table.less
- packages/visualizations/tests/acceptance/table-test.js
- Fix: Don't mark blank column titles as edited
- Fix: Only style column title when edited
- Update: Add table column title edit message 
- Added table column title edit message
- Refactored table header styles and selectors
> Add column edit msg

- packages/core/addon/mirage/fixtures/reports.js
- packages/data/tests/unit/helpers/metric-format-test.js
- packages/reports/tests/acceptance/navi-report-test.js
- packages/reports/tests/unit/serializers/report-test.js
- packages/visualizations/addon/helpers/default-column-name.js
- packages/visualizations/tests/integration/helpers/default-column-name-test.js
The default name of metric column is not displayed correctly for metric with parameters
> Fix: Metric format on serialized metric mode

- packages/directory/.bowerrc
```
> navi-directory@0.1.0-alpha.497411ed postinstall /Users/balajim1/Git/Teller/node_modules/navi-directory
> bower install
bower                           ENOENT No bower.json present
```
> Fix: Add missing bowerrc

- packages/directory/addon/templates/directory.hbs
- packages/directory/app/styles/navi-directory/components/dir-new-button.less
For now, we are using my forked version of ember-tooltips since it seems it will take a while to get a response to my PR here: https://github.com/sir-dunxalot/ember-tooltips/pull/258
Once that PR is merged or another fix is implemented, we can go back to using the published version of ember-tooltips. Issue created here: https://github.com/yahoo/navi/issues/139
Addresses comments at the bottom of #129
> Update: Polish the new directory button

- packages/data/addon/mirage/fixtures/bard-meta-dimensions.js
- packages/data/addon/mirage/routes/bard-lite.js
- packages/reports/addon/components/filter-values/dimension-select.js
- packages/reports/addon/consumers/request/filter.js
- packages/reports/tests/integration/components/dimension-selector-test.js
- packages/reports/tests/integration/components/filter-values/dimension-select-test.js
- packages/reports/tests/unit/consumers/request/filter-test.js
- packages/visualizations/addon/components/cell-renderers/dimension.js
- packages/visualizations/addon/templates/components/cell-renderers/dimension.hbs
- packages/visualizations/tests/integration/components/cell-renderers/dimension-test.js
Dimensions don't always use `id` as their primary key.  We have tags set up to specify which dimension field is the primary key, and therefore we can build the correct dimension filter that gives the intended results.
> Update: Dimension filter uses primaryKey tag

- packages/app/package.json
- packages/core/package.json
- packages/dashboards/package.json
- packages/directory/package.json
- packages/reports/package.json
The fix for Ember 3.0 that I submitted to ember-tooltips got merged and they came out with a release today.
> Update: Ember-tooltips version to support Ember 3.x

- packages/core/app/styles/navi-core/visualizations/table.less
This prevents table headers to break at middle of words when wrapping.
Single words may now be broken at arbitrary points only if there are no otherwise acceptable break points in the line.
> Fix: Table headers break at middle of words when wrapping

- packages/core/addon/components/navi-visualizations/line-chart.js
- packages/core/addon/components/navi-visualizations/pie-chart.js
- packages/core/tests/integration/components/navi-visualizations/line-chart-test.js
- packages/core/tests/integration/components/navi-visualizations/pie-chart-test.js
- packages/core/tests/unit/components/navi-visualizations/line-chart-test.js
- Cleanup tooltip registry when chart is destroyed
- Include `chartType` in tooltip name to distinguish between `bar` & `line` chart
> Fix: Cleanup tooltip registry when chart is destroyed

- packages/core/addon/models/bard-request/request.js
- packages/core/tests/unit/models/bard-request/request-test.js
fields in dimension filters were not being cloned correctly, causing default "id" field to be filtered, which breaks things.
> Fix: Fields in filters now being cloned correctly

- packages/directory/addon/components/dir-item-name-cell.js
- packages/directory/addon/templates/components/dir-item-name-cell.hbs
- packages/directory/app/styles/navi-directory/components/dir-item-name-cell.less
- packages/directory/tests/integration/components/dir-item-name-cell-test.js
- packages/directory/tests/unit/components/dir-item-name-cell-test.js
- packages/reports/addon/routes/reports/report/index.js
An issue was found where trying to open an unsaved report from the directory view wouldn't do anything. This should restore that functionality and I added a couple tests.
Unsaved report at the bottom
> Fix: Unsaved report links in directory

- packages/directory/addon/components/dir-icon.js
- packages/directory/addon/templates/components/dir-icon.hbs
- packages/directory/addon/templates/components/dir-item-name-cell.hbs
- packages/directory/addon/templates/components/dir-new-button.hbs
- packages/directory/addon/templates/components/dir-table.hbs
- packages/directory/app/styles/navi-directory/components/dir-icon.less
- packages/directory/tests/acceptance/dir-table-test.js
- packages/directory/tests/integration/components/dir-icon-test.js
- packages/directory/tests/integration/components/dir-item-name-cell-test.js
Sets the occlusion flag to true on the dir-table. There were some issues with the classNames being applied incorrectly to the icons with occlusion on, so I've added a wrapper component `dir-icon` to the `navi-icon` component in order to apply the correct styles.
> Update: Add occlusion rendering to directory table

- packages/directory/addon/templates/components/dir-item-name-cell.hbs
These lines were accidentally included when rebasing my occlusion PR branch. We only want one favorite icon
> Fix: Remove line leftover from rebase

- .travis.yml
Cuts the build time by a few minutes for each package 
The difference:
> Update: Upgrade node to 8 in travis build

- packages/directory/app/styles/navi-directory/components/dir-sidebar.less
> Fix: Directory Sidebar spacing issue in Firefox

- packages/directory/app/styles/navi-directory/components/dir-asset-row-actions.less
> Update: Align schedule button with other actions in directory

- packages/data/addon/mirage/fixtures/bard-meta-dimensions.js
- packages/data/addon/models/metadata/dimension.js
- packages/data/addon/services/bard-dimensions.js
- packages/data/tests/unit/services/bard-dimensions-test.js
- packages/reports/addon/components/dimension-bulk-import.js
- packages/reports/addon/components/power-select-bulk-import-trigger.js
- packages/reports/tests/integration/components/dimension-bulk-import-test.js
When we have a dimension with a smartkey, we need people to do bulk import of searchable ids.  The bulk importer needs to search against the right field.  This change makes sure that bulk-import works for smart key dimensions by looking to see if they have an 'id' tagged field and searching against that.  Otherwise, we search against primaryKey (searching against primaryKey was previous behavior).
Also found an issue which putting ids that were comma separated with spaces was sending bad requests to fili.  The splitting has been improved.
> Fix: Smartkey dimension bulk-import fix

- packages/core/app/styles/navi-core/components/navi-loader.less
Firefox before/after:
Chrome:
---
There's still a small issue with the horizontal scroll bar in Firefox, but I'm not sure what's causing it
> Fix: size of loading view in Firefox

- packages/dashboards/addon/helpers/reportify.js
The `reportify` helper creates a `report` from a `dashboard-widget`, which is then passed to `export` or `multiple-format-export` component.
It is not persisted at any point.
My first thinking was to make `reportify` return an Ember object instead of a `report` model.
csv link would work fine with an object, however `pdfHref` in `multiple-format-export` uses the `model-compression` service which expects a `report` model. 
This could be refactored as well to accept an object, but a more simple solution would be to just remove the `author` property when reportifying a widget, and then it wouldn't show up in the user's directory.
We actually do the same in `multiple-format-export` when we export a new unsaved report (with no `id`) - we call `report.clone()` which does not copy the `author` …
> Fix: Adding a new widget creates unsaved reports

- packages/core/addon/components/table-renderer-vertical-collection.js
Scrolling via the header via trackpad gesture or vertical scroll wheel didn't work.
This fixes that as both seem to be capturable with the 'wheel' event.  best of all this event is fired even when the container isn't scrollable! So we take the data from the wheel event and fire a scroll event to the table body.
> Fix: Vertical Collection header scroll gesture

- packages/app/tests/unit/services/navi-notifications-test.js
Build fails in navi-app without this
> Fix: Build failing due to new ember-cli-flash version

- packages/reports/app/styles/navi-reports/components/navi-table-select.less
Before:
table wraps to second line
After:
table name stays on the current line
Fixes #233
> Fix table select styling for long table names

- packages/core/addon/mirage/fixtures/reports.js
- packages/reports/addon/components/metric-config.js
- packages/reports/tests/acceptance/metric-parameters-test.js
Fixes bug in which, loading a report with empty parameters. (such as an old report, or a report with bad parameter values). the metric config component will fail to render entirely instead of letting users pick valid parameters.
gif of current behavior:
> Fix: Metric param selector fails on empty parameters

- .travis.yml
- packages/app/package.json
- packages/core/addon/chart-builders/date-time.js
- packages/core/package.json
- packages/core/tests/acceptance/table-test.js
- packages/core/tests/dummy/config/ember-intl.js
- packages/core/tests/helpers/destroy-app.js
- packages/core/tests/integration/components/navi-visualizations/goal-gauge-test.js
- packages/core/tests/integration/components/navi-visualizations/table-print-test.js
- packages/core/tests/integration/components/navi-visualizations/table-test.js
- packages/core/tests/integration/components/visualization-config/table-test.js
- packages/core/tests/integration/helpers/default-column-name-test.js
- packages/core/tests/unit/chart-builders/date-test.js
- packages/core/tests/unit/chart-builders/dimension-test.js
- packages/core/tests/unit/chart-builders/metric-test.js
- packages/core/tests/unit/components/visualization-config/table-test.js
- packages/core/tests/unit/models/bard-request/fragments/dimension-test.js
- packages/core/tests/unit/models/bard-request/fragments/filter-test.js
- packages/core/tests/unit/models/bard-request/fragments/having-test.js
- packages/core/tests/unit/models/bard-request/fragments/interval-test.js
- packages/core/tests/unit/models/bard-request/fragments/logical-table-test.js
- packages/core/tests/unit/models/bard-request/fragments/metric-test.js
- packages/core/tests/unit/models/bard-request/fragments/sort-test.js
- packages/core/tests/unit/models/bard-request/request-test.js
- packages/dashboards/package.json
- packages/dashboards/tests/helpers/destroy-app.js
- packages/directory/package.json
- packages/reports/package.json
- packages/reports/tests/helpers/destroy-app.js
We should statically determine what the display month is for a week rather than depend on the date of runtime. 
It seems that ember-sortable 1.12.4 released about a week ago and it was causing some of our tests to time out.
> Fix: Build timing out in reports and core

- packages/reports/addon/components/dropdown-date-picker.js
- packages/reports/addon/components/filter-values/date.js
- packages/reports/addon/components/navi-date-picker.js
- packages/reports/addon/templates/components/dropdown-date-picker.hbs
- packages/reports/addon/templates/components/filter-values/date.hbs
- packages/reports/addon/templates/components/navi-date-range-picker.hbs
- packages/reports/app/components/dropdown-date-picker.js
- packages/reports/app/styles/navi-reports/components/dropdown-date-picker.less
- packages/reports/app/styles/navi-reports/components/filter-values.less
- packages/reports/app/styles/navi-reports/components/index.less
- packages/reports/tests/integration/components/dropdown-date-picker-test.js
- packages/reports/tests/integration/components/filter-values/date-test.js
- packages/reports/tests/integration/components/navi-date-picker-test.js
Moved the dropdown date picker with reset and apply buttons to its own component. Before, we only had this for filter values so this is a little more generic. Next PR will use two instances of this component to make a dimension date range selector filter value component.
> Dropdown date picker component

- packages/reports/addon/components/filter-builders/date-dimension.js
- packages/reports/addon/components/filter-values/dimension-date-range.js
- packages/reports/addon/templates/components/filter-values/dimension-date-range.hbs
- packages/reports/app/components/filter-values/dimension-date-range.js
- packages/reports/app/styles/navi-reports/components/filter-collection.less
- packages/reports/app/styles/navi-reports/components/filter-values.less
- packages/reports/tests/integration/components/filter-values/dimension-date-range-test.js
Uses two dropdown date pickers to select two dates that make up an interval for dimensions with date values to filter by.
> Add dimension date range filter value

- packages/reports/addon/routes/reports/report.js
- packages/reports/tests/acceptance/navi-report-test.js
While upgrading my project which depends on navi. I get the error: 
Assertion Failed: Attempted to call .send() with the action 'revertChanges' on the destroyed route 'reports.report'
Found that in ember 3.2 they've added an assertion to check for actions being sent on destroyed components.
https://github.com/emberjs/ember.js/issues/16820
speaks of a workaround
fixes https://github.com/yahoo/navi/issues/287
> Revert Changes before transitioning

- packages/directory/addon/templates/components/dir-sidebar.hbs
- packages/directory/tests/acceptance/dir-sidebar-test.js
- packages/directory/tests/dummy/app/components/dir-sidebar.js
- packages/directory/tests/dummy/app/router.js
- packages/directory/tests/dummy/app/routes/directory/other-data.js
- packages/directory/tests/dummy/app/templates/directory/other-data.hbs
- packages/directory/tests/dummy/app/utils/enums/directories.js
- packages/directory/tests/integration/components/dir-sidebar-test.js
The favorites filter in the directory route should specifically be applied to `my-data`
> Update: Favorites filter should link to my-data route then add filter

- packages/core/addon/components/pick-container.js
- packages/core/addon/models/bard-request/fragments/metric.js
- packages/core/addon/models/bard-request/request.js
- packages/core/package.json
- packages/core/tests/integration/components/pick-container-test.js
- packages/reports/addon/templates/components/navi-date-range-picker.hbs
- packages/reports/addon/templates/components/pick-single.hbs
fixes #296 
fixes #297 
passing a target to a closure action
https://github.com/emberjs/ember.js/blob/v3.7.2/packages/%40ember/-internals/glimmer/lib/helpers/action.ts#L79
deprecated target Object
https://github.com/emberjs/ember.js/issues/14168
deprecation of ember internals copy
https://deprecations-app-prod.herokuapp.com/deprecations/v3.x/#toc_ember-runtime-deprecate-copy-copyable
> Fix: Remove targetObject use and ember internals copy (fixes #296)

- packages/reports/addon/components/dropdown-date-picker.js
- packages/reports/addon/components/filter-builders/date-dimension.js
- packages/reports/tests/acceptance/date-filter-test.js
- packages/reports/tests/integration/components/filter-values/dimension-date-range-test.js
The test for the dimension date range filter was dependent on the time that the test was run. These changes should make it behave the same way no matter when it's run. When I was fixing this, I also noticed an issue where a report that has a dimension date range filter would not keep the filter values after being saved. I fixed that and added a test for that behavior.
> [Fixes Build] Dimension date range selector not saving

- packages/core/addon/components/cell-renderers/dimension.js
- packages/core/addon/components/cell-renderers/metric.js
- packages/core/addon/components/navi-visualizations/table.js
- packages/core/addon/components/number-format-dropdown.js
- packages/core/addon/helpers/default-column-name.js
- packages/core/addon/models/table.js
- packages/core/addon/serializers/table.js
- packages/core/tests/dummy/app/controllers/table.js
- packages/core/tests/integration/components/cell-renderers/dimension-test.js
- packages/core/tests/integration/components/cell-renderers/metric-test.js
- packages/core/tests/integration/components/cell-renderers/threshold-test.js
- packages/core/tests/integration/components/navi-visualizations/table-print-test.js
- packages/core/tests/integration/components/navi-visualizations/table-test.js
- packages/core/tests/integration/components/table-cell-renderer-test.js
- packages/core/tests/integration/helpers/default-column-name-test.js
- packages/core/tests/unit/components/navi-visualizations/table-test.js
- packages/core/tests/unit/models/table-test.js
- packages/core/tests/unit/serializers/table-test.js
- packages/data/addon/utils/dimension.js
- packages/data/addon/utils/metric.js
- packages/data/tests/unit/utils/metric-test.js
- packages/reports/addon/consumers/report/table-visualization.js
- packages/reports/tests/integration/components/print-report-view-test.js
- packages/reports/tests/integration/components/report-view-test.js
- packages/reports/tests/unit/consumers/report/table-visualization-test.js
This changes the columns representations to:
```
{
type: 'dimension',
attributes: {
name: 'advanceTrafficCurrency',
field: 'id'
},
displayName: 'Traffic Currency'
}
```
```
{
type: 'metric',
attributes: {
name: 'pageViews',
format: '0.0a',
parameters: {...}
},
displayName: 'Page Views'
}
```
```
{
type: 'dateTime',
attributes: {
name: 'dateTime'
},
displayName: 'Date'
}
```
> Breaking: Table visualization model change (fixes #300)

- packages/dashboards/index.js
- packages/data/index.js
- packages/reports/index.js
We have `isDevelopingAddon` set to true in only dashboards, reports, and data. These shouldn't be true when we publish our addons. With Ember 3, this flag will cause Navi's template files to be run through the template linter for apps that use Navi.
More info:
https://github.com/ember-template-lint/ember-template-lint/issues/119#issuecomment-258620041
> Update: Remove Flag that shouldn't be published

- packages/directory/package.json
Solves an issue where the OrderedSet class was not being found within Ember. Daniel is working on upgrading Ember in this addon anyway so we can keep it to ~3.1.3 until his upgrade is ready.
> Fix: Build failing in directory due to new Ember release

- packages/app/app/router.js
- packages/core/addon/mirage/serializers/base-json-serializer.js
- packages/dashboards/addon/routes/dashboard-collections/collection.js
- packages/dashboards/addon/routes/dashboards/dashboard.js
- packages/dashboards/addon/routes/dashboards/dashboard/widgets/widget.js
- packages/dashboards/blueprints/navi-dashboards/index.js
- packages/dashboards/tests/dummy/app/router.js
- packages/dashboards/tests/unit/routes/dashboard-collections/dashboard-collections-test.js
- packages/dashboards/tests/unit/routes/dashboards/dashboard/widgets/widget-test.js
- packages/dashboards/tests/unit/routes/dashboards/dashboards-test.js
- packages/reports/addon/routes/report-collections/collection.js
- packages/reports/addon/routes/reports/report.js
- packages/reports/addon/routes/reports/report/view.js
- packages/reports/blueprints/navi/index.js
- packages/reports/tests/dummy/app/router.js
- packages/reports/tests/unit/routes/report-collections/collection-test.js
- packages/reports/tests/unit/routes/reports/report-test.js
The dynamic segments of the routes should be in snake case for Ember 3. 
Also there was an issue with setting the report state. The [issue](https://github.com/emberjs/ember.js/issues/17545) is that the contract for the `transition.send` function changed. The first argument in the function definition is `ignoreFailure` which used to be defined as a boolean. So I think since we were calling `transition.send` and passing a string as the first argument, the compiler would know that the string wasn't meant to be assigned to `ignoreFailure`. There was a change recently that no longer defines `ignoreFailure` as a boolean, but gives it a default value of `false`. Now that means that when we pass a string as the first argument, that string gets passed as `ignoreFailure` to `transition.send` and …
> Breaking: Make navi more compatible with Ember 3.x apps

- packages/dashboards/addon/templates/dashboard-collections/index.hbs
- packages/reports/addon/templates/report-collections/index.hbs
Previous PR changed routes to use snake case for dynamic route segments and hyphenated the route names
- Hyphenate route names that were missed
> Fix: Route names should be hyphenated

- packages/core/.npmignore
the `bower.json` file was not pushed to NPM because it was listed in the `.npmignore` file.  This breaks the node-core install.
- Remove `bower.json` and `.bowerrc` from `.npmignore`.
> Fix: Reinclude bower in the npmignore.

- packages/core/addon/components/navi-visualizations/table.js
- packages/core/tests/integration/components/navi-visualizations/table-test.js
Resolves HOTFIX
some addons aren't using Ember.NativeArray yet so addressing by 'model.0' doesn't work.
change to 'model.firstObject'
fix tests so it doesn't break 'firstObject' contract.
> Fix: Table rendering in widgets

- packages/core/addon/components/navi-visualizations/table.js
Resolves #
Found an issue where dates weren't being formatted correctly in widgets
Same as yesterday's bug fix, just missed one.
> Fix: Missed one.

- packages/data/addon/adapters/dimensions/bard.js
- packages/data/addon/mirage/routes/bard-lite.js
- packages/data/addon/services/bard-dimensions.js
- packages/data/tests/unit/adapters/dimensions/bard-test.js
- packages/data/tests/unit/services/bard-dimensions-test.js
- packages/reports/addon/components/filter-values/dimension-select.js
New endpoint `/dimensions/<dimensionName>/search/?query=<query>` when searching for dimension values. 
Behind a `newDimensionsSearchAPI` feature flag.
> Update: Use new dimensions search endpoint

- packages/reports/addon/controllers/reports/report.js
- packages/reports/addon/routes/reports/report.js
- packages/reports/addon/routes/reports/report/save-as.js
- packages/reports/addon/templates/reports/report.hbs
- packages/reports/tests/acceptance/navi-report-test.js
Save As modal no longer closes after successful save.
Change modal state to controller, send actions to controller
> Fix: Save As modal closes after success

- packages/core/addon/models/table.js
- packages/core/tests/unit/models/table-test.js
- packages/reports/tests/acceptance/date-filter-test.js
We recently decided that when the request has a timegrain of `all`, we will hide the dateTime column in the table visualization.
- Change table model validations to check for the existence of the datetime column based on the timegrain
- Change `rebuildConfig` in table model to handle adding or removing the datetime column when the timegrain changes
> Update: Hide datetime column on all timegrain

- packages/reports/addon/components/filter-values/dimension-select.js
- packages/reports/tests/acceptance/navi-report-test.js
- packages/reports/tests/acceptance/report-visualizations-test.js
Resolves #344 
For large dimensions you must paste the term 2 or 3 times before the value shows up in the results. In some cases it briefly flashes the value but then disappears from the results list.
- Stop loading all dimensions on initial filter dimension selector focus for large dimensions as defined by `config.navi.searchThresholds.contains`.
No initial load all on focus for large cardinality dimension:
Load after value input:
> Fix: Stop dimension filter initial loading of large dimensions.

- packages/reports/addon/controllers/reports/report.js
- packages/reports/addon/controllers/reports/report/view.js
- packages/reports/addon/routes/reports/report.js
- packages/reports/addon/routes/reports/report/view.js
- packages/reports/addon/templates/components/report-view.hbs
- packages/reports/addon/templates/print/reports/report/view.hbs
- packages/reports/addon/templates/reports/report/view.hbs
- packages/reports/tests/acceptance/navi-report-test.js
- packages/reports/tests/unit/routes/reports/report/view-test.js
This tries to solve 2 UX issues:
1. We don't always need to rerun the report, the "Run request to update Table" message should not be displayed after changes like column title/format and the run button should be disabled.
2. editing mode of table remains "on" even if report is changed and `visualization-config` is hidden:
Bringing back here something similar to what we had before - a property controller `hasRequestRun` (`hasReportRun` is too confusing with the report completed status)
the main difference is that `previousRequest` lives in the `reports.report` controller rather that the `view` router so it can be accessed from both `runReport` in the `view` route and `onUpdateReport` in the `report` route. Not sure if it's a bad practice to read controller properties from child routes. …
> Update: Check if report needs rerun

- packages/core/addon/manifests/bar-chart.js
- packages/core/addon/manifests/base.js
- packages/core/addon/manifests/line-chart.js
- packages/core/addon/models/bard-request/request.js
- packages/core/tests/unit/models/bard-request/request-test.js
- packages/dashboards/tests/acceptance/explore-widget-test.js
- packages/dashboards/tests/acceptance/report-action-test.js
- packages/reports/tests/acceptance/navi-report-test.js
Fili is removing the requirement to choose a metric. We will be too. this will allow dimension only reporting.
Update ember data model for request to require selecting a metric.
Make sure alerts is good. make sure adapter handles empty metrics correctly.
- Remove request model validation that requires at least one metric.
> Update: Remove metric requirement validation

- packages/reports/addon/components/pick-range-container.js
- packages/reports/addon/templates/components/navi-date-range-picker.hbs
- packages/reports/tests/integration/components/navi-date-range-picker-test.js
Bug reported that opening date picker in report builder, they couldn't select the next day if they already specified an interval.
reproduce step:
* Create a report with a custom date range and run it.
* open up custom date range and try to pick the day after your previous range selection as the end range
* Note that it won't let you pick the date.
Found code that won't adjust the end correctly if date selected is the same day as the previous interval. Because the switching between inclusive-inclusive and inclusive-exclusive this doesn't work well.
Noticed that the advanced editor when you select a date, it will increase the date by 1 if you focus out.  Since this already is inclusive-exclusive range it shouldn't adjust. So created a separate setEnd action. So that logic from selecting a …
> Fix: Next day selection bug.

- packages/reports/addon/templates/components/navi-list-selector.hbs
- packages/reports/app/styles/navi-reports/components/navi-list-selector.less
Chrome has been going really aggressive with autofill suggestions.  Shows up on dimension and metric search boxes.  Chrome has said for semantically ambiguous inputs it will try to figure out how to autofill, and outright ignores `autocomplete=off` or `=false`.  All tickets have been closed as "won't fix"
To fix this, it seems we need to hint that semantically these are search boxes and turn `autocomplete=off`. Chrome does seem to respect autofill being off on search type boxes.
Chrome also adds a clear button, which would make the one we put in redundant. However, this is not supported in firefox, so I have hidden the chrome's provided one in favor of cross-browser feature parity. 
No visual difference
> Fix: Autocomplete on metric/dimension search boxes

- packages/reports/app/styles/navi-reports/components/print-report-view.less
Goal-gauge legend is partially hidden when printing with pupeteer
Nudge it up a little
Hardly changes viz for phantom
\* might add more changes to this PR after testing dashboards printing
> Update: Nudge the goal-gauge legend a little up

- packages/dashboards/addon/controllers/dashboards/dashboard/widgets/widget/view.js
- packages/dashboards/tests/acceptance/explore-widget-test.js
This bug was probably introduced in #352 when `hasRequestRun` was added only to report/view controller and not to widget/view
- Inherit from the report/view controller to include this method
- add tests
> Fix: Notification to rerun is always visible when editing a widget

- .travis.yml
- package-lock.json
- package.json
- packages/app/package.json
- packages/core/.npmignore
- packages/core/package.json
- packages/dashboards/package.json
- packages/directory/.npmignore
- packages/directory/package.json
- packages/reports/.npmignore
- packages/reports/package.json
Don't do bower install as package npm postinstall
- Move bower to top level `devDependencies`
- Run bower install as top level post install
- Add `bower.json` to package level .npmignore
> Fix: Don't do bower install as npm postinstall

- .gitignore
- packages/reports/addon/components/filter-builders/base.js
- packages/reports/addon/components/filter-builders/dimension.js
- packages/reports/addon/templates/components/filter-builders/base.hbs
- packages/reports/addon/templates/components/filter-builders/dimension.hbs
- packages/reports/app/styles/navi-reports/components/filter-collection.less
- packages/reports/tests/acceptance/navi-report-test.js
- packages/reports/tests/integration/components/filter-builders/dimension-test.js
- packages/reports/tests/integration/components/filter-collection-test.js
Allows user to choose the field of a dimension when using the "Contains" operator. 
Update the dimension filter builder to allow for field selection of the operator supports it. We must also make sure we switch the field back to the primary key when choosing operators that do not support field choice.
> Update: Field selection on contains filter

- packages/reports/addon/templates/components/dimension-selector.hbs
- packages/reports/addon/templates/components/editable-label.hbs
- packages/reports/addon/templates/components/favorite-item.hbs
- packages/reports/addon/templates/components/metric-selector.hbs
- packages/reports/addon/templates/components/navi-table-select.hbs
- packages/reports/app/styles/navi-reports/common/ember-tooltips.less
Tooltips on an element/component that have overflow: hidden will hide part of the tooltips
- Use body as base of the tooltip as mentioned here: https://github.com/sir-dunxalot/ember-tooltips/blob/master/UPGRADING-3.x.md#my-tooltips-appear-clipped-use-within-elements-using-overflow-hidden
Before 
After
> Fix tooltip problem

- packages/dashboards/addon/routes/dashboards.js
- packages/dashboards/addon/templates/components/navi-dashboard.hbs
- packages/dashboards/tests/acceptance/schedule-modal-test.js
Saving a schedule from the dashboard view would never stop saving.
- Use delivery-action-consumer actions to handle changes to the schedule modal like we do in dashboard and report collections
> Fix: Saving a schedule in the dashboard view never finishes

- packages/core/addon/mirage/fixtures/dashboard.js
- packages/core/tests/unit/models/dashboard-test.js
- packages/dashboards/addon/components/navi-widget.js
- packages/dashboards/addon/templates/components/dashboard-action-list.hbs
- packages/dashboards/addon/templates/components/navi-widget.hbs
- packages/dashboards/addon/templates/dashboards/dashboard/widgets/widget.hbs
- packages/dashboards/app/styles/navi-dashboards/components/navi-widget.less
- packages/dashboards/tests/acceptance/dashboards-test.js
- packages/dashboards/tests/integration/components/navi-widget-test.js
Sometimes filters applied to a dashboard cannot be applied to all widgets due to widgets having different logical tables with different 
- Add a warning icon next to the title of a widget that could not apply all global dashboard 
filters
> Dashboard widget warning symbol

- .github/PULL_REQUEST_TEMPLATE.md
Add license to PR Template
```
Ben Pearson [8:45 AM]
Hi Balaji,
We are in the process of removing the need for contributors to sign a CLA when they submit PR's to our projects by adding a new section to our projects' pull request templates.
This file: https://github.com/yahoo/navi/blob/master/.github/PULL_REQUEST_TEMPLATE.md
Should have the following content at the bottom of it:
Once this statement is in place, I will turn off the CLA checker for this repo. From here on, the only people who need to sign our CLA is anyone that is not a Verizon Media employee who is granted write access to the repository. For everyone who is …
```
> Update: Add license to PR Template

- packages/dashboards/addon/templates/components/navi-dashboard.hbs
- packages/dashboards/app/styles/navi-dashboards/common.less
- packages/dashboards/app/styles/navi-dashboards/components/dashboard-filters.less
- packages/dashboards/app/styles/navi-dashboards/components/navi-dashboard.less
- packages/dashboards/app/styles/navi-dashboards/views/navi-dashboards.less
- packages/dashboards/tests/dummy/app/styles/app.less
Expanded dashboard filter view can block a lot of the view of the dashboard without being able to scroll to the part of the dashboard that is blocked. 
- Use position: relative on the expanded dashboard filters view 
- Move dashboard filters outside of the dashboard header.
- Add internal padding to the scrolled div.
> Update: Keep expanded dashboards filters view in flow of document

- packages/reports/addon/helpers/can-having.js
- packages/reports/addon/templates/components/metric-selector.hbs
- packages/reports/addon/templates/components/report-builder.hbs
- packages/reports/app/helpers/can-having.js
- packages/reports/app/styles/navi-reports/components/metric-selector.less
- packages/reports/tests/integration/components/metric-selector-test.js
- packages/reports/tests/integration/helpers/can-having-test.js
Adds hooks to metric selector component to allow customizations
- Add can-having helper to decide if a metric is allowed to be filtered as a base metric, currently always returns true, allowed to be overridden in other systems
- Pass in route action for adding metrics with parameters so that downstream overrides can make use of it.
> Update: Add hooks to metric selector

- packages/core/app/styles/navi-core/visualizations/table.less
Found column reordering not firing event to reorder the table columns.  Bug in upstream library of heroku/ember-sortable ticket had a workaround.
- CSS as described in here https://github.com/heroku/ember-sortable/issues/234
> Fix: Column reordering firing events

- packages/core/app/styles/navi-core/variables/colors.less
- packages/dashboards/addon/components/dashboard-filters.js
- packages/dashboards/addon/templates/dashboards/index.hbs
- packages/dashboards/app/styles/navi-dashboards/components/dashboard-filters.less
- packages/dashboards/app/styles/navi-dashboards/components/navi-dashboard.less
- packages/dashboards/app/styles/navi-dashboards/components/navi-widget.less
- packages/dashboards/app/styles/navi-dashboards/views/navi-dashboards.less
- packages/dashboards/tests/dummy/app/styles/app.less
Styling update for dashboards to add some contrast. Apps using the latest version of Navi should update their styles to accommodate the background added here.
- Add light gray background to dashboards
- Use that same light gray consistently as our background throughout navi
- Make `+ New Dashboard` button consistent with the `+ New Report` button
- Add border to collapsed dashboard filters view
These changes don't seem to affect the print view.
> Dashboards style changes

- packages/dashboards/package-lock.json
- packages/dashboards/package.json
Ember-transition-helper is necessary for the new dashboard save behavior.
- Make ember-transition-helper a dependency instead of devDependency
> Update: Make ember-transition-helper a dependency

- packages/core/addon/components/navi-visualizations/table.js
- packages/data/addon/mirage/fixtures/bard-meta-metrics.js
- packages/data/addon/services/metric-parameter.js
- packages/data/tests/unit/services/metric-parameter-test.js
- packages/directory/tests/dummy/mirage/bard-lite/dimensions/displayCurrency.js
- packages/reports/addon/components/metric-config.js
- packages/reports/addon/templates/components/metric-config.hbs
- packages/reports/tests/dummy/mirage/bard-lite/dimensions/displayCurrency.js
- packages/reports/tests/integration/components/metric-config-test.js
Add support for enum parameterized metric types as outlined in fili RFC https://github.com/yahoo/fili/pull/618
- update parameterized-metric service to support enum metadata.
- make sure metric-config allows usage of enum metadata.
> Enum parameterized metric support

- packages/core/addon/models/bard-request/request.js
- packages/dashboards/addon/services/dashboard-data.js
- packages/dashboards/tests/acceptance/dashboard-filter-test.js
- packages/dashboards/tests/unit/services/dashboard-data-test.js
Bug where widgets do not get the values of the global dashboard filters added correctly to the request.
- request `addFilter` does not do well when the input is already a data fragment class, so added`addRawFilter` which copies filter values via 'rawValues' which works better in that case and does not break things that are currently using `addFilter`
- big acceptance test
> Fix: Fix dashboard filter values.

- packages/reports/addon/routes/reports/report.js
- packages/reports/addon/routes/reports/report/view.js
- packages/reports/addon/templates/reports/report.hbs
- packages/reports/tests/acceptance/navi-report-test.js
- packages/reports/tests/unit/routes/reports/report/view-test.js
Found bug that sometimes the Run button in reports won't run the report, even though you should.  This puts the report in an awkward state that's not easily correctable by the user.
See acceptance test for an example of this bad behavior.  changing a report, reverting, and changing it back to the same report breaks the run button functionality.
- Change behavior of run button so that it will always run the report when clicked.
> Fix: Report run button always runs when clicked

- packages/core/app/styles/navi-core/visualizations/table.less
Fixes issue where metric table headers are left aligned.
- clean-css, the minify module that ember uses, is dropping `-webkit-box-orient` property
As we already have a fallback for browsers that don't support line clamp we should just use that method instead.  We can optionally go with lineclamp once it's well supported among browsers and tools.
> Fix: Metric header alignment

- packages/dashboards/addon/services/dashboard-data.js
- packages/dashboards/tests/unit/services/dashboard-data-test.js
Removing the last value of a global dashboard filter would result in decorating widget requests with a filter with no values which would result in a bad request error.
- Don't apply filters that don't have at least one value
> Fix: Don't apply global dashboard filters that don't have values

- packages/core/addon/chart-builders/date-time.js
- packages/core/addon/components/navi-visualizations/line-chart.js
- packages/core/app/styles/navi-core/variables/colors.less
- packages/core/app/styles/navi-core/visualizations/line-chart.less
- packages/core/tests/unit/chart-builders/date-test.js
- packages/core/tests/unit/components/navi-visualizations/line-chart-test.js
- packages/reports/app/styles/navi-reports/components/report-view.less
Update to #415 
The x axis grid lines don't always align to useful positions and it becomes confusing when x axis labels closely but don't perfectly align with them. 
- Update grid lines to be on the y axis 
- Provide fixed x axis label positions for year chart grain
> Use y grid lines and provide better alignment for x axis labels

- packages/core/addon/components/power-select-search.js
- packages/core/addon/templates/components/power-select-search.hbs
- packages/core/app/components/power-select-search.js
- packages/core/app/styles/navi-core/components/index.less
- packages/core/app/styles/navi-core/components/power-select-search.less
- packages/core/tests/integration/components/power-select-search-test.js
- packages/dashboards/addon/templates/components/dashboard-dimension-selector.hbs
Poor indication that a search bar is available when adding a filter in dashboard filters
- Add custom search component to power-select with better indication
> Update: Add search placeholder to dashboard filter add component

- packages/dashboards/addon/templates/components/dashboard-action-list.hbs
- packages/directory/addon/templates/components/dir-asset-row-actions.hbs
- packages/directory/app/styles/navi-directory/components/dir-asset-row-actions.less
- packages/reports/addon/templates/components/common-actions/share.hbs
- packages/reports/addon/templates/components/navi-action-list.hbs
- packages/reports/addon/templates/components/navi-collection.hbs
- packages/reports/addon/templates/components/report-actions/multiple-format-export.hbs
- packages/reports/addon/templates/partials/report-actions.hbs
- packages/reports/app/styles/navi-reports/components/reports-index.less
This fixed a few issues with the tooltips:
❌ Current (second row is an unsaved report):
- **export** expands vertically
- **export** remains visible when not hovering
- **schedule** is never visible
- for unsaved reports, **share** is never visible and button cursor/color styles are not disabled
- overall vertical alignment
✅ Fixed:
❌ Current:
- line breaks in **export**
- **export** remains visible when not hovering
✅ Fixed:
- fix parent elements of some tooltips, manually set `targetId` attribute  when necessary.
- setting `delay=0` instead of only `openDelay=0` for `basic-dropdown-hover` seems to fix the issue of export remaining visible.
- css changes
I confirm that this contribution is made under an MIT license and that I have the authority necessary to make this contribution on …
> Fix: Tooltips in reports and directory

- packages/core/addon/components/navi-visualizations/bar-chart.js
- packages/core/addon/components/navi-visualizations/line-chart.js
- packages/core/addon/components/visualization-config/line-chart.js
Fixes issue where charts wouldn't work with old ember versions
- Make sure we use `get` until we drop 2.x support
> Fix: Support Ember 2.x

- packages/core/addon/adapters/base-json-adapter.js
ember-fetch no longer sends right content type for JSONAPI adapter see:
https://github.com/ember-cli/ember-fetch/issues/87
- explicitly set headers
> Fix: Content type not being sent.

- .travis.yml
Partially addresses #367 
Travis currently does not run tests on the webservice
Add a build job in travis for testing the webservice
- Switch travis language to java and manually install node
> Update: Build webservice for travis

- .travis.yml
Publish seems to be running under navi-webservice which means installs aren't happening correctly.
- Move navi-webservice to bottom so publish runs under navi-app
> Fix: Fix publish

- packages/dashboards/tests/acceptance/dashboards-test.js
- packages/reports/tests/acceptance/navi-report-test.js
Adds tests that asserts content-type
- add a couple spot check tests that checks to see if content-type headers ar what we expect
> Fix: Spot check content type headers

- packages/core/app/styles/navi-core/utils/colors.less
Resolves #443
The order we have graph colors to make sure we have enough contrast previously was from the hip.  The design language we are using actually has a specification for this. 
- Change color order for visualizations series according to our design language
> Update: Change series order colors

- package-lock.json
- packages/app/package-lock.json
- packages/core/addon/services/compression.js
- packages/core/app/services/compression.js
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/tests/unit/services/compression-test.js
- packages/dashboards/package-lock.json
- packages/data/package-lock.json
- packages/directory/package-lock.json
- packages/reports/addon/components/report-actions/multiple-format-export.js
- packages/reports/addon/routes/reports/new.js
- packages/reports/app/services/model-compression.js
- packages/reports/index.js
- packages/reports/package-lock.json
- packages/reports/package.json
- packages/reports/tests/acceptance/navi-report-test.js
Compression service is needed for compressing a fragment to support an upcoming feature.
Currently, we have a service for compressing ember data models specifically within the reports package.
- Move model-compression service to navi-core as just simply compression service
- Add generic compress and decompress functions to that service that works for more than models
- Use ember-auto-import to access the codec
> Update: Move model compression to a generic service

- packages/app/package-lock.json
- packages/core/package-lock.json
- packages/dashboards/addon/routes/dashboards/new.js
- packages/dashboards/tests/unit/routes/dashboards/dashboard/widgets/new-test.js
- packages/dashboards/tests/unit/routes/dashboards/new-test.js
- packages/reports/addon/routes/reports/new.js
- packages/reports/package-lock.json
Resolves #427 
Fix direct query param fetch from transition object deprecation
- Update the query param usage in route model hooks to use routeInfo or the transition.to object as required
NA
> Update: Fix direct query param fetch from transition object deprecation

- package-lock.json
- packages/app/package-lock.json
- packages/core/package-lock.json
- packages/data/package-lock.json
- packages/data/package.json
- packages/data/tests/unit/models/bard-dimension-test.js
- packages/reports/package-lock.json
Resolves #400 
Deprecation messages flood the console and internal registry references that shouldn't be there
- Update ember-ajax to fix some deprecations around ember.merge
- Remove use of `new` when instantiating ember objects
- Remove references to internal npm registry
> Fix: Deprecation warnings in navi-data and internal registry references in package-lock

- packages/dashboards/addon/services/dashboard-data.js
- packages/dashboards/tests/unit/services/dashboard-data-test.js
Global dashboard filters are not applying to each widget request anymore on an Ember 2.x app.
- Use `get` when accessing `rawValues` on filter application to ensure computed property is accessed correctly
- Test filter application using actual fragments rather than shallow objects
> Fix: Global dashboard filters not applying

- packages/dashboards/addon/routes/dashboards/new.js
- packages/dashboards/tests/unit/routes/dashboards/new-test.js
issue that users using ember 2.x are not able to create new dashboards
- `currentRoute` is a property on `router` in 3.x, not 2.x... use alternative method to get queryParams from transition object in model hooks
> Fix: Dashboard creation for ember 2.x

- packages/data/addon/builder/request.js
- packages/data/tests/unit/builder/request-test.js
The request builder class is missing an addSort method
- update the class and include three new methods
- addSort
- addSorts
- setSorts
NA
> Update: Add missing addSort methods to builder class

- packages/data/addon/adapters/dimensions/keg.js
- packages/data/addon/services/bard-dimensions.js
- packages/data/tests/unit/adapters/dimensions/keg-test.js
- packages/data/tests/unit/services/bard-dimensions-test.js
The current findById method will return a not resolved promise even if the dimension value is already loaded in keg
Add a `getById` method to `bard-dimensions` service and `keg` adapter
> New: Synchronous get method to bard-dimensions

- packages/app/README.md
- packages/app/app/templates/components/top-bar.hbs
- packages/app/config/environment.js
- packages/app/ember-cli-build.js
- packages/app/package.json
- scripts/ci-publish.sh
* Adds an environment variable `BUILD_NAVI_DEMO` for use when building the demo app to enable mirage
* Adds a shell script that can be run to update the demo app on the gh-pages branch. It will remove all the old javascript/css from the gh-pages branch and also add the short SHA to the HTML `<head>` to make it easier to see which version is running.
Once this is merged I can send a second PR updating the gh-pages demo app to the newest master (and update the gh-pages README.md instructions for rebuilding the docs).
> Make rebuilding demo simpler.

- packages/reports/addon/components/navi-table-select-item.js
- packages/reports/addon/templates/components/navi-table-select-item.hbs
- packages/reports/addon/templates/components/navi-table-select.hbs
- packages/reports/app/components/navi-table-select-item.js
- packages/reports/app/styles/navi-reports/components/navi-table-select.less
- packages/reports/tests/integration/components/navi-table-select-test.js
Tooltip of selected option of table selector doesn't hide when opening the dropdown.
Creating a separate component for the option items as well as passing it to `selectedItemComponent` seems to solve the issue.
> Fix: Tooltip of selected option of table selector doesn't hide

- packages/core/addon/mirage/fixtures/dashboard-widget.js
- packages/core/addon/mirage/fixtures/dashboard.js
- packages/dashboards/addon/templates/components/navi-dashboard.hbs
- packages/dashboards/tests/acceptance/add-widget-test.js
- packages/dashboards/tests/acceptance/dashboards-test.js
- packages/dashboards/tests/unit/routes/dashboards/dashboard/clone-test.js
Save button should not be visible when the user is not allowed to edit the dashboard.
Wrap the button in `if dashboard.canUserEdit`
> Fix: Save button should not be visible when user is not allowed to edit dashboard

- packages/reports/package-lock.json
- packages/reports/package.json
For #447 
consistent version of route-action-helper across the app
- update the version in reports to latest
NA
> consistent version of route-action-helper across the app

- packages/core/addon/components/visualization-config/wrapper.js
This is embarrassing since @cythrawll had a comment on this exactly in #457.
Nothing was broken but didn't notice the selector was missing.
Change `{ visualization: { type } } = this` to `get(this, 'visualization.type')`.
> Fix: Metric selector is missing in Ember 2.x

- packages/app/testem.js
- packages/core/testem.js
- packages/dashboards/addon/controllers/dashboards/dashboard/view.js
- packages/dashboards/addon/routes/dashboards/dashboard/view.js
- packages/dashboards/package-lock.json
- packages/dashboards/testem.js
- packages/data/testem.js
- packages/directory/testem.js
- packages/reports/testem.js
Ember 2.x fixes for dashboard filter query string support.
- setting ember array length to 0 doesn't clear it in 2.x because they aren't Native arrays yet and length is a computed prop. So clearing it via removeAt is the best way to truncate.
- need a default value for the filters queryParam so when removed during save it doesn't error out passing a null as string.
- removed disable-gpu in testem so local tests work again.
> Fix: Ember 2.x fixes for dashboard filters

- packages/reports/addon/templates/components/report-actions/multiple-format-export.hbs
-  Looks like delay was set to 0 so that it would open fast, but on firefox causes it to close too fast to interact with.  setting specific open and close delays as allowed by the component fixes this.
> Fix: Export goes away too fast on firefox

- packages/app/package-lock.json
- packages/app/package.json
- packages/core/addon/helpers/route-action.js
- packages/core/app/helpers/route-action.js
- packages/core/package-lock.json
- packages/dashboards/package-lock.json
- packages/dashboards/package.json
- packages/data/package-lock.json
- packages/reports/addon/helpers/update-report-action.js
- packages/reports/package-lock.json
- packages/reports/package.json
- packages/reports/tests/unit/helpers/update-report-action-test.js
Resolves #447, Resolves #451, Resolves #454, Resolves #456  
Route action helper doesn't work with 3.10
- Modified the route action helper from `ember-route-action-helper` addon to include the router service
- Referenced the new helper in places where we used the addon helper
- Cleaned up `ember-route-action-helper` addon dependency
NA
> Update: Add custom route action helper

- packages/app/package-lock.json
- packages/app/package.json
- packages/core/package.json
- packages/dashboards/package-lock.json
- packages/dashboards/package.json
- packages/directory/package-lock.json
- packages/directory/package.json
- packages/reports/package-lock.json
- packages/reports/package.json
Resolves #477 
Upgrade ember-cp-validation version in all packages
According to the [changelog](https://github.com/offirgolan/ember-cp-validations/blob/master/CHANGELOG.md#v400-beta9) should work with 3.10+
- Bump versions in package.json
NA
> Upgrade: Bump ember-cp-validation version in all packages

- packages/app/bower.json
- packages/app/package-lock.json
- packages/app/package.json
- packages/core/addon/components/navi-vis-c3-chart.js
- packages/core/addon/components/navi-visualizations/goal-gauge.js
- packages/core/addon/components/navi-visualizations/pie-chart.js
- packages/core/addon/initializers/inject-c3-enhancements.js
- packages/core/addon/templates/components/navi-visualizations/goal-gauge.hbs
- packages/core/addon/utils/chart.js
- packages/core/bower.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/tests/dummy/config/deprecation-workflow.js
- packages/core/tests/integration/components/navi-visualizations/pie-chart-test.js
- packages/core/tests/unit/initializers/inject-c3-enhancements-test.js
- packages/core/tests/unit/utils/chart-test.js
- packages/dashboards/bower.json
- packages/dashboards/package-lock.json
- packages/dashboards/package.json
- packages/dashboards/tests/acceptance/explore-widget-test.js
- packages/data/package-lock.json
- packages/directory/bower.json
- packages/directory/package-lock.json
- packages/directory/package.json
- packages/reports/bower.json
- packages/reports/package-lock.json
- packages/reports/package.json
Resolves #315 
Update ember-c3 which takes c3 and d3 out of bower.
- Updates ember c3, which not only gets rid of bower controlled c3 and d3, but allows us to use a newer version of the c3 lib. which means we can get rid of a lot of c3 enhancements that are no longer necessary. (though introduced a new bug that we had to work around for now with unloading the component)
- Translation calculation moved out of the d3 api, so had to create a utility.
- Goal gauge api changed a bit, so small changes to get the same behavior was needed.
- property name changes in ember-c3
> Ember c3 upgrade

- packages/reports/app/styles/navi-reports/components/navi-list-selector.less
- packages/reports/app/styles/navi-reports/components/report-builder.less
Style change to bring dashboards and reports together
- refactor reports cards to match dashboards
- improve padding around cards
- add padding to metric/dimension selector
Before:
After:
> Update: Match dashboard card style in builder

- .travis.yml
Sometimes when we push to travis, things fail (during tests/etc) and we can't see why (see #468) because we added `travis_wait` to some commands which take longer to run #57
Set lerna to [stream the logs](https://github.com/lerna/lerna/tree/master/commands/run#--stream) of running tests so that travis should no longer time out since no tests are run in parallel and now we can see the output of tests as they happen instead of getting a dump of all the results at once
> Stream tests logs in travis ci

- package-lock.json
- packages/app/config/environment.js
- packages/app/mirage/config.js
- packages/app/package-lock.json
- packages/core/package-lock.json
- packages/dashboards/package-lock.json
- packages/data/addon/mirage/routes/bard-lite.js
- packages/data/package-lock.json
- packages/directory/package-lock.json
- packages/reports/package-lock.json
The app would fail sometimes when trying to refresh/share it etc because it couldn't go directly to the url. The data returned was random every time (e.g. the same query), and only basic dimension filters could be applied
- Use `hash` locationType to get around url issues
- Set the seed for `faker` when returning a metric value based on the `[day, dimensions requested, current metric]`, so that we can change `filters`/`havings`/`interval` without changing the data
- Added support for more dimension filters `[in, notin, contains]`
- Added support for havings `[gt, gte, lt, lte, eq, neq, bet, nbet]`
| 15 days query | 14 days query |
|---------|---------|
| ![15 day results](https://user-images.githubusercontent.com/12093492/64433420-05053a80-d084-11e9-8b1c-d0ac229187e6.png)        | …
> Demo app cleanup

- package-lock.json
- package.json
- packages/app/.bowerrc
- packages/app/bower.json
- packages/app/package-lock.json
- packages/core/bower.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/dashboards/.bowerrc
- packages/dashboards/bower.json
- packages/dashboards/package-lock.json
- packages/dashboards/package.json
- packages/data/.bowerrc
- packages/data/package-lock.json
- packages/directory/.bowerrc
- packages/directory/bower.json
- packages/directory/package-lock.json
- packages/directory/package.json
- packages/reports/.bowerrc
- packages/reports/addon/components/navi-date-picker.js
- packages/reports/bower.json
- packages/reports/package-lock.json
- packages/reports/package.json
- packages/reports/tests/integration/components/navi-date-picker-test.js
- packages/reports/tests/integration/components/navi-date-range-picker-test.js
Resolves #314 #316 #318 
Removing rest of bower dependencies
- Replace bower dependencies with npm ones.
- Upgrade ember-cli-bootstrap-calendar. this came with a couple small api changes that needed adjusted.
- Set to breaking as users will have to remove these dependencies from their bower and package.json in order for the build work.
> Breaking: Remove Bower

- packages/app/tests/acceptance/print-views-test.js
- packages/dashboards/addon/router.js
- packages/dashboards/tests/acceptance/print-dashboard-test.js
- packages/reports/addon/router.js
- packages/reports/tests/acceptance/print-report-test.js
- Only dashboardPrintRoutes or reportPrintRoutes works, not both
https://github.com/yahoo/navi/blob/4696d9518b58cf40c25eb8577ed32b8944320a5f/packages/app/app/router.js#L19-L24
✅ : https://yahoo.github.io/navi/#/print/dashboards/1/view
❌ : https://yahoo.github.io/navi/#/print/reports/1/view
Fixup the route name so they don't override each other
> Fix: Print for dashboards/reports

- packages/app/config/environment.js
- packages/core/package-lock.json
- packages/core/package.json
- packages/dashboards/package-lock.json
- packages/dashboards/package.json
- packages/directory/package-lock.json
- packages/directory/package.json
- packages/reports/package-lock.json
- packages/reports/package.json
Resolves #22 
Remove `ember-tether`. No longer needed, `ember-tooltips@3.2.0` does not use ember-tether anymore.
- Remove `ember-tether` from package.json
NA
> Update: Remove ember-tether

- .travis.yml
Resolves #
builds failing because it can't find the tagged release because the clone depth is too shallow.
- https://docs.travis-ci.com/user/customizing-the-build/#git-clone-depth
> Fix: Clone depth

- .travis.yml
- scripts/gh-pages-publish.sh
Resolves #508 
- gh-pages was sometimes too slow to build and failed to push
- The gh-pages deploy got confused since both `origin` and `ssh-origin` have a `gh-pages` branch
- Both gh-pages and npm deploys can run in parallel [(but as separate builds)](https://docs.travis-ci.com/user/build-stages/#naming-your-jobs-within-build-stages) so let's do that
- Add [travis_wait](https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received) to gh-pages deploy
- Combine deploy steps so they should run in parallel
> Fixup gh-pages deploy

- package.json
- packages/dashboards/addon/controllers/dashboards/dashboard.js
- packages/dashboards/addon/controllers/dashboards/dashboard/widgets/widget.js
- packages/dashboards/addon/routes/dashboards/dashboard.js
- packages/dashboards/addon/routes/dashboards/dashboard/view.js
- packages/dashboards/addon/routes/dashboards/dashboard/widgets/widget.js
- packages/dashboards/addon/templates/dashboards/dashboard/widgets/widget.hbs
- packages/dashboards/app/controllers/dashboards/dashboard.js
- packages/dashboards/tests/acceptance/dashboard-filter-test.js
- packages/dashboards/tests/acceptance/dashboards-test.js
Dashboards often lose saved state when navigating to other routes
- Move the dashboard rollback to the parent route, that way subroutes like editing widgets can be done without losing dashboard changes.
- When navigating out of parent route, prompt the user if they have unsaved changes.
- Add filter query params to breadcrumb links in widgets
> Fix widget nav

- packages/reports/app/styles/navi-reports/components/report-builder.less
Issue in which table selector was rendering slightly outside it's container.
- put the right padding in place:
Before:
After:
> Fix: Table selector style

- packages/core/app/styles/navi-core/components/navi-button.less
Resolves #
Align NaviButton heights
- Align NaviButton heights
Before:
After:
> Fix: Align NaviButton heights

- packages/core/app/styles/navi-core/common/pills.less
- packages/reports/app/styles/navi-reports/vendor/ember-tag-input.less
The remove buttons for ember-power-select have different styles from our remove button
Copy ember-power-select, now they get darker on hover
Before:
After:
> Fix: Remove selector button color

- packages/core/addon/mirage/fixtures/delivery-rules.js
- packages/core/addon/models/delivery-rule.js
- packages/core/addon/models/fragments/scheduling-rules.js
- packages/core/app/models/fragments/scheduling-rules.js
- packages/core/tests/unit/models/delivery-rule-test.js
- packages/reports/addon/templates/components/common-actions/schedule.hbs
- packages/reports/tests/acceptance/schedule-modal-test.js
Resolves #532
We added the feature to only send reports via email if there is data. The schedule modal did not allow users to save a delivery rule if toggling the mustHaveData toggle was the only change.
Make schedulingRules an ember data model fragment so that the model passed to the schedule modal actions can actually listen for each rule in the schedulingRules object.
There's a corresponding change to the schedule.js and hbs common actions that depend on this navi-core update
-
> Fix: Allow save when mustHaveData is toggled (fixes #532)

- package-lock.json
- package.json
- packages/app/package.json
- packages/core/package.json
- packages/dashboards/package.json
- packages/data/package.json
- packages/directory/package.json
- packages/reports/package.json
Resolves #
Lock down navi dependency versions
- Set versions to `0.2.0` as that is what we are currently publishing
- Change navi dependencies from floating the minor to a static version
> Update: Lock down navi dependency versions

- packages/dashboards/addon/routes/dashboards/dashboard/view.js
Resolves #
Dashboard filters are not adding or updating.
It seems the `queryParams` property was moved in the `transition` object in the model hook. It now resides behind `to` and `from` rather than being a top level property.
- Access `to.queryParams`
> Fix: Dashboard Filters were not being updated by query params

- README.md
- packages/directory/addon/templates/components/dir-table-filter.hbs
- packages/directory/app/styles/navi-directory/components/dir-table-filter.less
Resolves #545 
The directory table filter only opens if you click on the text or dropdown
- Wrapping text in `<span>` to increase its width.
- Adding required css.
> directory table filter click issue

- packages/app/package-lock.json
- packages/core/addon/templates/components/number-format-dropdown.hbs
- packages/core/addon/templates/components/table-renderer-vertical-collection.hbs
- packages/core/addon/templates/components/visualization-config/table.hbs
- packages/core/package-lock.json
- packages/core/package.json
- packages/dashboards/addon/templates/components/dashboard-actions/add-widget.hbs
- packages/dashboards/addon/templates/components/report-actions/add-to-dashboard.hbs
- packages/dashboards/package-lock.json
- packages/dashboards/package.json
- packages/directory/addon/templates/components/dir-search-bar.hbs
- packages/directory/addon/templates/components/dir-sidebar.hbs
- packages/directory/package-lock.json
- packages/directory/package.json
- packages/reports/addon/templates/components/common-actions/schedule.hbs
- packages/reports/addon/templates/components/dropdown-date-picker.hbs
- packages/reports/addon/templates/components/navi-collection.hbs
- packages/reports/addon/templates/components/navi-list-selector.hbs
- packages/reports/addon/templates/components/power-select-bulk-import-trigger.hbs
- packages/reports/package-lock.json
- packages/reports/package.json
`mut` is a bit ambiguous in how it actually works under the hood. Read more about the issues with `mut` and how to live without it here https://www.pzuraq.com/on-mut-and-2-way-binding/
Essentially, the common usage of `mut` is not the behavior intended when it was created. The set helper is more explicit in what it is doing. 
- Use `ember-set-helper` to be more explicit about how we set values in our actions
> Update: Use ember-set-helper instead of the mut helper

- packages/webservice/LICENSE.md
- packages/webservice/README.md
- packages/webservice/app/src/main/kotlin/com/yahoo/navi/ws/app/Main.kt
- packages/webservice/build.gradle.kts
- packages/webservice/models/build.gradle.kts
Part of #367 
The webservice is 
- already building
adds ability to
- read version from top-level `package.json`
- push to [bintray](https://bintray.com/yahoo/maven/navi)/artifactory (for snapshots), but not set up for travis yet
---
I did not enable pushing from travis yet as we have to decide how versions will be managed
- should we publish a snapshot on every commit to master? (maybe yes)
- should we tie our version numbers to the rest of the packages? (currently yes)
- how will we create releases (not snapshots)? This depends on the previous question, I'm thinking manually bump versions in all the `package.json` files, reflect changes in changelog, submit a PR, merge, create a `git tag ...` for that release and have a workflow in travis for tags
There is currently a manually pushed …
> Webservice publish

- .gitignore
- packages/dashboards/addon/components/dashboard-filters-collapsed-filter.js
- packages/dashboards/addon/controllers/dashboards/dashboard/view.js
- packages/dashboards/addon/templates/components/dashboard-filters-collapsed-filter.hbs
- packages/dashboards/tests/acceptance/dashboard-filter-test.js
- packages/dashboards/tests/integration/components/dashboard-filters-collapsed-filter-test.js
- packages/dashboards/tests/integration/components/dashboard-filters-collapsed-test.js
Found dashboards break when you use a dimension with alternative primary key.
- Add support for looking up primaryKey field from metadata when filter is added.
- Change dimension display to pass in idField to formatter rather than filter field.
This will make it consistent with how we display dimension values in dropdowns and tag selectors.
> Fix: Dashboard filter alt primarykey support

- packages/directory/app/styles/navi-directory/components/dir-table-filter.less
Filter dropdown in directory in firefox is unclickable due to overlapping elements
- style change
> Fix: Directory filter unclickable in firefox

- .travis.yml
- packages/webservice/README.md
- packages/webservice/models/build.gradle.kts
- scripts/artifactory-publish.sh
Partially addresses #367 (still needs publishing for release versions)
The webservice should have some publishing set up so we don't have to manually deploy
Upload snapshot builds from my artifactory account (the environment keys are set in travis) on pushes to master
> Update: Publish to artifactory

- packages/data/addon/adapters/bard-facts.js
- packages/data/tests/dummy/config/environment.js
- packages/data/tests/unit/adapters/bard-facts-test.js
While we configure fact datasources in navi as an array, the adapter only uses the first defined.
This will allow the service or users of the service to pick which datasource they want to use.
- Add a host method that decides which host to use in the adapter.
- Use `dataSourceName` to choose which datasource to use when using the fact service.
> Update: Add support for multiple fact datasources.

- packages/dashboards/app/styles/navi-dashboards/components/navi-dashboard.less
- packages/reports/addon/templates/components/favorite-item.hbs
Resolves #
Added a star icon the same style as the edit icon
Favorite and editing icons had different styles, as a result, they were displayed in different ways.
-
> Resize favorite icon

- lerna.json
- package-lock.json
- package.json
- packages/core/addon/adapters/base-json-adapter.js
There is a bug using dashboards where the dashboard model is reloaded in the background after changes have been made which caused the changes to stay on the dashboard but caused the dashboard itself to have `hasDirtyAttributes === false`
Steps:
1. Load `/dashboards/2/view`
2. Modify filters (i.e. remove one)
3. Click the `Dashboards >` breadcrumb to navigate away
4. Use the browser back button to go back to the dashboard in a dirty state
At this point the dashboard with the dirty state is used for all the requests, but after the `routes/dashboards/dashboard` model refreshes in the background it appears to be in a clean state (so the save/revert buttons disappear)
By default when we find a record from the navi persistence store we should not reload it in the background
I confirm that this …
> Dashboard filters fixup

- packages/dashboards/tests/acceptance/explore-widget-test.js
- packages/reports/addon/templates/components/dimension-selector.hbs
- packages/reports/addon/templates/components/metric-config.hbs
- packages/reports/app/styles/navi-reports/components/grouped-list.less
- packages/reports/tests/acceptance/navi-report-test.js
- packages/reports/tests/integration/components/dimension-selector-test.js
Use the same class name for time grain checkboxes and dimension/metric labels - helpful for functional/acceptance tests.
Change `.grouped-list__item-checkbox-label` to `.grouped-list__item-label` and adjust css accordingly.
> Update: Use same class for checkbox and dimension/metric labels

- packages/reports/addon/templates/components/metric-config.hbs
- packages/reports/addon/templates/components/metric-selector.hbs
- packages/reports/app/styles/navi-reports/components/grouped-list.less
- packages/reports/tests/integration/components/metric-selector-test.js
Tiny styling change - align metric config trigger icon when there's no filter
> Update: Metric config alignment when no filter

- packages/reports/addon/templates/components/metric-config.hbs
- packages/reports/addon/templates/components/report-builder.hbs
Wrongly removed, was used by one of the apps. Also remove redundant `and`
> Fix: Revert removal of onAddMetricWithParameter

- packages/core/addon/components/table-renderer-vertical-collection.js
- packages/core/app/styles/navi-core/visualizations/table.less
Dashboard widgets stopped scrolling
- flex-basis is causing the table widget to be rendered in a overflowed hidden content.
- Add passive hints to table scroll events.
> Fix: Dashboard fixes

- packages/core/addon/models/bard-request/fragments/metric.js
- packages/data/addon/services/metric-parameter.js
- packages/data/tests/unit/services/metric-parameter-test.js
- packages/reports/addon/components/metric-config.js
- packages/reports/addon/components/navi-request-column-config/date-time.js
- packages/reports/addon/components/navi-request-column-config/dimension.js
- packages/reports/addon/components/navi-request-column-config/metric.js
- packages/reports/addon/components/navi-request-preview.js
- packages/reports/addon/consumers/request/metric.js
- packages/reports/addon/services/request-action-dispatcher.js
- packages/reports/addon/templates/components/navi-request-column-config/base.hbs
- packages/reports/addon/templates/components/navi-request-column-config/date-time.hbs
- packages/reports/addon/templates/components/navi-request-column-config/dimension.hbs
- packages/reports/addon/templates/components/navi-request-column-config/metric.hbs
- packages/reports/addon/templates/components/navi-request-preview.hbs
- packages/reports/app/components/navi-request-column-config/date-time.js
- packages/reports/app/components/navi-request-column-config/dimension.js
- packages/reports/app/components/navi-request-column-config/metric.js
- packages/reports/app/styles/navi-reports/components/navi-request-column-config.less
- packages/reports/tests/integration/components/navi-request-column-config/base-test.js
- packages/reports/tests/integration/components/navi-request-column-config/metric-test.js
- packages/reports/tests/integration/components/navi-request-preview-test.js
- packages/reports/tests/unit/consumers/request/metric-test.js
Metric column config component should be able to change the parameter for a given metric column.
- Add UPDATE_METRIC_PARAM method to metric fragment and request action consumer
- Move fetching of metric parameter values into the metric-parameter service
- Change `editingColumn` property to depend on index of the column instead of the `canonicalName` since that will change with param changes. This is a temporary solution until a rework in the request modeling is done.
- Add metric column config component with column name and metric parameter options
- Add components for dimension and date time as well that export the base column config component for now
I confirm that this contribution is made under an MIT license and that I have the authority necessary to make this contribution on behalf …
> Update: Move Metric Parameter Config to Request Preview Column Config

- packages/core/config/environment.js
- packages/core/tests/dummy/config/environment.js
- packages/dashboards/addon/services/dashboard-data.js
- packages/data/addon/services/navi-facts.js
- packages/data/app/services/bard-facts.js
- packages/data/app/services/navi-facts.js
- packages/data/tests/dummy/config/environment.js
- packages/data/tests/unit/services/navi-facts-test.js
- packages/reports/addon/components/common-actions/get-api.js
- packages/reports/addon/components/report-actions/export.js
- packages/reports/addon/components/report-actions/multiple-format-export.js
- packages/reports/addon/routes/reports/report/view.js
- packages/reports/config/environment.js
- packages/reports/tests/dummy/config/environment.js
- packages/reports/tests/integration/components/common-actions/get-api-test.js
- packages/reports/tests/integration/components/report-actions/export-test.js
- packages/reports/tests/integration/components/report-actions/multiple-format-export-test.js
**BREAKING CHANGE**
Update: Rename bard-facts service to navi-facts
- Make the adpater and serializer types configurable
- update environment config to contain adpater and serializer type like below
```js
dataSources: [{ name: 'dummy', uri: 'https://data.naviapp.io', type: 'bard-facts' }]
```
> Update: Rename bard-facts service to navi-facts

- packages/dashboards/tests/acceptance/dashboards-test.js
- packages/reports/addon/components/navi-collection.js
- packages/reports/addon/templates/components/navi-collection.hbs
- packages/reports/app/styles/navi-reports/components/navi-collection.less
- packages/reports/tests/acceptance/navi-report-test.js
- packages/reports/tests/integration/components/navi-collection-test.js
Partially addresses #40 
We want to use ember-power-select in place of ember-pick. Navi collection is the only place besides the date picker components that uses ember-pick. @kevinhinterlong is working on replacing the dropdown date picker so once that is complete, we will be able to remove ember-pick components from Navi.
- Replace the navi-collection table filter dropdown with ember-power-select
- Use Angle Brackets and Native Class syntax in the applicable files
Before: 
After: 
> Update: Replace navi-collection ember-pick filter selector with power select

- packages/reports/addon/components/filter-values/dimension-select.js
- packages/reports/addon/templates/components/filter-values/dimension-select.hbs
- packages/reports/package-lock.json
- packages/reports/tests/integration/components/filter-values/dimension-select-test.js
Resolves #344 
The dimension search had inconsistent behavior depending on the cardinality of the dimension being search
- for low cardinality dimensions, when searching, if you clicked an option the list would be recomputed and override the actual search results
- for high cardinality dimensions, when searching, if you clicked an option the list would stay filtered as expected
Only show dimension options if there is no search filter for low cardinality dimensions
> Update: Fix dimension select search behavior

- packages/reports/addon/components/filter-values/range-input.js
- packages/reports/addon/components/filter-values/value-input.js
- packages/reports/addon/templates/components/filter-values/range-input.hbs
- packages/reports/addon/templates/components/filter-values/value-input.hbs
- packages/reports/tests/integration/components/filter-values/range-input-test.js
- packages/reports/tests/integration/components/filter-values/value-input-test.js
Fix the input for metric filters.
For one-way binding we should use `<input>` with the `value` property and the `input` event, i.e.:
<strike>`<Input @value={{...}} @key-up={{action "setValue"}} />`</strike>
`<input value={{...}} {{on "input" (action this.setValue value="target.value")}}>`.
> Fix: Metric filter input

- packages/core/addon/adapters/base-json-adapter.js
- packages/core/tests/unit/adapters/base-json-adapter-test.js
The #619 PR removed the fetch adapter, which caused Cookies to not be included in requests and resulted in 401s when fetching resources
Send credentials to persistence api host
> Fix: Send credentials with requests

- packages/core/addon/models/line-chart.js
- packages/core/addon/models/pie-chart.js
- packages/core/addon/models/table.js
- packages/reports/addon/components/navi-request-preview.js
- packages/reports/addon/components/report-view.js
- packages/reports/addon/components/report-visualization.js
- packages/reports/addon/components/visualization-selector.js
- packages/reports/addon/consumers/request/dimension.js
- packages/reports/addon/consumers/request/metric.js
- packages/reports/addon/routes/reports/report/view.js
- packages/reports/addon/services/request-action-dispatcher.js
- packages/reports/addon/templates/components/navi-request-preview.hbs
- packages/reports/addon/templates/components/print-report-view.hbs
- packages/reports/addon/templates/components/report-view.hbs
- packages/reports/addon/templates/components/report-visualization.hbs
- packages/reports/addon/templates/components/visualization-selector.hbs
- packages/reports/app/components/visualization-selector.js
- packages/reports/app/styles/navi-reports/components/index.less
- packages/reports/app/styles/navi-reports/components/navi-request-preview.less
- packages/reports/app/styles/navi-reports/components/report-view.less
- packages/reports/app/styles/navi-reports/components/visualization-selector.less
- packages/reports/package.json
- packages/reports/tests/acceptance/report-visualizations-test.js
- packages/reports/tests/dummy/config/environment.js
- packages/reports/tests/integration/components/navi-request-preview-test.js
- packages/reports/tests/integration/components/visualization-selector-test.js
- packages/reports/tests/unit/consumers/request/dimension-test.js
- packages/reports/tests/unit/consumers/request/metric-test.js
- packages/reports/tests/unit/routes/reports/report/view-test.js
This PR introduces the new visualization selector for use with the request preview. It is hidden behind the `enableRequestPreview` feature flag, so if that flag is not present or false, then the old visualization toggle component will be present instead. 
- Add visualization-selector component and add it to report view with `enableRequestPreview` enabled
- Add Data label to the visualization panel, but without collapsibility functionality for now
- Add `currentView` property to `report-view` to handle which visualization to show
- Add Acceptance test for the request preview and visualization selector
> New Visualization Selector

- .travis.yml
Partially address #635 
Travis is now warning that our build config is invalid because we have both a `matrix` and `jobs` field, with the `matrix` field overwriting the jobs and stopping our builds from publishing
- Merge `matrix` and `jobs`
- Remove deprecated `sudo` field
> Update: Merge matrix and jobs config

- packages/reports/addon/components/navi-tag-input.js
When the user types `'with,comma' + Enter`, they get `['with', 'comma']` tags
- Don't split input when typing comma
- When the user types `'with,comma' + Enter`, they get `['with,comma']` tag
> Update: Only split on enter for multi-value-input

- packages/reports/app/styles/navi-reports/components/filter-collection.less
Resolves #638 
When people paste in a large number of filters and collapse the filters, they overflow into the report
- Hide overflowing items
Before:
After:
> Update: Better styling for many filters/values

- packages/core/app/styles/navi-core/common/dropdowns.less
- packages/core/app/styles/navi-core/variables/colors.less
- packages/reports/addon/components/dimension-bulk-import-simple.js
- packages/reports/addon/components/navi-tag-input.js
- packages/reports/addon/templates/components/dimension-bulk-import-simple.hbs
- packages/reports/addon/templates/components/dimension-bulk-import.hbs
- packages/reports/addon/templates/components/filter-values/multi-value-input.hbs
- packages/reports/addon/templates/components/navi-tag-input.hbs
- packages/reports/addon/templates/components/paginated-scroll-list.hbs
- packages/reports/app/components/dimension-bulk-import-simple.js
- packages/reports/app/styles/navi-reports/components/dimension-bulk-import-simple.less
- packages/reports/app/styles/navi-reports/components/dimension-bulk-import.less
- packages/reports/app/styles/navi-reports/components/index.less
- packages/reports/app/styles/navi-reports/components/show-all.less
- packages/reports/package-lock.json
- packages/reports/package.json
- packages/reports/tests/integration/components/common-actions/schedule-test.js
- packages/reports/tests/integration/components/dimension-bulk-import-simple-test.js
- packages/reports/tests/integration/components/dimension-bulk-import-test.js
- packages/reports/tests/integration/components/navi-tag-input-test.js
- packages/reports/tests/integration/components/paginated-scroll-list-test.js
- packages/reports/tests/integration/components/power-select-bulk-import-trigger-test.js
When we have a dimension with `storageStrategy === 'none'`, we fall back to multi-value-input which means we don't support dimension bulk import on (pasting a list of ids)
https://github.com/yahoo/navi/blob/842719c9c2b074aa1d04d6982cc1a0fca4c4e210/packages/reports/addon/components/filter-builders/dimension.js#L31-L34
- Add a simple dimension importer for multi-value-input
- detect if the users pastes something in with a `','`
- let user choose whole string value or split values into array
- clean up some styling on dimension importing
- fix key code from `118` to `188` for commas 👀 
Updated styles:
New simple importer:
> Bulk import paste for multi-value-input

- packages/data/addon/adapters/dimensions/keg.js
- packages/data/addon/services/bard-dimensions.js
- packages/data/tests/unit/adapters/dimensions/keg-test.js
The keg dimension adapter currently only supports passing in a single query in the given format (string list of values)
```js
{
field: 'id',
operator: 'in', // optional
values: 'my,list,of,values'
}
```
- Add support for multiple filters
- Directly pass an array of filter values instead of a string (supports values like `"Thing, Small"`)
```js
[
{
field: 'id',
values: ['my', 'list', 'of', 'values']
},
{
field: 'id',
values: ['my', 'list']
},
{
field: 'description',
values: ['yay']
}
]
```
We then merge all filters to be a keg-compatible filter
```js
{
id: ['my', 'list'],
description: ['yay']
}
```
> Update: Use andQueries in keg dimension adapter

- packages/data/addon/adapters/dimensions/bard.js
- packages/data/addon/services/bard-dimensions.js
- packages/data/tests/unit/adapters/dimensions/bard-test.js
The bard dimension adapter currently takes in
```js
{
field: 'id',
operation: 'in',
values: '1,2,3' // or [1, 2, 3]
}
```
When given
- `'1,2,3'` -> `filters=dim|id-in[1,2,3]`
- `[1, 2, 3]` -> `filters=dim|id-in[1],dim|id-in[2],dim|id-in[3]`
which is confusing since we think of multiple filter objects being ANDed together and filter values being ORed
Update the interface to take in an array of filters which will be ANDed together, and in a single filter the values are ORed
```js
[
{
field: 'id',
operation: 'in',
values: [1, 2, 3]
}
]
```
Now
- `[{values: '1,2,3'}]` -> `filters=dim|id-in[1,2,3]` *(same as before)*
-  `[{values: [1, 2, 3]}]` -> `filters=dim|id-in[1,2,3]`
-  `[{values: [1]}, {values: [2]}, {values: [3]}]` -> `filters=dim|id-in[1],dim|id-in[2],dim|id-in[3]`
I confirm that this …
> Update: Bard dimension adapter multiple filters

- packages/reports/addon/templates/components/navi-date-picker.hbs
- packages/reports/tests/integration/components/navi-date-picker-test.js
Using the month calendar required users to click the previous/next button `12` times (manually changing the center date one year ahead/behind)
Use power-calendar-selectors nav bar so that it will navigate one year at a time
> Update: Use power-calendar-selectors-nav for month

- packages/app/config/ember-intl.js
- packages/dashboards/tests/dummy/config/ember-intl.js
- packages/directory/tests/dummy/config/ember-intl.js
- packages/notifications/tests/dummy/config/ember-intl.js
- packages/reports/tests/dummy/config/ember-intl.js
`ember-intl` makes a _lot_ of noise during tests
stop it
> Update: Include ember-intl config in dummy apps

- packages/core/addon/components/number-format-dropdown.js
- packages/core/addon/templates/components/number-format-dropdown.hbs
- packages/core/tests/integration/components/number-format-dropdown-test.js
- packages/reports/tests/acceptance/navi-report-test.js
The table metric formatting is currently not working
1. Make a [new report](https://yahoo.github.io/navi/#/reports/new)
2. Add a metric 'coins'
3. Click Run
4. Click Edit Table
5. Click Number format dropdown
6. Click money format
Nothing happens, formatting still works on existing saved reports but new reports can no longer modify formatting
- Fix modifying format
- add tests
> Fix: Table metric formatting and add tests

- packages/core/addon/initializers/inject-c3-enhancements.js
If the tooltip gets too close to the right edge of the chart it will just stay snapped to the right side. This can be an issue because it will cover the data the user wants to look at
- Mirror the tooltip over the vertical bar to the left side of the data instead of blocking the right side of the data
> Update: Tooltip position behavior near edge

- packages/dashboards/app/styles/navi-dashboards/components/navi-widget.less
Resizing widgets would work horizontally, but resizing vertically would only expand the height and not shrink it
- Hide the overflow of the widget content so that when we shrink it and set `max-height` to `100%` that it will resize to the visible area instead of the actual height including the overflow
> Update: Hide chart overflow so it resizes to visible area

- packages/core/app/styles/navi-core/utils/mixins.less
- packages/reports/addon/components/dimension-bulk-import.js
- packages/reports/addon/components/power-select-bulk-import-trigger.js
- packages/reports/addon/templates/components/dimension-bulk-import.hbs
- packages/reports/addon/templates/components/power-select-bulk-import-trigger.hbs
- packages/reports/app/styles/navi-reports/components/dimension-bulk-import.less
- packages/reports/app/styles/navi-reports/components/filter-collection.less
- packages/reports/tests/integration/components/dimension-bulk-import-test.js
- packages/reports/tests/integration/components/power-select-bulk-import-trigger-test.js
During the dimension bulk import, if a user pasted a dimension id containing a comma ('yes, comma'), then it will.
- paste 'yes, comma'
- bring up bulk import
- show 2 invalid values
Add a search for the raw input in the bulk import
- paste 'yes, comma'
- bring up bulk import
- show 2 invalid values _and_ button allowing import of raw value
> Update: Add search for raw query input during import

- packages/dashboards/addon/routes/dashboards/dashboard/clone.js
- packages/dashboards/addon/routes/dashboards/dashboard/widgets/add.js
- packages/dashboards/tests/acceptance/dashboards-test.js
Resolves #674
Adding a new widget to a freshly cloned report redirects you to a dashboard with all but the first widget.
The bug appears when we set the new layout back to the dashboard, but this set was not necessary. 
- Remove set statement and add a corresponding acceptance test.
> Fixing dashboard widget bug with cloned dashboards

- packages/data/addon/adapters/dimensions/bard.js
- packages/data/addon/adapters/dimensions/keg.js
- packages/data/addon/models/metadata/dimension.js
- packages/data/addon/services/bard-dimensions.js
- packages/data/addon/services/bard-metadata.js
- packages/data/addon/services/keg.js
- packages/data/test-support/helpers/metadata-routes.js
- packages/data/tests/unit/adapters/dimensions/bard-test.js
- packages/data/tests/unit/adapters/dimensions/keg-test.js
- packages/data/tests/unit/services/bard-dimensions-test.js
- packages/reports/addon/components/filter-values/dimension-select.js
- packages/reports/tests/integration/components/filter-values/dimension-select-test.js
Resolves #667 
Adds multi datasource support to dimension metadata services
- Add namespace and datasource options to service methods.
- Add namespace to dimension value kegs
- Make sure options get passed down to keg lookups and bard/dimension adapters correctly
- wire up the new changes to dimension-select component so that dimension values can be searched.
- Make sure defaults are set up so all calls are backwards compatible.
> Update: Add datasource to dimension metadata

- packages/core/app/styles/navi-core/vendor/index.less
- packages/core/app/styles/navi-core/vendor/navi-ember-basic-dropdown.less
- packages/core/app/styles/navi-core/vendor/navi-ember-power-select.less
- packages/core/config/environment.js
- packages/core/tests/dummy/config/environment.js
- packages/reports/addon/components/filter-values/lookback-input.js
- packages/reports/addon/templates/components/filter-values/lookback-input.hbs
- packages/reports/config/environment.js
- packages/reports/tests/integration/components/filter-values/lookback-input-test.js
Fixes some of #550 
Using the new calendar picker, trying to select an interval like `P7D/current` will require you to click in the input box, clear what was in there, then type 7
- Add back functionality for presets such as `P7D/current`, `P30D/current`, so all you have to do is another click
Here it is side by side `Power Select Styles | Basic Dropdown Styles`
> New: Calendar presets

- .travis.yml
Resolves #508 (never resolved see #518)
The `gh-pages` deploy step is taking too long and has failed for the last several builds
- https://travis-ci.org/yahoo/navi/jobs/657423046
- https://travis-ci.org/yahoo/navi/jobs/657371616
- https://travis-ci.org/yahoo/navi/jobs/656024170
We tried using `travis_wait` before, but that didn't exist during deploy so I'm adding [travis-wait-improved](https://github.com/cisagov/travis-wait-improved) so that it no longer times out
> Update: Travis wait during gh-pages deploy

- .travis.yml
Resolves #692 
`before_deploy` didn't run, so `travis-wait-improved` didn't exist
install right before script
> Update: Before deploy didn't run

- .travis.yml
Travis still uses eol python by default
https://travis-ci.org/yahoo/navi/jobs/657499775#L282
> File "/home/travis/.local/lib/python2.7/site-packages/travis_wait_improved/sherpa.py", line 29
update that to 3.7.1 so travis-wait-improved will work
> Update: Python 3.7.1 instead of eol

- .travis.yml
Fix gh-pages deploy, I tested it on my own fork this time
> Update: Travis wait during deploy python 3.6

- .travis.yml
Running into out of memory during gh-pages deploy
Try setting `JOBS=1` like in ember-cli [.travis.yml blueprint](https://github.com/ember-cli/ember-cli/blob/b05d47e3d9fd60d075cdfcc5afdb57a03421f3e4/blueprints/addon/files/.travis.yml)
> Update: Jobs param for travis

- packages/data/addon/adapters/dimensions/keg.js
- packages/data/tests/unit/adapters/dimensions/keg-test.js
- packages/data/tests/unit/services/bard-dimensions-test.js
* Bad test setup wasn't loading dimension values correctly, so this behavior was missed
> Fix: Keg adapter getById namespace behavior

- packages/directory/addon/controllers/directory.js
- Query params are technically owned (managed) by the ember framework so we should be using set to notify them to update
- https://discuss.emberjs.com/t/query-params-tracked/17467/21
- https://github.com/emberjs/ember.js/issues/18715
^^ we saw the same issue above where putting `@tracked` made the page unusable
Revert them from `@tracked` to just plain properties
> Fix: Revert tracked query params

- packages/data/addon/models/metadata/metric.js
- packages/data/addon/serializers/bard-metadata.js
- packages/data/addon/services/bard-metadata.js
- packages/data/addon/services/keg.js
- packages/data/test-support/helpers/metadata-routes.js
- packages/data/tests/unit/models/metadata/dimension-test.js
- packages/data/tests/unit/models/metadata/metric-test.js
- packages/data/tests/unit/serializers/bard-metadata-test.js
- packages/data/tests/unit/services/bard-metadata-test.js
- packages/data/tests/unit/services/keg-test.js
Dimension Extended property started using `findById` instead of `fetchById` so that we wouldn't need to send a request if the dimension was already in the Keg. Because of the data from the `table?format=fullView` request on report builder load, there were records already in the Keg for each dimension and metric. Since `table?format=fullView` doesn't include all fields (such as `description`), this resulted in those extra fields never being fetched.
- Set a `partialData` property to true in all metrics and dimensions in `_normalizeTable` in `serializers/bard-metadata`
- `services/bard-metadata` `findById` will now only return an existing record in the keg if it does not contain that partialData flag
- Utilize `findById` in metric too so we aren't sending so many requests
- Return model …
> Fix: Fetch extended data properly

- packages/reports/addon/components/navi-list-selector.js
- packages/reports/addon/templates/components/navi-list-selector.hbs
- packages/reports/app/styles/navi-reports/components/grouped-list.less
- packages/reports/tests/integration/components/dimension-selector-test.js
- packages/reports/tests/integration/components/metric-config-test.js
- packages/reports/tests/integration/components/metric-selector-test.js
- packages/reports/tests/integration/components/navi-list-selector-test.js
Only if `enableRequestPreview` is turned on.
> Update: Remove `show selected` toggle from selectors (feature flagged)

- packages/notifications/addon/services/navi-notifications.js
- packages/notifications/tests/unit/navi-notifications-test.js
Notifications can't show a custom timeout duration
- allow passing in number to timeout
> New: Use number directly as timeout for notifications

- packages/app/app/styles/components/nav-bar.less
- packages/app/app/styles/views/landing.less
- packages/core/app/styles/navi-core/utils/mixins.less
- packages/core/app/styles/navi-core/variables/colors.less
- packages/dashboards/app/styles/navi-dashboards/common.less
- packages/dashboards/app/styles/navi-dashboards/components/add-to-dashboard-modal.less
- packages/directory/app/styles/navi-directory/components/dir-empty.less
- packages/reports/app/styles/navi-reports/common/breadcrumb.less
- packages/reports/app/styles/navi-reports/common/report-not-found.less
- packages/reports/app/styles/navi-reports/components/grouped-list.less
- packages/reports/app/styles/navi-reports/components/navi-column-config.less
- packages/reports/app/styles/navi-reports/components/navi-column-config/item.less
- packages/reports/app/styles/navi-reports/components/report-view.less
- packages/reports/app/styles/navi-reports/components/visualization-toggle.less
Use denali link and hover colors
Use denali link and hover colors based the repo's current css variables:
```css
--links-text-color: var(--color-brand-600);
--links-hover-text-color: var(--color-brand-700);
```
https://github.com/denali-design/denali-site/blob/96fee64f00208c3993fb9a5c240b42c4ae2c86d5/assets/denali.css#L177-L178
> Update: Use denali link and hover colors

- packages/reports/addon/components/navi-table-select.js
- packages/reports/addon/templates/components/navi-table-select.hbs
- packages/reports/tests/integration/components/navi-table-select-test.js
Resolves #
Add the searchField property to the navi-table-select so that you can specify which field you want to use for search when search is enabled.
- Add searchField property.
> Update: Specify search field for table selector

- packages/data/addon/adapters/bard-facts.js
- packages/data/addon/adapters/bard-metadata.js
- packages/data/addon/adapters/dimensions/bard.js
- packages/data/addon/adapters/dimensions/keg.js
- packages/data/addon/helpers/metric-format.js
- packages/data/addon/request-decorators/replace-null.js
- packages/data/addon/serializers/bard-facts.js
- packages/data/addon/serializers/bard-metadata.js
- packages/data/addon/serializers/dimensions/bard.js
- packages/data/addon/services/bard-dimensions.js
- packages/data/addon/services/bard-metadata.js
- packages/data/addon/services/metric-name.js
- packages/data/addon/services/metric-parameter.js
- packages/data/addon/services/navi-facts.js
- packages/data/addon/services/request-decorator.js
Most things work with native classes and it makes for a much better experience with more readable javascript/more tools being able to do autocompletion/etc
- Remove some ember get
- native classes in navi-data (minus `models/` since they are being remodeled)
> Native class navi data

- packages/reports/addon/templates/reports/report/invalid.hbs
- packages/reports/tests/acceptance/invalid-route-test.js
If you end up with an invalid report, you aren't able to see the column config
- Add it to the invalid route
> Update: Add column config to invalid route

- packages/core/app/styles/navi-core/components/navi-visualization-config/wrapper.less
Firefox visualization config has a tendency to overflow (stack config for long metric names)
- add max width to config wrapper
> Fix: VIsuailzation config firefox overflow bug

- packages/core/addon/mirage/fixtures/dashboard-widget.js
- packages/core/addon/mirage/fixtures/dashboard.js
- packages/core/addon/models/dashboard.js
- packages/core/addon/serializers/dashboard.js
- packages/core/tests/unit/models/dashboard-test.js
- packages/core/tests/unit/serializers/dashboard-test.js
- packages/dashboards/addon/components/dashboard-dimension-selector.js
- packages/dashboards/addon/controllers/dashboards/dashboard/view.js
- packages/dashboards/addon/routes/dashboards/dashboard/view.js
- packages/dashboards/addon/services/dashboard-data.js
- packages/dashboards/addon/templates/components/dashboard-dimension-selector.hbs
- packages/dashboards/tests/acceptance/add-widget-test.js
- packages/dashboards/tests/acceptance/dashboard-filter-test.js
- packages/dashboards/tests/acceptance/dashboards-test.js
- packages/dashboards/tests/acceptance/mutli-datasource-dashboards-test.js
- packages/dashboards/tests/dummy/app/routes/application.js
- packages/dashboards/tests/dummy/config/environment.js
- packages/dashboards/tests/dummy/mirage/config.js
- packages/dashboards/tests/integration/components/dashboard-dimension-selector-test.js
- packages/dashboards/tests/unit/controllers/dashboards/dashboard/view-test.js
- packages/dashboards/tests/unit/routes/dashboards/dashboard/clone-test.js
- packages/dashboards/tests/unit/services/dashboard-data-test.js
Resolves #666 also known as the issue of the beast
Adds Multi datasource support to dashboards
- Update fetch to pass dataSource of widget to adapter
- Update global filters to specify the dataSource and carry it around
- Make sure dashboard serializer and cloning includes dataSource in dimension name
- Global dashboard dashboard dimension selector specifies dataSource in tooltip and resolves conflicting categories.
> Update: Add multi-datasource dashboard support

- packages/app/README.md
Noticed a missing step when someone was trying to setup navi.
Navi package versions were set to 0.2.0 when no such version exists in npm since we are still releasing alpha versions of 0.2.0.
- Update README
> Update: Add missing step to README

- packages/data/addon/utils/metric.js
- packages/data/tests/unit/adapters/bard-facts-test.js
- packages/data/tests/unit/utils/metric-test.js
We are serializing parameter null values which breaks the fili contract
- filter out null valued parameters.
> Fix: Dont serialize metric params with null values

- packages/reports/addon/components/report-view.js
- packages/reports/addon/controllers/reports/report.js
- packages/reports/addon/templates/components/report-builder.hbs
- packages/reports/addon/templates/components/report-view.hbs
- packages/reports/addon/templates/reports/report.hbs
- packages/reports/addon/templates/reports/report/edit.hbs
- packages/reports/addon/templates/reports/report/error.hbs
- packages/reports/addon/templates/reports/report/invalid.hbs
- packages/reports/app/styles/navi-reports/components/navi-column-config.less
- packages/reports/tests/acceptance/column-config-test.js
- packages/reports/tests/integration/components/report-view-test.js
While playing around with the column config, if you move things around/open/close/etc those changes are destroyed every time you transition to a new report route such as when running a report/etc
Lift up the column config to the report route level so that it persists between transitions
> Update: Lift column config to report route

- packages/data/addon/mirage/fixtures/bard-meta-metrics.js
- packages/data/addon/services/metric-parameter.js
- packages/data/tests/unit/services/metric-parameter-test.js
- packages/reports/addon/components/navi-column-config/metric.js
- packages/reports/addon/templates/components/navi-column-config/metric.hbs
- packages/reports/tests/integration/components/navi-column-config/metric-test.js
The current column config only allows you to configure the first parameter for a metric
Loop through all the metrics so all of them can be configured
> Fix: Metric config for multiple and null values

- packages/reports/app/styles/navi-reports/components/navi-column-config/item.less
- packages/reports/app/styles/navi-reports/components/report-view.less
The column config open/close button pushes the visualization over a lot and the columns can be hard to read sometimes
- Make column config take up less space
- Ellipse column text at 2 lines for supporting browsers
> Update: Column config styles

- packages/reports/addon/components/filter-builders/date-time.js
- packages/reports/addon/components/filter-values/advanced-interval-input.js
- packages/reports/addon/components/filter-values/base-interval-component.js
- packages/reports/addon/templates/components/filter-values/advanced-interval-input.hbs
- packages/reports/tests/acceptance/report-test.js
- packages/reports/tests/integration/components/filter-collection-test.js
- packages/reports/tests/integration/components/filter-values/advanced-interval-input-test.js
- packages/reports/tests/integration/components/filter-values/current-period-test.js
- packages/reports/tests/integration/components/filter-values/date-range-test.js
- packages/reports/tests/integration/components/filter-values/lookback-input-test.js
- packages/reports/tests/integration/components/filter-values/since-input-test.js
The advanced date picker currently adds an extra period to the end of the interval, but this is confusing as it's not what the user typed in
Update the advanced date picker so that it does not modify the date from user input
> Fix: Advanced date picker

- packages/data/addon/models/metadata/dimension.js
- packages/data/addon/serializers/bard-metadata.js
- packages/data/addon/services/bard-dimensions.js
- packages/data/addon/utils/enums/cardinality-sizes.js
- packages/data/app/utils/enums/cardinality-sizes.js
- packages/reports/addon/components/filter-values/dimension-select.js
Expose cardinality size export outside of navi-data addon
- move to enums file
> Update: Move where cardinality sizes are exported from

- packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/ReportTest.kt
- packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/RequestV2Test.kt
- packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/UserTest.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/enums/ColumnType.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/Request.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/RequestV1.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/RequestV2.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/request/v2/Column.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/request/v2/Filter.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/request/v2/Sort.kt
Resolves #746 
Webservice change to support storing Request V2 while still supporting v1
- Add jackson magic to serialize/deserialize request objects in either v1 or 2.0 
- Note that there are some minor differences than Java implementations based on Kotlin data class limitations.
> Request v2: Navi-WS Support

- packages/data/.eslintrc.js
- packages/data/addon/adapters/bard-metadata.js
- packages/data/addon/adapters/dimensions/bard.js
- packages/data/addon/adapters/dimensions/keg.js
- packages/data/addon/helpers/metric-format.js
- packages/data/addon/mirage/fixtures/bard-meta-metrics.js
- packages/data/addon/mirage/routes/bard-lite.js
- packages/data/addon/request-decorators/replace-null.ts
- packages/data/addon/services/metric-parameter.js
- packages/data/addon/services/request-decorator.ts
- packages/data/addon/utils/metric.js
- packages/data/addon/utils/search.js
- packages/data/config/environment.d.ts
- packages/data/package-lock.json
- packages/data/package.json
- packages/data/test-support/helpers/metadata-routes.js
- packages/data/tests/dummy/app/config/environment.d.ts
- packages/data/tests/dummy/app/router.js
- packages/data/tests/test-helper.ts
- packages/data/tests/unit/adapters/bard-facts-test.js
- packages/data/tests/unit/adapters/dimensions/bard-test.js
- packages/data/tests/unit/adapters/dimensions/keg-test.js
- packages/data/tests/unit/models/metadata/dimension-test.js
- packages/data/tests/unit/models/metadata/function-argument-test.js
- packages/data/tests/unit/models/navi-facts-model-test.js
- packages/data/tests/unit/services/bard-dimensions-test.js
- packages/data/tests/unit/services/metric-parameter-test.js
- packages/data/tsconfig.json
- packages/data/types/global.d.ts
- packages/directory/package.json
Allow for using typescript in `navi-data`
- lots of small file changes to satisfy stricter prettier/eslint stuff
- Set allowJs to false so that it runs like ember ts:precompile (this just means you have to add `//@ts-ignore` to import js files)
The first commit should be a pretty good skeleton for converting other packages
> Update: Install typescript for navi data

- packages/data/addon/adapters/bard-facts-v2.ts
- packages/data/addon/request-decorators/replace-null.ts
- packages/data/app/adapters/bard-facts-v2.js
- packages/data/tests/unit/adapters/bard-facts-v2-test.js
The request V2 shape will not work with the existing bard-facts adapter.
- Create bard-facts-v2 adapter to send requests to fili with the new v2 request
> New: Bard Facts Adapter for Request V2

- packages/data/addon/gql/fragments/table.js
- packages/data/addon/gql/schema.js
- packages/data/addon/models/metadata/column.ts
- packages/data/addon/models/metadata/dimension.ts
- packages/data/addon/models/metadata/metric.ts
- packages/data/addon/models/metadata/table.ts
- packages/data/addon/models/metadata/time-dimension.ts
- packages/data/addon/serializers/elide-metadata.ts
- packages/data/tests/dummy/mirage/factories/dimension.js
- packages/data/tests/dummy/mirage/factories/metric.js
- packages/data/tests/unit/adapters/elide-metadata-test.js
- packages/data/tests/unit/serializers/elide-metadata-test.js
We discussed how we could make the types involved in loading metadata clearer.
- Add a metadata payload interface and metadata interface for each metadata model that's serialized currently
> Update: Better interface typing around metadata models

- packages/data/addon/adapters/bard-facts-v2.ts
- packages/data/addon/utils/adapter.ts
- packages/data/addon/utils/metric.ts
- packages/data/types/global.d.ts
Resolves #
Predeploy step broke on `ember ts:precompile` because of imports from modules with no types defined. Could've fixed it by using `// @ts-ignore` but these will need to be typescript at some point anyway.
- Typescript metric and adapter utils in navi-data
> Fix: Typescript some data utils to fix npm publish

- packages/search/app/styles/navi-search/components/navi-search-bar.less
Resolves #
Show scrollbar instead of extending the size of the search result pane. Also, add a border around the search bar.
-
> Update: Search results show scrollbar

- packages/search/addon/components/navi-search-bar.hbs
- packages/search/addon/components/navi-search-bar.js
- packages/search/addon/services/navi-search-provider.js
- packages/search/addon/services/navi-search/navi-asset-search-provider.js
- packages/search/addon/services/navi-search/navi-definition-search-provider.js
- packages/search/app/styles/navi-search/components/navi-search-bar.less
Resolves #
Performance improvements for navi-search. 
- Use restartableTask instead of keepLatestTask.
- Debounce queries from search bar.
- Use task's lastSuccessful value instead of keeping an extra tracked property.
- Update styles: make search result pane extend a little longer (after testing w/ Spotlight) and update z-index so search results appear over some page elements.
> Update: Performance improvements for navi-search

- packages/reports/addon/templates/components/grouped-list.hbs
- packages/reports/addon/templates/components/metric-config.hbs
- packages/reports/app/styles/navi-reports/components/grouped-list.less
- packages/reports/app/styles/navi-reports/components/metric-config.less
Long titles in dimension and metric selectors are not aligned well.
- Add flex to categories to align title with arrow icon 
- For items, toggle visibility instead of display of ? icon to avoid line break on hover
**Before:**
**After:**
> Update: Grouped list styling

- packages/search/addon/components/navi-search-result/asset.hbs
- packages/search/addon/components/navi-search-result/asset.js
- packages/search/addon/components/navi-search-result/base.ts
- packages/search/addon/components/navi-search-result/definition.hbs
- packages/search/addon/components/navi-search-result/definition.ts
- packages/search/addon/services/navi-base-search-provider.js
- packages/search/addon/services/navi-search/navi-definition-search-provider.js
- packages/search/app/styles/navi-search/common/common.less
- packages/search/app/styles/navi-search/components/navi-definition-search-result.less
- packages/search/package-lock.json
- packages/search/package.json
- packages/search/tests/integration/components/navi-search-result/asset-test.js
- packages/search/tests/integration/components/navi-search-result/definition-test.js
Resolves #
Show more results support for display components
- Limit results returned by the provider
- Show more button for when you have a lot of results
- Only show definition result if it has a description property
- Typescript updates
> Show more results support for display components

- packages/dashboards/addon/templates/dashboards/dashboard/widgets/widget.hbs
- packages/reports/addon/components/navi-column-config.js
- packages/reports/addon/components/navi-column-config/item.js
- packages/reports/addon/controllers/reports/report.js
- packages/reports/addon/routes/reports/report.js
- packages/reports/addon/templates/components/dimension-selector.hbs
- packages/reports/addon/templates/components/metric-selector.hbs
- packages/reports/addon/templates/components/navi-column-config.hbs
- packages/reports/addon/templates/components/navi-column-config/item.hbs
- packages/reports/addon/templates/components/report-builder.hbs
- packages/reports/addon/templates/reports/report.hbs
- packages/reports/app/styles/navi-reports/components/navi-column-config.less
- packages/reports/app/styles/navi-reports/components/navi-column-config/item.less
- packages/reports/app/styles/navi-reports/components/report-builder.less
- packages/reports/tests/acceptance/column-config-test.js
- packages/reports/tests/integration/components/navi-column-config-test.js
When adding or cloning a column, open and highlight the item and scroll to it.
- Add a controller property `lastAddedColumn` that will save last added column type and id
- Reset it when removing a column, reverting unsaved changes or navigating away
- the `navi-column-config` component will pass a `isLastAdded` argument to each item
- if `true`, the item will be scrolled to, have a highlighted background and config will be open
- had to switch back to a regular `each` loop since `animated-each` causes scrolling to flicker. Instead, added `animated-if` for fade and collapse effect when removing a column
- disable removing a date time column when no `all` time grain in metadata
I confirm that this contribution is made under an MIT license and that I have the authority necessary to make this …
> Update: Column config - scroll to and highlight most recently added column

- packages/data/addon/adapters/bard-facts-v2.ts
- packages/data/addon/adapters/elide-metadata.ts
- packages/data/addon/gql/fragments/table.js
- packages/data/addon/serializers/elide-metadata.ts
- packages/data/addon/services/elide-metadata.ts
- packages/data/app/services/elide-metadata.js
- packages/data/package.json
- packages/data/tests/dummy/mirage/factories/time-dimension.js
- packages/data/tests/dummy/mirage/scenarios/graphql-blockhead.js
- packages/data/tests/dummy/mirage/scenarios/graphql.js
- packages/data/tests/unit/adapters/elide-metadata-test.js
- packages/data/tests/unit/services/elide-metadata-test.ts
- packages/data/types/global.d.ts
Resolves #770 
We needed a service similar to bard-metadata in order to leverage our new adapter and serializer for graphql. 
The new service is intentionally not extending from the bard-metadata service even though they share a lot of similar functionality right now. In the future, there will be the opportunity for optimizations using the elide-metadata service that will change the implementation to be pretty different from the bard metadata flow.
- Create Elide-metadata-service
- Typescript Elide-metadata adapter
- Add time dimensions to the graphql table query
> New: Elide-metadata-service to support fetching metadata through graphql

- packages/search/addon/components/navi-search-bar.js
- packages/search/addon/services/navi-search-provider.js
- packages/search/addon/services/navi-search/navi-asset-search-provider.js
- packages/search/addon/services/navi-search/navi-definition-search-provider.js
- packages/search/package.json
- packages/search/tests/dummy/app/services/navi-search/navi-sample-search-provider.js
Resolves #
Deprecate ember concurrency decorators from navi-search in favor of native ember concurrency syntax
-
> Update: Deprecate ember concurrency decorators

- packages/core/addon/models/bard-request-v2/fragments/base.js
- packages/core/addon/models/bard-request-v2/fragments/column.js
- packages/core/addon/models/bard-request-v2/fragments/filter.js
- packages/core/addon/models/bard-request-v2/fragments/sort.js
- packages/core/addon/models/bard-request-v2/request.js
- packages/core/addon/services/fragment-factory.ts
- packages/core/app/services/fragment-factory.js
- packages/core/tests/dummy/app/models/fragments-v2-mock.js
- packages/core/tests/unit/models/bard-request-v2/fragments/column-test.js
- packages/core/tests/unit/models/bard-request-v2/fragments/filter-test.js
- packages/core/tests/unit/models/bard-request-v2/fragments/sort-test.js
- packages/core/tests/unit/models/bard-request-v2/request-test.js
- packages/core/tests/unit/services/fragment-factory-test.js
- packages/core/tsconfig.json
- packages/core/types/@ember/service/index.d.ts
Resolves #751 
Current approach to metadata is to replace the field component of a fragment with the metadata at transform time, this has been a headache.
- Field has different shape depending on serialized or unserialized which is confusing
- transforms don't give access to all information needed to get ahold of the metadata so work arounds are needed. 
Request V2 will have the following approach to metadata
- Metadata moved onto a lazy fetched property on the base fragment.
- lazy based fetch will fetch from metadata service looking up info from the parent request v2 model if available.
- Factories are provided to attach meta to newly created fragments that are not part of a request yet. 
Note: this PR contains typescript rebase from master.
I confirm that this contribution is made …
> Fragment meta

- packages/search/addon/components/navi-search-bar.hbs
- packages/search/tests/integration/components/navi-search-bar-test.js
Resolves #
Add focusOut hook on navi-search
- Add a hook for when the search bar is out of focus. Can be used to say collapse a nav bar when the search loses focus
- Render search results under the navi-search div instead of the root of the body.
> Update: Add focusOut hook on navi-search

- packages/core/addon/templates/components/power-select-search.hbs
- packages/reports/addon/templates/components/power-select-bulk-import-trigger.hbs
- packages/reports/addon/templates/components/power-select-search-trigger.hbs
Having some issues with Chrome trying to be helpful and trying to autocomplete on our multiselect
- [autocomplete="new-password"](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#Preventing_autofilling_with_autocompletenew-password) to really suggest that the browser does not try to autocomplete
> Update: Use autocomplete="new-password"

- packages/reports/addon/components/navi-column-config.js
- packages/reports/addon/templates/components/navi-column-config/item.hbs
- packages/reports/tests/acceptance/column-config-test.js
- packages/reports/tests/integration/components/navi-column-config-test.js
With the new experience, we should show users how they can configure metrics/time grain by automatically opening the date time
- Show the date time as being added when creating a new report
> Update: Open Date Time on new report

- packages/reports/addon/consumers/request/sort.js
- packages/reports/tests/acceptance/column-config-test.js
When removing a metric in the new column config, any matching sorts are not removed, causing Fili API errors
- Add corresponding consumer for REMOVE_METRIC_FRAGMENT in sort consumer.
- When params change, remove all sorts with the base metric to reset the sorts for that metric.
> Fix: Remove sort when matching metric is removed

- .travis.yml
- packages/core/app/styles/navi-core/variables/animations.less
- packages/reports/addon/components/dimension-selector.js
- packages/reports/addon/components/metric-config.js
- packages/reports/addon/components/metric-selector.js
- packages/reports/addon/templates/components/dimension-selector.hbs
- packages/reports/addon/templates/components/metric-config.hbs
- packages/reports/addon/templates/components/metric-selector.hbs
- packages/reports/app/styles/navi-reports/components/grouped-list.less
- packages/reports/app/styles/navi-reports/components/navi-column-config/item.less
- packages/reports/tests/acceptance/column-config-test.js
- packages/search/addon/components/navi-search-bar.hbs
- packages/search/addon/components/navi-search-result/asset.hbs
- packages/search/addon/components/navi-search-result/definition.hbs
- packages/search/tests/integration/components/navi-search-bar-test.js
Users find it hard to tell when they've added a metric or dimension in the new column config, so they end up adding the same metric/dimension multiple times.
- Highlight a clicked metric/dimension so that users have some feedback that something has happened
- Throttle clicks on metrics/dimensions to prevent unintentional additions/deletions
It doesn't show in the gif, but selected metrics/dimensions still have a light `@denali-brand-100` background color.
> Update: Throttle and highlight clicks on metric/dimension selections

- packages/data/addon/services/navi-metadata-apollo.js
- packages/data/tests/dummy/mirage/config.js
- packages/data/tests/unit/adapters/elide-metadata-test.js
- packages/data/tests/unit/services/navi-metadata-apollo-test.js
`v1` in the URI prefix is not needed for GraphQL requests
- Remove v1 from URI prefix for GraphQL
> Update: GraphQL Request URI Prefix

- packages/data/addon/gql/fragments/table.ts
- packages/data/addon/gql/schema.js
Resolves #
Elide metadata schema has objects for supported grains of a time dimension
- Make supportedGrains into a connection to TimeDimensionGrain nodes
> Update: Time Dimension's supported grains should be objects

- packages/data/addon/mirage/fixtures/bard-meta-metrics.js
- packages/data/addon/serializers/metadata/metric-function.js
- packages/data/tests/unit/serializers/bard-metadata-test.js
- packages/data/tests/unit/serializers/metadata/metric-function-test.js
- packages/reports/addon/components/navi-column-config/metric.js
- packages/reports/addon/templates/components/metric-config.hbs
- packages/reports/addon/templates/components/navi-column-config/metric.hbs
- packages/reports/tests/integration/components/navi-column-config/metric-test.js
- also allow param arguments with name over description.
Allows description to be a property of metric function parameters that can be used as tooltip helpers.
Allows the shape of metric function parameter arguments to be `{id, name}` as well as support `{id, description}`
- Add description property to metric function parameters.
- If said description exists show tooltip help next to parameter in metric config
- Add support to use `name` rather than `description` if the values have a `name` param. 
FUTURE TODO: Normalize all function arguments to `{name, id, description}` shape. even if arguments come from external sources like a dimension.
I confirm that this contribution is made under an MIT license and that I have the authority necessary to make this contribution on behalf of its …
> Update: Add tootlip support for metric parameters.

- packages/data/addon/models/metadata/time-dimension.ts
- packages/data/addon/serializers/elide-metadata.ts
- packages/data/tests/unit/serializers/elide-metadata-test.js
Supported Grains need to be serialized as objects into the time dimension model
- Normalize support grains connection into objects
> Update: SupportedGrains serialize as objects

- packages/core/addon/helpers/get-shallow.ts
- packages/core/app/helpers/get-shallow.js
- packages/core/tests/integration/helpers/get-shallow-test.ts
- packages/reports/addon/templates/components/dimension-selector.hbs
- packages/reports/addon/templates/components/metric-config.hbs
- packages/reports/addon/templates/components/metric-selector.hbs
Elide is going to use a convention of `` `${table.id}.${columnId}` `` for its column ids. This causes problems when we try to use the basic `get` helper that is built-in to Ember since it sees that `.` in the middle of the id as a nested access indicator. 
- Add a `get-shallow` helper that will allow us to use column ids as keys
> Update: Use get-shallow when using column id as key

- packages/reports/addon/components/metric-config.js
- packages/reports/addon/templates/components/metric-config.hbs
- packages/reports/addon/templates/components/metric-selector.hbs
- packages/reports/tests/acceptance/column-config-test.js
- packages/reports/tests/acceptance/metric-parameters-test.js
Disable metric config gear menu when request preview is on: It obstructs column preview and doesn't give enough functionality
- Removes gear icon when the enableRequestPreview flag is on
> Fix: Enable Request Preview disables metric-config

- packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/RequestV2Test.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/RequestV2.kt
In request 2.0, sort refers to a collection
- pluralize sorts to clarify it is a collection
> Update: Pluralize sorts in request 2.0

- packages/reports/addon/controllers/reports/report/view.js
- packages/reports/addon/routes/reports/report.js
- packages/reports/tests/acceptance/report-test.js
- packages/reports/tests/unit/routes/reports/report-test.js
There's no need to rerun the request after reordering table columns.
Reordering metric columns changes the order of the metrics fragment array.
Change `hasRequestRun` method to return true if the only diff is the order of metrics, otherwise false.
> Update: Don't rerun request after reordering table columns

- packages/core/addon/components/navi-visualizations/bar-chart.js
Bar chart is borked
- Add line-chart-widget to classnames of bar chart since it extends from line-chart
> Fix: Bar-chart missing class name

- packages/data/addon/utils/metric.ts
- packages/data/tests/unit/utils/metric-test.js
Quick fix to handle some extra spacing in metric parameters list
> Fix: Gracefully handle spaces after comma

- packages/core/addon/transforms/base-metadata-transform.js
- packages/core/addon/transforms/dimension.js
- packages/core/tests/unit/transforms/dimension-test.js
- packages/core/tests/unit/transforms/metric-test.js
Resolves #
Reports saved with a metric or dimension with an id like `tableA.metric1` would not be successfully deserialized in the metadata transform due to the `.` character in the id.
- Extract the namespace from before only the first `.` in the id.
> Update: Support deserializing metadata objects from ids that contain "."

- packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/RequestV2Test.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/enums/ColumnType.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/request/v2/Filter.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/request/v2/Sort.kt
In request 2.0 we want to have a distinguishable type for every column/filter/sort fragment so that they can more easily be looked up have correct behaviors
- add `type` to all fragments in 2.0
> Update: Add type to all 2.0 fragments

- packages/data/addon/adapters/bard-facts-v2.ts
- packages/data/addon/adapters/bard-facts.ts
- packages/data/addon/adapters/fact-interface.ts
- packages/data/addon/models/navi-facts.ts
- packages/data/addon/serializers/bard-facts.ts
- packages/data/addon/serializers/fact-interface.ts
- packages/data/addon/services/navi-facts.ts
- packages/data/package-lock.json
- packages/data/package.json
- packages/data/tests/unit/adapters/bard-facts-v2-test.js
This PR adds fact interfaces for the adapter and serializer. This is in preparation of the elide set. I took a stab at organizing some types and interfaces. I am open to suggestions, but I don't think we need to get it perfect in the short term. Most likely we will see the patterns as we move forward, plus it is pretty easy to move them around (VSCode is pretty good at that).
- Bumps ember-cli-typescript to  3.1.4
- Adds fact adapter and serializer interfaces
- JS -> TS some files
- Move Request V2 types
> Fact data interfaces

- .travis.yml
Currently, the build is breaking:
> $ pyenv global 3.6
> pyenv: version `3.6' not installed
> The command "pyenv global 3.6" failed and exited with 1 during .
https://travis-ci.com/github/yahoo/navi/jobs/353629118
Build: Install python explicitly in build
> Build: Install python explicitly in build

- .travis.yml
The build is failing:
>$ pyenv install 3.6.10
python-build: definition not found: 3.6.10
See all available versions with `pyenv install --list'.
If the version you need is missing, try upgrading pyenv:
Other travis builds have successfully used 3.6.3
-
> Build: Use python 3.6.3

- packages/webservice/app/build.gradle.kts
- packages/webservice/app/src/main/resources/application.yaml
- packages/webservice/models/build.gradle.kts
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/Asset.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/Dashboard.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/DashboardWidget.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/HasAuthor.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/HasEditors.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/Report.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/DashboardPresentation.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/DashboardWidgetVisualization.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/RequestV1.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/RequestV2.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/Visualization.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/layout/Layout.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/request/Dimension.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/request/Filter.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/request/Having.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/request/Interval.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/request/LogicalTable.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/request/Metric.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/request/Sort.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/request/v2/Column.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/request/v2/Filter.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/request/v2/Sort.kt
Update: Support Elide GraphQL
- Enable GraphQL
- Update to Elide5-pr12
- Use List instead of Array in fragments
- Cleanup data class constructors
> Update: Support Elide GraphQL

- packages/core/addon/helpers/default-column-name.js
- packages/core/tests/integration/helpers/default-column-name-test.js
Tables request metadata with type 'dimension' still. This is a quick fix to make sure time-dimensions can still let the table render. #879 is for a better long term fix by supporting more than metric/dimensions as column types.
- When dimension metadata can't be found, look in time-dimension bucket for default name helper.
> Fix: Quick fix default name time-dimension support

- packages/data/addon/gql/fragments/table.ts
- packages/data/addon/gql/queries/table.ts
- packages/data/addon/gql/queries/tables.ts
- packages/data/tests/unit/adapters/elide-metadata-test.js
Elide doesn't support some of the fields we request in our metadata and has some issues with using fragments for now.
- Temporarily remove some requested fields
- Temporarily stop using fragment
> Update: Remove unsupported metadata fields from graphql queries

- packages/core/addon/models/bard-request/request.js
- packages/core/tests/unit/models/bard-request/request-test.js
- packages/webservice/gradle/wrapper/gradle-wrapper.properties
When cloning a report, time-dimensions get cloned as undefined
- Make sure dimension/time-dimension metadata gets queried as the right type during clone
- Also gradle update for java > 8
> Fix: Request clones time-dimensions correctly

- packages/reports/addon/components/grouped-list.js
- packages/reports/tests/integration/components/grouped-list-test.js
Grouped-list component would blow up if one of the items had a falsey value in the `groupByField`
- Use falsey values as a value for grouping too
> Allow grouped list to group on fields with possibly falsey values

- packages/core/addon/templates/components/navi-loader.hbs
- packages/search/addon/components/navi-search-bar.js
- packages/search/addon/components/navi-search-result/wrapper.hbs
- packages/search/addon/components/navi-search-result/wrapper.ts
- packages/search/addon/services/navi-search-provider.js
- packages/search/app/components/navi-search-result/wrapper.js
- packages/search/app/styles/navi-search/components/navi-wrapper-search-result.less
- packages/search/tests/integration/components/navi-search-result/wrapper-test.js
- packages/search/tests/unit/services/navi-search-provider-test.js
Resolves #
It used to be that for the navi-search-provider federated service to return results it had to successfully resolve the responses of all the search providers. 
Now changed so that the federated service returns tasks instances of the search providers and the result wrapper is the one that takes care of displaying only the results that successfully resolved from the task instances.
-
> Navi Search Load Search Results Individually

- packages/data/addon/services/metric-parameter.js
- packages/data/test-support/helpers/metadata-routes.js
- packages/data/tests/unit/services/bard-metadata-test.js
- packages/data/tests/unit/services/metric-parameter-test.js
Dimensions that only have id fields don't work correctly as metric function parameter values
- Normalize metric function parameter values.
> Fix: Normalize dims with id only fields

- packages/reports/addon/components/grouped-list.js
- packages/reports/tests/integration/components/grouped-list-test.js
We shouldn't use `undefined` or `null` as grouping values in the grouped-list
- Use `Uncategorized` as the grouping value for falsy values
> Update: Use `Uncategorized` for grouped-list falsy group values

- packages/data/addon/adapters/elide-facts.ts
- packages/data/tests/unit/adapters/elide-facts-test.ts
- packages/data/tests/unit/utils/adapter-test.js
We need to be able to send Elide queries using the new request V2 format.
- Add function to compose query string from a request v2 object
- Add util function for formatting a parameterized field for query
> Update: Elide-facts adapter can send queries with RequestV2

- packages/core/addon/components/navi-visualization-config/series-chart.js
- packages/core/addon/models/bard-request-v2/fragments/base.js
- packages/core/addon/models/bard-request-v2/request.js
- packages/core/tests/unit/models/bard-request-v2/fragments/column-test.js
- packages/core/tests/unit/models/bard-request-v2/fragments/filter-test.js
- packages/core/tests/unit/models/bard-request-v2/fragments/sort-test.js
- packages/core/tests/unit/models/bard-request-v2/request-test.js
- packages/core/tests/unit/serializers/bard-request-v2/request-test.js
- packages/core/tests/unit/services/fragment-factory-test.js
- packages/reports/addon/components/dimension-selector.js
- packages/reports/addon/components/filter-builders/base.js
- packages/reports/addon/components/filter-builders/dimension.js
- packages/reports/addon/components/filter-builders/metric.js
- packages/reports/addon/components/filter-collection.js
- packages/reports/addon/components/filter-values/dimension-select.js
- packages/reports/addon/components/metric-selector.js
- packages/reports/addon/consumers/request/column.js
- packages/reports/addon/consumers/request/filter.js
- packages/reports/addon/consumers/request/sort.js
- packages/reports/addon/utils/request-metric.js
- packages/reports/tests/unit/consumers/request/column-test.js
- packages/reports/tests/unit/consumers/request/filter-test.js
Rename `columnMeta` to `columnMetadata`
We often use the word `metadata` instead of `meta`. For instance `metadataService`. This PR renames `columnMeta` to `columnMetadata`.
> Update: Rename `columnMeta` to `columnMetadata`

- .travis.yml
Travis is only configured to build master
> To only build pull requests targeting specific branches you can use the branches: only: key, which will also restrict the branches that trigger builds.
[Travis How Pull Requests are Built](https://docs.travis-ci.com/user/pull-requests#how-pull-requests-are-built)
- add request-v2 branches and hopefully pull requests against them
> Update: Travis config for integration branches

- packages/core/addon/chart-builders/metric.js
- packages/core/addon/components/navi-visualization-config/series-chart.js
- packages/core/addon/models/bard-request-v2/fragments/base.js
- packages/core/addon/models/bard-request-v2/request.js
- packages/core/addon/models/table.js
- packages/core/addon/services/fragment-factory.ts
- packages/core/addon/utils/chart-data.js
- packages/core/addon/utils/request.ts
- packages/core/tests/integration/components/navi-cell-renderers/time-dimension-test.ts
- packages/core/tests/unit/models/bard-request-v2/fragments/column-test.js
- packages/core/tests/unit/models/bard-request-v2/request-test.js
- packages/core/tests/unit/models/report-test.js
- packages/core/tests/unit/models/table-test.js
- packages/core/tests/unit/serializers/bard-request-v2/request-test.js
- packages/core/tests/unit/utils/request-test.js
- packages/data/tests/unit/services/navi-facts-test.js
- packages/reports/addon/components/filter-collection.js
Fix usage of `time-dimension` under request v2. Right now we only expect it to be used when looking up/fetching metadata
> Update: Rename time-dimension -> timeDimension

- packages/core/addon/utils/request.ts
- packages/core/tests/unit/models/bard-request-v2/fragments/column-test.js
- packages/core/tests/unit/models/bard-request-v2/fragments/filter-test.js
- packages/core/tests/unit/models/bard-request-v2/fragments/sort-test.js
- packages/core/tests/unit/models/bard-request-v2/request-test.js
- packages/core/tests/unit/models/table-test.js
- packages/core/tests/unit/serializers/bard-request-v2/request-test.js
- packages/core/tests/unit/utils/request-test.js
- packages/data/addon/adapters/bard-facts.ts
- packages/data/addon/adapters/dimensions/bard.ts
- packages/data/addon/adapters/fact-interface.ts
- packages/data/tests/unit/adapters/bard-facts-test.js
- packages/data/tests/unit/services/navi-facts-test.js
- packages/reports/addon/components/filter-builders/dimension.js
- packages/reports/addon/consumers/request/filter.js
- packages/reports/tests/unit/consumers/request/filter-test.js
Navi makes a lot of assumptions regarding `id` and `desc` fields for dimensions
- Every dimension now uses a `field` parameter defaulted to `'id'` we'll allow users to configure them later
> Update: Add field parameter to dimensions

- packages/webservice/app/build.gradle.kts
- packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/UserTest.kt
- packages/webservice/models/build.gradle.kts
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/User.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/hooks/UserValidationHook.kt
Upgrades to Elide 5 PR 15 build.
There is a security change in PR15 that breaks the User bean create permission.  This is a workaround pending a more expensive modeling change in Navi.
I also added the Hibernate validator (which was missing) which turns on JSR303 validations.
> Upgrading to Elide 5 PR 15

- packages/core/addon/mirage/fixtures/dashboard-widget.js
- packages/core/tests/integration/components/navi-visualizations/pie-chart-test.js
- packages/data/addon/adapters/metadata/bard.ts
- packages/data/addon/adapters/metadata/elide.ts
- packages/data/addon/mirage/fixtures/bard-meta-dimensions.js
- packages/data/addon/mirage/fixtures/bard-meta-metrics.js
- packages/data/addon/mirage/routes/bard-meta.js
- packages/data/addon/models/metadata/column-function.ts
- packages/data/addon/models/metadata/dimension.ts
- packages/data/addon/models/metadata/metric.ts
- packages/data/addon/models/metadata/registry.ts
- packages/data/addon/models/metadata/table.ts
- packages/data/addon/models/metadata/time-dimension.ts
- packages/data/addon/serializers/metadata/bard.ts
- packages/data/addon/serializers/metadata/elide.ts
- packages/data/addon/serializers/metadata/interface.ts
- packages/data/addon/services/bard-metadata.js
- packages/data/addon/services/elide-metadata.ts
- packages/data/addon/services/keg.ts
- packages/data/addon/services/navi-metadata.ts
- packages/data/addon/utils/adapter.ts
- packages/data/app/services/navi-metadata.js
- packages/data/tests/unit/adapters/metadata/bard-test.ts
- packages/data/tests/unit/serializers/metadata/bard-test.js
- packages/data/tests/unit/serializers/metadata/elide-test.ts
- packages/data/tests/unit/services/bard-dimensions-test.js
- packages/data/tests/unit/services/navi-metadata-test.ts
Navi metadata service
**Note**: Removal of bard and elide metadata services will be done in another PR
-  Fix typos and update names
- Update: Add MetadataModelRegistry
- Update: Bard metadata mirage mocks
- Remove description field in fullview response
- Return correct response shape if requesting non fullview table request
- Use mirage `Response` object for 404 response
- Update: Refactor metadata adapter & serializers
- Update `normalize` method to take `dataSourceName` argument
- Bard adapter & serializer works with arrays of models
- Bard uses the presence of `description` to determine if partial
- Update: Refactor keg types
- Update: Add navi-metadata service
I confirm that this contribution is made under an MIT license and that I have the authority necessary to make this …
> Navi metadata service

- packages/data/addon/adapters/facts/bard.ts
- packages/data/addon/models/metadata/function-parameter.ts
- packages/data/addon/serializers/metadata/bard.ts
- packages/data/addon/serializers/metadata/column-function.ts
- packages/data/config/navi-config.d.ts
- packages/data/tests/unit/adapters/facts/bard-test.js
- packages/data/tests/unit/models/metadata/column-function-test.ts
- packages/data/tests/unit/models/metadata/function-parameter-test.ts
- packages/data/tests/unit/serializers/metadata/bard-test.js
- packages/data/tests/unit/services/navi-facts-test.js
- packages/data/tests/unit/services/navi-metadata-test.ts
Resolves #938 #916
Each table in fili can specify a list of timegrains to filter on, so we want to model this as a unique timeDimension for each table
For each table from fili, we now create a `${tableName}.dateTime` with a `columnFunctionId = ${tableName}.grain(${grains})`
> Request v2 table date time

- packages/data/addon/mirage/fixtures/bard-meta-dimensions.js
- packages/data/addon/models/metadata/dimension.ts
- packages/data/addon/models/metadata/function-parameter.ts
- packages/data/addon/serializers/metadata/bard.ts
- packages/data/addon/serializers/metadata/column-function.ts
- packages/data/test-support/helpers/metadata-routes.js
- packages/data/tests/unit/models/metadata/dimension-test.ts
- packages/data/tests/unit/serializers/metadata/bard-test.ts
Resolves #921 
Currently in request v2, we have no way of selecting the `field` parameter on dimension columns. Since we've made columnFunction generic, we can now link to it from a dimension and create a function for picking from those dimension fields
Create a columnFunction for every unique set of dimension fields and link to them as a `field` parameter on dimensions
> Update: Create columnFunction for dimension fields

- packages/data/addon/adapters/facts/bard.ts
- packages/data/addon/adapters/facts/interface.ts
- packages/data/tests/unit/adapters/facts/bard-test.ts
Resolves #957 
Fili has strict requirements on how filtered dates align to the timeGrain
- Only allow a single dateTime column and dateTime filter, requiring that they have the same time grain
so these are valid
```js
{
filters: [{ type: 'timeDimension', field: 'tableName.dateTime', parameters: { grain: 'all' }, operator: 'bet', values: []],
columns: []
}
{
filters: [{ type: 'timeDimension', field: 'tableName.dateTime', parameters: { grain: 'all' }, operator: 'bet', values: [] ],
columns: [{ type: 'timeDimension', field: 'tableName.dateTime', parameters: { grain: 'all' }]
}
{
filters: [{ type: 'timeDimension', field: 'tableName.dateTime', parameters: { grain: 'day' }, operator: 'bet', values: [] ],
columns: [{ type: 'timeDimension', field: 'tableName.dateTime', parameters: { grain: 'day' …
```
> Update: Require only one dateTime column/filter and same grain

- packages/data/addon/adapters/facts/elide.ts
- packages/data/addon/serializers/facts/elide.ts
- packages/data/tests/unit/adapters/facts/elide-test.ts
- packages/data/tests/unit/serializers/facts/elide-test.ts
- packages/data/tests/unit/services/navi-facts-elide-test.js
Resolves #953 
Resolves #961
Update: Fix elide request and response names
- Update elide adapter and serializer
- Move `queryStrForField` private method to export function `getElideField`
> Update: Fix elide request and response names

- packages/data/addon/adapters/dimensions/elide.ts
- packages/data/addon/adapters/dimensions/interface.ts
- packages/data/addon/adapters/facts/elide.ts
- packages/data/addon/adapters/facts/interface.ts
- packages/data/app/adapters/dimensions/elide.js
- packages/data/tests/unit/adapters/dimensions/elide-test.ts
- packages/data/tests/unit/adapters/facts/elide-test.ts
Resolves #950 
We need to be able to fetch dimension values from elide so we can support type ahead search in the filter builder.
- Create elide dimension adapter
- Update elide facts adapter to request against the right uri for the given datasource
- Remove some RequestV1 stuff
> New: Elide Dimension Adapter

- packages/data/addon/adapters/facts/elide.ts
- packages/data/addon/mirage/factories/dimension.js
- packages/data/addon/mirage/factories/metric.js
- packages/data/addon/mirage/factories/time-dimension.js
- packages/data/addon/mirage/handlers/graphql.js
- packages/data/addon/serializers/dimensions/elide.ts
- packages/data/app/serializers/dimensions/elide.js
- packages/data/tests/dummy/mirage/scenarios/elide-one.ts
- packages/data/tests/dummy/mirage/scenarios/elide-two.ts
- packages/data/tests/unit/adapters/dimensions/elide-test.ts
- packages/data/tests/unit/adapters/facts/elide-test.ts
- packages/data/tests/unit/adapters/metadata/elide-test.ts
- packages/data/tests/unit/serializers/dimensions/elide-test.ts
- packages/data/tests/unit/services/navi-dimension-test.ts
- packages/data/tests/unit/services/navi-facts-elide-test.js
- packages/data/tests/unit/services/navi-metadata-test.ts
Closes #949 
Closes #948 
We need to serialize dimension value payloads from the elide dimension adapter.
- Add elide dimension serializer
- Update graphql handler to handle dimension value search
- Test navi-dimension-service using the graphql mocks
> Elide dimension serializer and mock

- packages/data/addon/gql/fragments/table.ts
- packages/data/addon/gql/queries/table.ts
- packages/data/addon/gql/queries/tables.ts
- packages/data/addon/gql/schema.js
- packages/data/addon/serializers/metadata/elide.ts
- packages/data/tests/dummy/mirage/scenarios/elide-one.ts
- packages/data/tests/dummy/mirage/scenarios/elide-two.ts
- packages/data/tests/unit/serializers/metadata/elide-test.ts
Elide updated its schema for metadata recently
- `supportedGrains` -> `supportedGrain`
Left it as an array as `supportedGrain` is still a collection in Elide
> Fix: GraphQL Metadata queries after API update

- packages/data/addon/gql/fragments/table.ts
- packages/data/addon/gql/queries/table.ts
- packages/data/addon/gql/queries/tables.ts
- packages/data/addon/mirage/factories/time-dimension-grain.js
- packages/data/addon/mirage/handlers/graphql.js
- packages/data/addon/serializers/metadata/elide.ts
- packages/data/tests/unit/serializers/metadata/elide-test.ts
- packages/data/tests/unit/services/navi-metadata-test.ts
Resolves #977 
We need a columnFunction for each time dimension so that the metadata has a uniform property for its supported grains regardless of what the data source is
- add createTimeGrainColumnFunction to elide metadata serializer
- add custom handler to mirage graphql config for timeDimensionGrains since the addon can't do it properly
- bring fragments back to the graphql table queries because they're supported now by elide
> Elide time dimension col funcs

- packages/reports/addon/components/report-actions/save-as.js
- packages/reports/tests/acceptance/report-test.js
Noticed that changing title in save as modal, still creates a report of `(Copy Of) Old Title` regardless of changes.
- The value bound to Input just has a getter that returns default.
- Added setter and private state variable to override default value in getter.
- Added test to catch this misbehavior in the future.
> Fix: Save-as custom title doesn't save

- .travis.yml
- packages/webservice/models/build.gradle.kts
- scripts/artifactory-publish-beta.sh
Resolves #994 
Upcoming cid change in #982 will only be visible on the `request-v2` branch which does not get published
- set up extra publishing step for `request-v2` only as `0.2.0-beta-SNAPSHOT`
> Update: Publish beta webservice to artifactory

- .travis.yml
npm ci be taking it's time timing out the output wait in travis
- add travis_wait to npm ci
> Fix: Build npm install taking a bit o time.

- packages/data/addon/adapters/facts/elide.ts
- packages/data/tests/unit/adapters/facts/elide-test.ts
Resolves #1018 
We have too many escape characters before quotes in the elide fact adapter.
- Remove unneeded escapes
> Fix: Elide fact query arguments

- packages/data/addon/adapters/facts/elide.ts
- packages/data/tests/unit/adapters/facts/elide-test.ts
Resolves #995 
The between operator is not currently supported by Elide.
- Split a filter with "bet" as the operator into two filters of `>= ${v1}` and `< ${v2}`
> Elide "bet" operator

- packages/core/addon/serializers/table.ts
Optional cid on serialized RequestV2 makes it possibly undefined so add an assert requiring it to be defined
> Update: Fixup for optional cid in table serializer

- packages/data/addon/gql/fragments/table.ts
- packages/data/addon/gql/schema.js
- packages/data/addon/mirage/factories/dimension.js
- packages/data/addon/mirage/factories/metric.js
- packages/data/addon/mirage/factories/time-dimension.js
- packages/data/addon/serializers/metadata/elide.ts
- packages/data/tests/unit/adapters/metadata/elide-test.ts
- packages/data/tests/unit/serializers/metadata/elide-test.ts
Metadata queries aren't working with graphql right now
- `columnTags` => `tags`
> Update: Change columnTags to tags in metadata schema

- packages/core/addon/utils/error.js
- packages/core/tests/unit/utils/error-test.js
- packages/reports/addon/templates/reports/report/error.hbs
- packages/reports/tests/acceptance/error-route-test.js
Fili rate limit errors not being messaged to user properly. Get 'Server Error' instead.
- Add support for error message in plain text in body of response rather than json object
- Add support for regex matching for custom error message overrides.
> Rate limit support

- packages/data/addon/adapters/dimensions/bard.ts
- packages/data/addon/adapters/dimensions/elide.ts
- packages/data/addon/adapters/dimensions/interface.ts
- packages/data/addon/models/metadata/column.ts
- packages/data/addon/models/metadata/dimension.ts
- packages/data/addon/models/metadata/metric.ts
- packages/data/addon/models/metadata/time-dimension.ts
- packages/data/addon/models/navi-dimension.ts
- packages/data/addon/models/navi-fact-response.ts
- packages/data/addon/models/navi-facts.ts
- packages/data/addon/serializers/dimensions/bard.ts
- packages/data/addon/serializers/dimensions/elide.ts
- packages/data/addon/serializers/dimensions/interface.ts
- packages/data/addon/serializers/facts/bard.ts
- packages/data/addon/serializers/facts/elide.ts
- packages/data/addon/serializers/facts/interface.ts
- packages/data/addon/services/navi-dimension.ts
- packages/data/tests/unit/adapters/dimensions/elide-test.ts
- packages/data/tests/unit/models/navi-dimension-test.ts
- packages/data/tests/unit/models/navi-fact-response-test.ts
- packages/data/tests/unit/models/navi-facts.js
- packages/data/tests/unit/serializers/dimensions/bard-test.ts
- packages/data/tests/unit/serializers/dimensions/elide-test.ts
- packages/data/tests/unit/serializers/facts/bard-test.ts
- packages/data/tests/unit/serializers/facts/elide-test.ts
- packages/data/tests/unit/services/navi-facts-elide-test.js
- packages/data/tests/unit/services/navi-facts-test.ts
- packages/reports/addon/components/filter-values/dimension-select.ts
Add `navi-fact-response` model with min/max time dimension methods for handling non-static date filters
- Refactor column instance types
- Add `navi-fact-response` model 
- Adds min/max time dimension methods
- Adds `getCanonicalName` to base column metadata model
- Renames navi fact model test file name
- Use NaviFactResponse in NaviFacts model
> Response methods

- packages/app/config/environment.js
- packages/dashboards/addon/components/dashboard-actions/export.js
- packages/dashboards/addon/components/dashboard-actions/schedule.js
- packages/dashboards/addon/templates/components/dashboard-action-list.hbs
- packages/dashboards/addon/templates/components/navi-dashboard.hbs
- packages/dashboards/addon/templates/dashboards/dashboard/widgets/widget.hbs
- packages/dashboards/app/styles/navi-dashboards/components/navi-dashboard.less
- packages/dashboards/app/styles/navi-dashboards/views/print-navi-dashboard.less
- packages/dashboards/tests/acceptance/explore-widget-test.js
- packages/dashboards/tests/acceptance/schedule-modal-test.js
- packages/dashboards/tests/dummy/config/environment.js
- packages/dashboards/tests/integration/components/dashboard-actions/export-test.js
- packages/reports/addon/components/common-actions/schedule.js
- packages/reports/addon/components/report-actions/multiple-format-export.js
- packages/reports/addon/templates/components/navi-action-list.hbs
- packages/reports/addon/templates/components/report-actions.hbs
- packages/reports/addon/templates/components/report-actions/multiple-format-export.hbs
- packages/reports/app/styles/navi-reports/common/report-controls.less
- packages/reports/config/environment.js
- packages/reports/tests/acceptance/report-test.js
- packages/reports/tests/dummy/config/environment.js
- packages/reports/tests/integration/components/common-actions/schedule-test.js
- packages/reports/tests/integration/components/report-actions/multiple-format-export-test.js
Add PNG export.
- add PNG option to `multiple-format-export` component
- use in dashboards instead of the single export button
- add to schedule formats
❗not to be merged until fully supported on back end❗ 
> Update: PNG export

- packages/reports/addon/consumers/request/filter.ts
- packages/reports/tests/unit/consumers/request/filter-test.js
We can't currently filter on certain time dimensions on request-v2 because their metadataType is set to `TIME` rather than the expected `date`.
- support a `time` metadataType as well for filter adds
> Fix: Use appropriate filter operator for time dimensions

- packages/core/addon/chart-builders/dimension.ts
- packages/core/addon/models/bard-request-v2/request.ts
- packages/core/addon/models/chart-visualization.ts
- packages/core/addon/utils/chart-data.ts
- packages/core/addon/validators/request-dimension-order.js
- packages/core/tests/unit/models/bard-request-v2/request-test.js
- packages/core/tests/unit/utils/chart-data-test.ts
Resolves #1074 
`getRequestDimensions` doesn't need to be a separate utility function
- Make a property on the request fragment that will replace `getRequestDimensions`
> Update: Make getRequestDimensions a property on the request

- packages/core/addon/chart-builders/base.ts
- packages/core/addon/chart-builders/date-time.ts
- packages/core/addon/chart-builders/dimension.ts
- packages/core/addon/chart-builders/metric.ts
- packages/core/addon/components/navi-visualizations/line-chart.ts
- packages/core/addon/components/navi-visualizations/table.ts
- packages/core/addon/models/bard-request-v2/fragments/base.ts
- packages/core/addon/models/bard-request-v2/fragments/column.ts
- packages/core/addon/models/bard-request-v2/request.ts
- packages/core/addon/models/chart-visualization.ts
- packages/core/addon/utils/chart-data.ts
- packages/core/addon/utils/data.ts
- packages/core/addon/validators/request-dimension-order.js
- packages/core/tests/dummy/app/routes/line-chart.ts
- packages/core/tests/integration/components/navi-visualizations/line-chart-test.ts
- packages/core/tests/unit/chart-builders/date-test.ts
- packages/core/tests/unit/chart-builders/dimension-test.ts
- packages/core/tests/unit/chart-builders/metric-test.ts
- packages/core/tests/unit/components/navi-visualizations/line-chart-test.ts
- packages/core/tests/unit/utils/chart-data-test.ts
- packages/data/addon/models/navi-fact-response.ts
- packages/data/addon/utils/classes/interval.ts
- packages/data/tests/unit/utils/classes/interval-test.ts
Resolves #1079
We no longer expect a time filter that specifies the start and end date, so visualizations can no longer rely on an interval specified in the request
- updates line chart visualization to rely solely on the response for defining an interval, which should add support for `gte`, `lte` time filters
> Update: Migrate chart builders to use navi-fact-response

- screwdriver.yaml
ember-cli-build tries to manage it's own parallelization but it doesn't work well for CI so manually set JOBS to 6 and use HIGH resources for SD
also added a test node script to run to show cpu count
> Update: SD to use TURBO for gh-pages and set 4 JOBS

- packages/data/addon/adapters/dimensions/elide.ts
- packages/data/addon/mirage/factories/dimension.js
- packages/data/addon/models/metadata/elide/dimension.ts
- packages/data/addon/serializers/dimensions/elide.ts
- packages/data/tests/unit/adapters/dimensions/elide-test.ts
- packages/data/tests/unit/adapters/metadata/elide-test.ts
- packages/data/tests/unit/services/navi-dimension-test.ts
Resolves #
Adds support for dimension lookup for elide provided enum values
Needs #1093 
- Support elide dimension enum values
> Elide enums

- packages/core/addon/consumers/action-consumer.ts
- packages/reports/.eslintrc.js
- packages/reports/addon/consumers/request/fili.ts
- packages/reports/addon/services/request-action-dispatcher.ts
- packages/reports/app/consumers/request/fili.js
- packages/reports/tests/acceptance/date-filter-test.js
- packages/reports/tests/unit/consumers/request/fili-test.ts
Resolves #1000 
With the new report view it's challenging to change the parameters of a filter and would be extra work to change a parameter in both the column and filter
- Adds a fili specific consumer which will forward updates to the dateTime column to the dateTime filter so the grains are always in sync
> Update: Add fili consumer to keep filter in sync with dateTime column

- packages/core/addon/chart-builders/base.ts
- packages/core/addon/chart-builders/date-time.ts
- packages/core/addon/chart-builders/dimension.ts
- packages/core/addon/chart-builders/metric.ts
- packages/core/addon/components/navi-visualizations/line-chart.ts
- packages/core/addon/models/bard-request-v2/request.ts
- packages/core/addon/navi-visualization-manifests/base.ts
- packages/core/addon/navi-visualization-manifests/goal-gauge.ts
- packages/core/addon/navi-visualization-manifests/metric-label.ts
- packages/core/addon/navi-visualization-manifests/pie-chart.ts
- packages/data/addon/serializers/metadata/elide.ts
- packages/data/tests/unit/serializers/metadata/elide-test.ts
- packages/reports/addon/components/filter-values/base-date.ts
- packages/reports/addon/components/filter-values/date.hbs
- packages/reports/addon/components/filter-values/date.ts
- packages/reports/addon/components/filter-values/dimension-date-range.hbs
- packages/reports/addon/components/filter-values/dimension-date-range.ts
- packages/reports/addon/templates/components/navi-date-picker.hbs
The current date time filter does not make use of the grain being requested, so if the filtered column is a timeDimension we use that grain and fall back to "day" otherwise
- Also cleans up chart builders/viz to better handle changes in request
> Update: Use the timeDimension grain if available

- packages/core/addon/components/navi-visualizations/goal-gauge.ts
- packages/core/addon/components/navi-visualizations/metric-label.ts
- packages/core/addon/models/goal-gauge.ts
- packages/core/addon/models/metric-label.ts
- packages/core/tests/integration/components/navi-visualizations/goal-gauge-test.ts
- packages/core/tests/integration/components/navi-visualizations/metric-label-test.ts
- packages/core/tests/unit/models/goal-gauge-test.ts
- packages/core/tests/unit/models/metric-label-test.ts
Currently, the UI breaks when metric label or goal gauge try to render when a metric is missing. This gracefully handles the error, however more will need to be done to indicate to the user that the query needs to be re-executed.
- Handle missing metric in goal gauge
- Handle missing metric in metric label
> Fix missing metric issues

- packages/app/server/index.js
- packages/dashboards/addon/components/dashboard-actions/export.js
- packages/dashboards/tests/acceptance/dashboards-test.js
- packages/dashboards/tests/acceptance/schedule-modal-test.js
- packages/dashboards/tests/dummy/config/environment.js
- packages/notifications/app/styles/navi-notifications.less
- packages/reports/addon/components/report-actions/multiple-format-export.js
- packages/reports/addon/templates/components/report-actions/multiple-format-export.hbs
- packages/reports/app/styles/navi-reports/components/report-actions/multiple-format-export.less
- packages/reports/tests/acceptance/report-test.js
- packages/reports/tests/dummy/config/environment.js
- packages/reports/tests/dummy/mirage/config.js
- packages/reports/tests/integration/components/common-actions/schedule-test.js
- packages/reports/tests/integration/components/report-actions/multiple-format-export-test.js
Add support for google sheet exports
- add support for google sheet export
- add concept of export links that require saved state
- widen drop down for longer export names
- Will rebase on master once this is merged into alpha
> Update: Add google sheets support

- packages/core/addon/models/bard-request-v2/fragments/filter.ts
- packages/core/addon/models/bard-request-v2/request.ts
- packages/core/addon/services/fragment-factory.ts
- packages/core/addon/utils/request.ts
- packages/core/tests/unit/utils/request-test.ts
- packages/data/addon/adapters/facts/elide.ts
- packages/data/addon/adapters/facts/interface.ts
- packages/data/tests/unit/adapters/facts/elide-test.ts
- packages/data/tests/unit/services/navi-facts-elide-test.js
- packages/reports/addon/components/filter-values/multi-value-input.ts
- packages/reports/addon/components/filter-values/null-input.ts
- packages/reports/addon/consumers/request/filter.ts
- packages/reports/tests/integration/components/filter-collection-test.ts
- packages/reports/tests/integration/components/filter-values/null-input-test.ts
Fix Elide `contains` Filter
**Needs** #1133 
- Fix Elide `contains` filter building
- Ignore filters without filter values
- `null` & `notnull` operators now have a value of `true`
> Fix Elide `contains` Filter

- packages/reports/addon/templates/components/navi-action-list.hbs
Fix: Directory tooltips
- Fix: Directory tooltips
Before:
After:
> Fix: Directory tooltips

- packages/webservice/app/build.gradle.kts
- packages/webservice/app/src/main/resources/application.yaml
- packages/webservice/app/src/main/resources/demo-configs/models/tables/DemoTables.hjson
- packages/webservice/models/build.gradle.kts
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/Report.kt
Upgrade elide version to 5.0.0-pr28
Set `isFact` as false for `Report` model so it doesn't show up as table.
> Upgrade elide version to 5.0.0-pr28

- packages/app/config/environment.js
Set a temporary data epoch to `1900` so that the demo app allows filtering older dates
- This change will allow the demo app to not be limited in the dates it can filter to. In the future we should remove the requirement for an epoch or have a better default
> Update: Data epoch for demo app

- packages/reports/addon-test-support/report-builder.js
- packages/reports/addon/components/filter-builders/time-dimension.ts
- packages/reports/addon/components/report-view-overlay.hbs
- packages/reports/addon/components/report-view-overlay.ts
- packages/reports/addon/consumers/request/column.js
- packages/reports/addon/consumers/request/sort.ts
- packages/reports/addon/routes/reports/report.js
- packages/reports/addon/templates/components/report-view.hbs
- packages/reports/app/components/report-view-overlay.js
- packages/reports/app/styles/navi-reports/components/index.less
- packages/reports/app/styles/navi-reports/components/navi-column-config.less
- packages/reports/app/styles/navi-reports/components/report-builder.less
- packages/reports/app/styles/navi-reports/components/report-view-overlay.less
- packages/reports/tests/acceptance/report-test.js
- packages/reports/tests/acceptance/report-view-overlay-test.ts
- packages/reports/tests/integration/components/report-view-overlay-test.ts
- packages/reports/tests/unit/consumers/request/sort-test.ts
- packages/reports/tests/unit/routes/reports/report-test.js
With request 2.0 we listen to a lot more changes on the request and dynamically update the visualization which sometimes makes it incorrect
- Fix bug with sort consumer where removing a duplicated column removes the sorts
- Adds a shade over the report view when the request has been modified to make the response out of date
> Report visualization shade

- packages/core/addon/chart-builders/base.ts
- packages/core/addon/chart-builders/date-time.ts
- packages/core/addon/chart-builders/dimension.ts
- packages/core/addon/chart-builders/metric.ts
- packages/data/addon/adapters/facts/elide.ts
- packages/data/addon/mirage/routes/graphql.js
The line/bar chart did not handle updates to time dimensions well. We thought this was only a fili issue when changing grains in the column config but it affects elide as well
Steps to Reproduce error before this PR
- http://localhost:8080/ui/reports/new
- add country
- add count
- run
- switch to bar chart
- add release year
- filter release year
- Guard against missing timeGrainColumn data
- Use utc for elide filters and mocks
> Fix chart builders time dimension

- packages/core/addon/helpers/is-forbidden.js
- packages/core/addon/mirage/fixtures/dashboard.js
- packages/core/addon/serializers/table.ts
- packages/core/tests/unit/serializers/table-test.ts
- packages/dashboards/addon/components/dashboard-dimension-selector.js
- packages/dashboards/addon/components/dashboard-filters.js
- packages/dashboards/addon/services/dashboard-data.js
- packages/dashboards/addon/templates/components/navi-widget.hbs
- packages/dashboards/tests/acceptance/dashboard-filter-test.js
- packages/dashboards/tests/acceptance/dashboards-test.js
- packages/dashboards/tests/acceptance/explore-widget-test.js
- packages/dashboards/tests/acceptance/mutli-datasource-dashboards-test.js
- packages/dashboards/tests/acceptance/report-action-test.js
- packages/dashboards/tests/integration/components/dashboard-dimension-selector-test.js
- packages/dashboards/tests/integration/components/dashboard-filters-test.js
- packages/dashboards/tests/unit/routes/dashboards/dashboard/clone-test.js
- packages/dashboards/tests/unit/routes/dashboards/dashboard/widgets/new-test.js
- packages/dashboards/tests/unit/services/dashboard-data-test.js
- packages/data/addon/serializers/metadata/bard.ts
- packages/data/addon/services/navi-facts.ts
- packages/reports/addon/components/filter-collection.hbs
- packages/reports/addon/components/unauthorized-table.js
- screwdriver.yaml
Fixes failing dashboards tests
- fixed a bug with dashboard-data service where we yielded a promise instead of a TaskInstance so cancelling did not bubble correctly
- removed date dimension filter
- catch errors when calling `getURL`
- Fili dimensions use `primaryKey` field as default value for dimension field parameter
> Fix dashboard tests

- packages/data/addon/adapters/facts/bard.ts
- packages/data/addon/serializers/facts/bard.ts
- packages/data/tests/unit/services/navi-facts-test.ts
Our new error handling/extraction does not surface errors thrown from the adapter such as requiring a filter (which can happen since we don't have required table filters)
- add a check to see if error was thrown from adapter
> Fix: Show fili adapter errors

- packages/core/addon/models/bard-request-v2/request.ts
- packages/dashboards/addon/templates/dashboards/dashboard/widgets/widget.hbs
- packages/data/addon/mirage/fixtures/bard-meta-dimensions.js
- packages/reports/addon/components/filter-collection.ts
- packages/reports/addon/components/navi-column-config.hbs
- packages/reports/addon/components/navi-column-config.ts
- packages/reports/addon/templates/components/navi-action-list.hbs
- packages/reports/addon/templates/components/report-actions.hbs
- packages/reports/tests/acceptance/report-test.js
Fixes most failing tests from Navi Report
- Fixed an issue with export types not working as expected
- Fixed an issue with missing table's not being handled the same
Still need to fix `filters - collapse and expand` which I'm planning to handle in a similar way to our `DID_ADD_COLUMN` consumer
> Update: Fix Navi Report minus filters expanding

- packages/data/addon/adapters/facts/bard.ts
- packages/data/tests/unit/adapters/facts/bard-test.ts
In Request v2 we are skipping over filters with empty value arrays
- This was already working in elide so added support on the fili side
> Update: Skip filters with empty values array

- packages/data/addon/gql/fragments/table.ts
- packages/data/addon/gql/queries/tables.ts
- packages/data/addon/models/metadata/table.ts
- packages/data/addon/serializers/metadata/bard.ts
- packages/data/addon/serializers/metadata/elide.ts
- packages/data/tests/unit/adapters/metadata/elide-test.ts
- packages/data/tests/unit/serializers/metadata/bard-test.ts
- packages/data/tests/unit/serializers/metadata/elide-test.ts
- packages/reports/addon/components/report-builder.js
- packages/reports/addon/routes/reports/new.js
- packages/reports/tests/unit/components/report-builder-test.js
We currently filter elide tables to only fetch the fact ones in order to hide tables for application data (reports/async queries/etc), but elide fact tables can point to non-fact tables for sourcing dimension values
- Hide non-fact tables from the UI, but keep the metadata loaded for providing faster dimension lookups
> Update: Load all tables but hide non-fact ones

- packages/core/tests/dummy/config/environment.js
- packages/data/addon/utils/classes/duration.ts
- packages/data/addon/utils/duration-utils.ts
- packages/reports/addon/components/filter-builders/time-dimension.ts
- packages/reports/addon/components/filter-values/time-dimension/lookback.ts
- packages/reports/addon/consumers/request/fili.ts
- packages/reports/addon/helpers/format-interval-inclusive-inclusive.js
- packages/reports/config/environment.js
- packages/reports/tests/unit/components/filter-builders/time-dimension-test.ts
- packages/reports/tests/unit/consumers/request/fili-test.ts
The fili consumer would update the grain parameter of a dateTime filter to match the column, but would not update the values so the displayed value would not match the queried one.
- update the filter values when the grain changes
- Fix an issue with using isoweek for lookback
> Fix: Lookback for isoWeek, better fili grain support

- packages/core/addon/models/dashboard.ts
- packages/core/addon/serializers/dashboard.js
- packages/core/tests/unit/serializers/dashboard-test.js
Dashboard filters are still using the old v1 format on the WS so it assumed all filters were for fili datasources (i.e. dimension filters that have a `field` parameter)
- Use `canonicalName` rather than hardcoded string for better support
> Update: Dashboards filters support no parameters

- .dockerignore
- container/docker/Dockerfile.alpine
- container/docker/Dockerfile.demo_local
- container/docker/README.md
- packages/webservice/app/build.gradle.kts
Resolves # 
- Docker images getting out of date.
- Docker image size was over 4 GB due to duplicate dependencies in node modules.
Docker container integration.
Optimized node_module dependency
Readme for docker related information.
-
add Dockerfiles
add readme.
final integration and image build workflow is in side docker hub.
> Docker image build integration

- packages/core/addon/components/navi-visualizations/line-chart.ts
- packages/core/app/styles/navi-core/visualizations/line-chart.less
- packages/core/tests/unit/components/navi-visualizations/line-chart-test.ts
Update Line chart for missing data points
This PR increases the line chart radius and stroke-width to handle the case when there are missing data points
> Update: Line chart for missing data points

- packages/dashboards/addon/templates/components/navi-dashboard.hbs
- packages/dashboards/addon/templates/dashboards/dashboard/widgets/widget.hbs
- packages/dashboards/tests/acceptance/explore-widget-test.js
- packages/reports/addon/components/report-view-overlay.hbs
- packages/reports/addon/templates/reports/report.hbs
- packages/reports/tests/acceptance/report-test.js
Move report and dashboard buttons over to denali
> Update: Report and Dashboards use Denali buttons

- packages/directory/addon/components/dir-search-bar.hbs
Accidentally delete a wrapper class so the style fixups for the search bar were not being used
> Update: Add back wrapper class

- packages/app/app/index.html
Clicking the search button input slightly zooms in the page and makes the user zoom out after clicking
- Update meta tag so that the zoom does not change when focusing inputs, but still allows users to manually zoom (https://stackoverflow.com/a/46254706)
> Update: App index.html don't zoom on input focus

- packages/app/app/styles/app.less
- packages/app/app/styles/app.scss
- packages/app/app/styles/views/dashboards.scss
- packages/app/app/styles/views/index.scss
- packages/app/app/styles/views/reports.scss
Move `.less` to `.scss` for app styles
> Update: Migrate less to sass for app

- package.json
- packages/app/package.json
- packages/webservice/README.md
- packages/webservice/app/build.gradle.kts
Resolves #
Separate prod and dev env builds
pass gradle variable while running build to indicate env.
example : `./gradlew bootJar -Pbuild_env=prod`
If no arg provided then default is dev. Values are dev | prod
-
> Build: dev n prod build (fixes #CARBON-552)

- packages/data/addon/gql/fragments/table.ts
- packages/data/addon/gql/schema.ts
- packages/data/addon/serializers/metadata/elide.ts
- packages/data/tests/unit/serializers/metadata/elide-test.ts
- packages/webservice/app/build.gradle.kts
- packages/webservice/app/src/main/resources/db/changelog/changelog.xml
- packages/webservice/app/src/main/resources/demo-configs/models/tables/DemoTables.hjson
- packages/webservice/models/build.gradle.kts
Update to latest elide release
i) Multiple TimeGrains
ii) User_role table changed to User_Roles. (This seems to be caused by latest Hibernate versions in elide-spring-boot-starter but I can not find a relevant ticket/change anywhere)
> update elide version to 5.0.0-pr31

- packages/data/addon/adapters/facts/bard.ts
- packages/data/addon/mirage/routes/bard-lite.ts
- packages/data/tests/unit/adapters/facts/bard-test.ts
- packages/reports/tests/acceptance/fili-datasource-test.ts
- packages/reports/tests/unit/components/filter-builders/time-dimension-test.ts
Resolves #1260
Add support for since/before operators in fili by using far past (or dataEpoch) and distant future as bounds
> Update: Support since/before operator in fili

- packages/data/addon/adapters/facts/bard.ts
- packages/data/addon/adapters/facts/elide.ts
- packages/data/addon/adapters/facts/interface.ts
- packages/data/addon/mirage/routes/graphql.js
- packages/data/addon/serializers/dimensions/elide.ts
- packages/data/addon/serializers/facts/bard.ts
- packages/data/addon/serializers/facts/elide.ts
- packages/data/tests/unit/adapters/facts/elide-test.ts
- packages/data/tests/unit/serializers/dimensions/elide-test.ts
- packages/data/tests/unit/serializers/facts/elide-test.ts
- packages/reports/addon/consumers/request/filter.ts
- packages/reports/tests/integration/components/common-actions/get-api-test.js
- packages/webservice/app/src/main/resources/demo-configs/models/tables/DemoTables.hjson
Resolves #1258 
Elide added support for multiple time grains on timeDimensions
- Use alias for each requested column and use it for applicable sorts/filters
- single parameter support for elide which allows requesting specific grains of a timeDimension
- added example of day/year timegrain for netflix dataset
> Update: Add support for multiple time grains in elide

- .gitattributes
This will give a more accurate counting of TS vs JS in our repo
As of now the breakdown is
but this also includes a large vendor file in the webservice package
> Update: Add .gitattributes

- packages/data/addon/adapters/dimensions/elide.ts
- packages/data/tests/unit/adapters/dimensions/elide-test.ts
- packages/data/tests/unit/services/navi-dimension-test.ts
We used `colN` aliasing convention for elide columns but didn't implement this for our mock enum response
- use 'col0' as field instead of elideField for enum responses
> Fix: Elide enum value search

- build-scripts/setup-chrome.sh
- screwdriver.yaml
Parallelize the sd build for the main job
We should also look into ways to speed up the WS build because it takes awhile to boot up for each test
> Update: Build main SD jobs in parallel

- build-scripts/setup-chrome.sh
- screwdriver.yaml
SD was not able to interpret the `[[` command which worked when there was no cache, but now that it exists is breaking
```
./build-scripts/setup-chrome.sh: 5: ./build-scripts/setup-chrome.sh: [[: not found
17:17:34 /usr/bin/chrome does not exist. Starting download.
```
> Update: SD disable chrome cache

- README.md
- package.json
Resolves #
Lerna is aware of CI environments and runs `npm ci` if `process.env.CI` is `true`. Since there are times when you don't want `npm ci`, such as when update a dependency. This PR changes the lerna bootstrap command to run `npm ci` only when `process.env.CI` is `true`.
- Remove the `--ci` flag from the `bootstrap` cmd
> Build: Don't force `ci` during lerna bootstrap

- packages/data/addon/adapters/facts/elide.ts
- packages/data/tests/unit/adapters/facts/elide-test.ts
Elide's new release supports parameters in filters
- remove restriction for parameters in filters
> Update: Allow parameters in elide filters

- packages/webservice/app/src/main/resources/demo-configs/models/tables/DemoTables.hjson
Fix day grain definition, adds week, isoweek, month grains
Standard week seems to work well in the UI without any changes
- fixes an issue with day grain not having sql definition
- Fixes Year grain definition (was using [weekyear](https://stackoverflow.com/a/12781297))
> Update: Add week, isoweek, month grains for elide

- package.json
Looks like we are not publishing TS definitions. Caught this in the logs:
```
lerna WARN lifecycle navi-data@0.2.0-beta.580+0564b8fc~prepublishOnly: 
cannot run in wd navi-data@0.2.0-beta.580+0564b8fc ember ts:precompile (wd=/sd/workspace/src/github.com/yavin-dev/framework/packages/data)
```
https://cd.screwdriver.cd/pipelines/6102/builds/690514/steps/publish
Hopefully this can fix it.
-  Add `-- --unsafe-perm` to lerna publish
> Build: Add `-- --unsafe-perm` to lerna publish

- package.json
- scripts/npm-publish.sh
Resolves #
Looks like we are not publishing TS definitions. Caught this in the logs:
```
lerna WARN lifecycle navi-data@0.2.0-beta.580+0564b8fc~prepublishOnly: 
cannot run in wd navi-data@0.2.0-beta.580+0564b8fc ember ts:precompile (wd=/sd/workspace/src/github.com/yavin-dev/framework/packages/data)
```
https://cd.screwdriver.cd/pipelines/6102/builds/690514/steps/publish
Hopefully this can fix it.
- Set unsafe-perm true when publishing
> Build: Set unsafe-perm true when publishing

- packages/notifications/package.json
- packages/notifications/tests/dummy/config/environment.js
- packages/notifications/tests/dummy/mirage/config.js
- packages/notifications/tsconfig.json
Resolves #
This PR adds navi-core as a devDep to notifications for its TS notification definition and refactors the tsconfig to fix the build:
```
addon/components/navi-notifications/alert.ts:7:51 - error TS6059: File '/sd/workspace/src/github.com/yavin-dev/framework/packages/core/addon/services/interfaces/navi-notifications.ts' is not under 'rootDir' '/sd/workspace/src/github.com/yavin-dev/framework/packages/notifications'. 'rootDir' is expected to contain all source files.
```
https://cd.screwdriver.cd/pipelines/6102/builds/691308/steps/publish
-
> Build: Add navi-core as a devDep to notifications

- packages/reports/addon/components/grouped-list.ts
Getting an error in the `app` repo where sortByField is being set to null so use a more forgiving type
- accept null sortByField
> Update: Accept null for sortByField

- packages/reports/app/styles/navi-reports/components/filter-collection.less
The current design makes the dashboard filter box to expand and take over the screen as more values are added.
Set a max height for the filter box. We will be able to scroll if more values are added.
-
Before
After
> Set max size for filter selection box

- packages/data/tests/test-helper.ts
- packages/reports/addon-test-support/column-config.ts
- packages/reports/addon/components/navi-column-config/item.hbs
- packages/reports/tests/acceptance/column-config-test.ts
`ember-sortable` was using the whole element while the handle element was hidden making it sometimes impossible to rename a column
- disable dragging when mouse is not in column
> Update: Ember sortable should only use the drag handle

- packages/reports/addon/components/report-actions/export.hbs
- packages/reports/addon/templates/components/report-actions.hbs
The report action list started to wrap after the div element and the export tooltip was not in the correct place
- `div` -> `span`
- add targetId for tooltip
> Update: Export style cleanup

- packages/reports/addon/components/filter-values/dimension-select.js
Issue where sortFn was messing with searchAPI sorting of results.
- Obey sorting from dimensionService when cardinality is MEDIUM or above.
- Testing was fruitless because ordering of sortFn is done visually only and does not reflect in DOM. (matrix display magic).
> Fix: Dimensions should obey sorting from service

- packages/data/addon/adapters/facts/bard.ts
- packages/data/addon/mirage/routes/bard-lite.ts
- packages/data/tests/unit/adapters/facts/bard-test.ts
- packages/data/tests/unit/services/navi-facts-bard-test.ts
- packages/reports/addon/consumers/request/fili.ts
- packages/reports/tests/acceptance/column-config-test.ts
- packages/reports/tests/acceptance/fili-datasource-test.ts
- packages/reports/tests/acceptance/report-test.js
- packages/reports/tests/unit/consumers/request/fili-test.ts
Fixes some behavior for fili datasources
- when no dateTime column is present (all grain), any macros are converted to absolute dates using the filter's grain
- When removing the dateTime column (moving to all grain) no longer drop to the lowest time grain
- Updating the dateTime filter grain now also updates the column grain
> Fili Data source fixups

- assets/server-generated-config.js
The server generated config does not define a displayName for the datasource
> Update: Add displayName for server-generated-config

- packages/reports/app/styles/navi-reports/components/navi-column-config/item.scss
Resolves #
-  Column config font
Before (Safari):
After (Safari):
> Update: Column config font

- packages/core/app/styles/navi-core/utils/helpers.scss
- packages/core/app/styles/navi-core/utils/index.scss
- packages/reports/addon/components/report-builder/sidebar.hbs
- packages/reports/app/styles/navi-reports/components/report-builder.scss
- packages/reports/app/styles/navi-reports/components/report-builder/sidebar.scss
Resolves #
- Fix: Column selector overflow issues
**Before:**
**After:**
> Fix: Column selector overflow issues

- packages/data/addon/adapters/facts/elide.ts
- packages/data/addon/adapters/metadata/elide.ts
- packages/data/addon/adapters/metadata/interface.ts
- packages/data/tests/unit/adapters/facts/elide-test.ts
- packages/data/tests/unit/adapters/metadata/elide-test.ts
Add support for custom headers in the Elide adapters.
- Added passthrough of headers in RequestOptions to Apollo
- Added passthrough of headers in MetadataOptions to Apollo
> New: header support in elide adapter

- packages/app/tests/acceptance/custom-reports-test.js
- packages/dashboards/addon/routes/dashboards/dashboard/widgets/new.ts
- packages/dashboards/tests/acceptance/dashboards-test.js
- packages/dashboards/tests/acceptance/explore-widget-test.js
- packages/dashboards/tests/dummy/config/environment.js
- packages/dashboards/tests/unit/routes/dashboards/dashboard/widgets/new-test.js
- packages/reports/addon/routes/reports/new.ts
- packages/reports/config/navi-config.d.ts
- packages/reports/tests/acceptance/column-config-test.ts
- packages/reports/tests/acceptance/dropdown-parameter-picker-test.ts
- packages/reports/tests/acceptance/fili-datasource-test.ts
- packages/reports/tests/acceptance/report-test.js
- packages/reports/tests/dummy/config/environment.js
- packages/reports/tests/unit/routes/reports/new-test.ts
The `defaultDataTable` flag is currently not very useful because it would require loading all tables from all sources and does not guarantee there is a unique table with the given name
- Removes the `defaultDataTable` config option
> Update: Remove defaultDataTable config option

- packages/data/addon/adapters/metadata/bard.ts
Resolves #
- When fetching a non default bard datasource metadata, default datasource metric functions where being fetched. This PR fixes that.
> Fix: Use options fetching metricFn from everything

- packages/data/addon/mirage/routes/bard-lite.js
Adds subtotal/total mock to bard-lite
- Post process the mock rows so that it groups by each requested rollup dimension, adding a subtotal row to each group via reduce. Then flattening the final row set.
- Verified with bard team. 
> New: Add total/subtotal mock support

- packages/core/addon/models/bard-request/fragments/dimension.js
- packages/reports/addon/components/navi-column-config.js
- packages/reports/addon/components/navi-column-config/base.hbs
- packages/reports/addon/templates/components/navi-column-config.hbs
- packages/reports/addon/templates/components/navi-column-config/item.hbs
- packages/reports/addon/templates/reports/report.hbs
- packages/reports/app/styles/navi-reports/components/navi-column-config/base.less
- packages/reports/tests/acceptance/column-config-test.js
- packages/reports/tests/dummy/config/environment.js
- packages/reports/tests/integration/components/navi-column-config/base-test.js
- packages/reports/tests/integration/components/navi-column-config/metric-test.js
- packages/reports/tests/integration/components/navi-column-config/time-dimension-test.js
Adds UI to column config on dimension/datetime columns in order to toggle rollup (aka subtotal).
- Other than obviously setting up and wiring up the buttons, Made dimension fragment copyable, since those fragments can only have one owner it became necessary to clone them in order to add them to the rollup part of the request.
> Rollup dim toggle UI

- packages/core/addon/components/navi-visualizations/table.js
- packages/core/tests/unit/components/navi-visualizations/table-test.js
- packages/data/addon/mirage/routes/bard-lite.js
Missed in spec. since __rollupMask  is a dimension, get serialized as a string
- Handle _rollupMask as a string.
> Fix: Serializing __rollupMask is a dimension

- packages/dashboards/addon/components/dashboard-actions.hbs
- packages/dashboards/addon/components/dashboard-header.hbs
- packages/dashboards/addon/templates/dashboards/dashboard/widgets/widget.hbs
- packages/reports/addon/components/navi-action-list.hbs
- packages/reports/addon/templates/components/report-actions.hbs
- packages/reports/tests/acceptance/report-test.js
Fixes the mysterious disappearance of the export tooltip in the directory view
> Fix: Export tooltip

- packages/core/addon/helpers/current-route.ts
- packages/core/addon/helpers/parent-route.ts
- packages/core/addon/mirage/serializers/base-json-serializer.js
- packages/notifications/app/styles/navi-notifications.scss
- packages/reports/addon/helpers/model-for.ts
- packages/reports/tests/integration/helpers/model-for-test.ts
- model-for checks for empty route name to prevent container lookup assertion error
- notification bar only takes up the width of it's content now (caused some issues click on content near notifications)
- fixup for base-json-serializer
> Fix: ModelForHelper empty route, notifications width

- packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/ReportTest.kt
- packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/RequestV2Test.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/Request.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/request/Rollup.kt
Add rollup to v2 models
- Adds the following shape to requests: 
```
{
rollup: {
columns: [
'columnCID',
'anotherColumnCID'
],
grandTotal: true
}
}
```
> New: Rollup support in webservice models

- packages/core/addon/models/bard-request-v2/fragments/rollup.ts
- packages/core/addon/models/bard-request-v2/request.ts
- packages/core/addon/models/registry.ts
- packages/core/app/models/bard-request-v2/fragments/rollup.js
- packages/core/tests/unit/models/bard-request-v2/request-test.js
- packages/core/tests/unit/models/dashboard-widget-test.js
- packages/core/tests/unit/models/report-test.js
- packages/core/tests/unit/services/compression-test.ts
- packages/dashboards/tests/unit/routes/dashboards/dashboard/widgets/new-test.js
- packages/data/addon/adapters/facts/interface.ts
- packages/reports/addon/consumers/request/column.ts
- packages/reports/addon/consumers/request/rollup.ts
- packages/reports/addon/services/request-action-dispatcher.ts
- packages/reports/app/consumers/request/rollup.js
- packages/reports/tests/unit/consumers/request/rollup-test.ts
- packages/reports/tests/unit/routes/reports/new-test.ts
- packages/reports/tests/unit/serializers/report-test.js
Port of alpha branch but is simplified. Instead of holding dimension model copies in rollup columns, we simply just hold a reference cid.
- add rollup to request model and add consumers to modify request.
> New: Subtotal models and consumers.

- packages/core/addon/components/navi-cell-renderers/dimension.ts
- packages/core/addon/components/navi-cell-renderers/time-dimension.ts
- packages/core/addon/components/navi-table-cell-renderer.hbs
- packages/core/addon/components/navi-table-cell-renderer.ts
- packages/core/addon/components/navi-visualizations/table.ts
- packages/core/addon/helpers/format-date-for-granularity.ts
- packages/core/addon/templates/components/table-renderer-vertical-collection.hbs
- packages/core/addon/templates/components/table-renderer.hbs
- packages/core/app/styles/navi-core/components/navi-visualizations/table.scss
- packages/core/tests/integration/components/navi-cell-renderers/dimension-test.ts
- packages/core/tests/integration/components/navi-cell-renderers/time-dimension-test.ts
- packages/core/tests/integration/components/navi-visualizations/metric-label-test.ts
- packages/core/tests/unit/components/navi-visualizations/table-test.js
- packages/data/addon/adapters/facts/bard.ts
- packages/data/addon/serializers/facts/bard.ts
- packages/data/addon/serializers/facts/interface.ts
- packages/reports/addon/consumers/request/column.ts
- packages/reports/tests/acceptance/column-config-test.ts
Adds sub total and grand total rendering support to table
- More flexible "blank values" rendering in cell selectors, sub total needs nbsp in order to render the subtotal label as a superscript and grand total needs blank in order to display more flat and inline.
- subtotal/grand total styles added
- table component maps subtotal, grandtotal in row meta.
> New: Add subtotal and grandtotal support to table

- packages/webservice/app/build.gradle.kts
- packages/webservice/app/src/main/kotlin/com/yahoo/navi/ws/filters/AuthFilter.kt
- packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/framework/IntegrationTest.kt
- packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/DashboardTest.kt
- packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/DashboardWidgetTest.kt
- packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/DeliveryRulesTest.kt
- packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/ReportTest.kt
- packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/UserTest.kt
- packages/webservice/models/build.gradle.kts
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/Dashboard.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/DashboardWidget.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/DeliveryRule.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/Report.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/User.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/hooks/DashboardDeletionHook.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/hooks/ReportDeletionHook.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/hooks/UserValidationHook.kt
Currently admins do not have the ability to create/update/delete any users/reports/dashboards/widgets/deliveryRules/etc 
allow admins to create/update/delete entities
> Update: Allow admin to create/modify/delete entities

- packages/core/addon/components/navi-visualizations/table.ts
- packages/core/addon/models/bard-request-v2/fragments/rollup.ts
- packages/core/addon/models/bard-request-v2/request.ts
- packages/core/tests/unit/components/navi-visualizations/table-test.js
- packages/core/tests/unit/models/bard-request-v2/request-test.js
- packages/core/tests/unit/models/dashboard-widget-test.js
- packages/core/tests/unit/models/report-test.js
- packages/dashboards/tests/unit/routes/dashboards/dashboard/widgets/new-test.js
- packages/data/addon/adapters/facts/bard.ts
- packages/data/addon/adapters/facts/interface.ts
- packages/data/tests/unit/adapters/facts/bard-test.ts
- packages/reports/addon/components/navi-column-config.ts
- packages/reports/tests/unit/consumers/request/rollup-test.ts
- packages/reports/tests/unit/routes/reports/new-test.ts
- packages/reports/tests/unit/serializers/report-test.js
- packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/ReportTest.kt
- packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/RequestV2Test.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/request/Rollup.kt
Changes rollup contract from rollup.columns to rollup.columnCids
- rename the prop everywhere
>  Rollup.columns -> Rollup.columnCids

- packages/core/addon/utils/persistence-error.js
- packages/core/tests/unit/utils/persistence-error-test.js
- packages/reports/tests/acceptance/schedule-modal-test.js
Persistence error messages coming in as `{ errors: [{detail: 'msg'}] }` so we need to support this format
- Make sure we can pull error messages from this format.
> Fix: Support new elide error message format.

- packages/core/addon/components/navi-table-sort-icon.hbs
- packages/core/addon/components/navi-visualizations/table.ts
- packages/core/addon/templates/components/table-renderer-vertical-collection.hbs
- packages/core/addon/templates/components/table-renderer.hbs
- packages/core/app/styles/navi-core/components/navi-table-sort-icon.scss
- packages/core/app/styles/navi-core/components/navi-visualizations/table.scss
Table column reordering fires a `click` event, similar to https://github.com/adopted-ember-addons/ember-sortable/issues/405
- attach click listener to `ol`
- other cosmetics: always render Denali sort arrows to avoid possible column width change on hover
> Fix: Table column reordering + always render sort icons

- packages/dashboards/addon/templates/dashboards/dashboard/widgets/widget.hbs
- packages/dashboards/tests/acceptance/dashboards-test.js
- packages/dashboards/tests/acceptance/explore-widget-test.js
- packages/reports/addon/templates/components/report-actions.hbs
- packages/reports/tests/acceptance/report-test.js
Check validity of the request and not the report (which also checks `title`, `visualization`)
> Fix: Enable API Query button even if valid request hasn't been run

- packages/core/addon/mirage/fixtures/reports.ts
- packages/core/addon/serializers/dashboard-widget.ts
- packages/core/addon/serializers/report.ts
- packages/core/addon/serializers/table.ts
- packages/core/addon/utils/request.ts
- packages/core/tests/unit/models/report-test.js
- packages/core/tests/unit/serializers/bard-request-v2/request-test.js
- packages/core/tests/unit/serializers/table-test.ts
- packages/core/tests/unit/utils/request-test.ts
- packages/dashboards/tests/acceptance/dashboards-test.js
- packages/data/addon/mirage/routes/bard-lite.ts
- packages/reports/tests/acceptance/multi-datasource-test.js
- packages/reports/tests/acceptance/report-test.js
- packages/reports/tests/acceptance/report-visualizations-test.js
- packages/reports/tests/dummy/app/routes/application.ts
Reverts the request v2 normalizer to convert requested `dimension`s to `{ type: 'dimension', field: dimension, parameters: { field: 'id' }}` because only the table visualization requires different fields
The table serializer will modify the request dimensions by
- checking if metadata is available and
- injecting all `show` fields if present or
- injecting `desc` or `id` if present or
- fall back to first field available
- if not available, defaults to `desc` field
For chart series visualizations, the request must only ask for the `id` field to remain valid. If we request `id` and `desc` the visualization becomes out of date and must be rebuilt.
For chart series, this is how it will appear if new series are added since the description is not available.
But after adding the desc field and …
> Fix: Request v2 normalizer adds dimensions with id field, table normalizer updates to use show fields/desc

- packages/data/addon/adapters/facts/bard.ts
- packages/data/config/navi-config.d.ts
- packages/data/tests/dummy/config/environment.js
- packages/data/tests/unit/adapters/facts/bard-test.ts
Default end date for dateTime `since` operator for fili was  9999, this actually causes an issue with fili to search way far out into the future for date buckets that don't exist.
- Allow a configurable value per datasource to control how far out `since` will search for.
> Update: Configurable Fili end for since operator

- packages/data/addon/adapters/dimensions/bard.ts
- packages/data/addon/utils/pagination.ts
- packages/data/addon/utils/search.ts
- packages/data/tests/unit/adapters/dimensions/bard-test.ts
- packages/reports/addon/components/filter-values/dimension-select.hbs
- packages/reports/addon/components/filter-values/dimension-select.ts
- packages/reports/tests/integration/components/filter-values/dimension-select-test.ts
Lucene based dimension searching endpoint has better result sorting than client side provides. So in the case of that dimension sort we do not want to resort the result
- Do not client side sort if cardinality is larger than "Small" and we're using the enhanced dimension search.
- TODO: add caching to `all` in the adapter will be in a followup PR.
> Fix: Don't client side sort dim search endpoint

- packages/data/addon/adapters/dimensions/bard.ts
Pass dimension searches through search util. (Temporary)
- Due to tweaks needed server side search ordering, we will run search results through our client side ranking for the time being.
> Fix: DimensionSearch ordering.

- packages/data/addon/adapters/facts/bard.ts
- packages/data/addon/mirage/routes/bard-lite.ts
- packages/data/tests/unit/adapters/facts/bard-test.ts
- packages/data/tests/unit/services/navi-facts-bard-test.ts
Support Fili's new `currentDay`, `nextWeek` etc. date macros.
- Allow "custom macros" for the `all` time grain. If `current`/`next` is passed in, add filter grain suffix.
- Add support in mirage route handler
> Support Fili new date macros

- packages/reports/addon/components/column-selector.hbs
- packages/reports/addon/components/grouped-list.ts
- packages/reports/tests/integration/components/grouped-list-test.js
Discovered when searching for metric/dimension, the groups get ordered alphabetically, which puts better search results farther down the list.
- Keep alpha group sorting, but we'll disable that when there is a search happening
- To do that we just add a `@shouldSort` argument to `GroupedList` component
- `Uncategorized` will still get sorted to bottom.
> Fix: Group order when search gets alpha sorted

- package-lock.json
- packages/core/addon/components/navi-visualizations/goal-gauge.ts
- packages/core/addon/components/navi-visualizations/line-chart.ts
- packages/core/addon/components/number-format-selector.hbs
- packages/core/addon/helpers/smart-format-number.ts
- packages/core/package-lock.json
- packages/core/package.json
- packages/data/addon/services/navi-formatter.ts
- packages/data/package-lock.json
- packages/data/package.json
Resolves #1065 
Replace numeral with numbro
- Other than obvious library swap there was some inconsistencies with numeral
- 'a' formatter works different and is a bit more aggressive about rounding up on numbers less than 1000. so `500` got formatted to `.5k` to fix this I set average flag only when number > 1000.
- There seems a bug with things getting floatty even with safe ints with large Mantissa. https://github.com/BenjaminVanRyseghem/numbro/issues/587 so the default metric formatter from 10 mantissa to 9. We might see more issues. Might investigate this in numbro so we can go back to 10.
- used the new formatting object rather than strings for all programmatic formats. (leaving old style for users).
I confirm that this contribution is made under the terms of the license found in the …
> Update: Replace numeral.js with numbro

- packages/core/addon/components/navi-visualizations/chart-builders-base.ts
- packages/core/tests/acceptance/line-chart-test.ts
- packages/core/tests/dummy/app/services/navi-formatter.js
- packages/core/tests/dummy/app/templates/line-chart.hbs
The buildTooltip function keeps a reference to the chart builder to access row information, but we lookup the same instance instead of creating new ones so it gets overwritten if used more than once
> Fix: Tooltip pass the row correctly

- packages/core/addon/mirage/fixtures/users.ts
- packages/directory/tests/acceptance/dir-table-test.js
- packages/reports/addon/components/navi-action-list.ts
- packages/reports/addon/templates/components/report-actions.hbs
- packages/reports/tests/acceptance/report-test.js
- packages/reports/tests/acceptance/schedule-modal-test.js
- packages/reports/tests/unit/routes/reports/index-test.js
- validate the request, not the whole report
- add an invalid report to the mocks for testing
> Fix: Validate request only when trying to schedule a report

- packages/reports/addon/components/report-builder/sidebar.hbs
- packages/reports/addon/components/report-builder/source-selector.hbs
- packages/reports/app/styles/navi-reports/components/report-builder/sidebar.scss
- packages/reports/app/styles/navi-reports/components/report-builder/source-selector.scss
Fix the sidebar layout to display long strings better
Before:
After:
Datasource/Table selector stays small:
> Fix: Report builder sidebar cuts off long strings

- packages/data/addon/adapters/facts/bard.ts
- packages/data/tests/unit/adapters/facts/bard-test.ts
Respects the dimension field order from the request so that CSV output matches better with the table visualization
- Do not sort dimension fields in show clause
> Fix: Respect fili dimension field order from request

- packages/core/addon/components/navi-visualizations/table.ts
Export these types to allow `computeColumnTotal` to be overriden
> Update: Export TotalType, TotalRow types

- packages/reports/addon/components/navi-column-config/base.hbs
- packages/reports/addon/consumers/request/sort.ts
- packages/reports/app/styles/navi-reports/components/navi-column-config.scss
- packages/reports/tests/acceptance/column-config-test.ts
- packages/reports/tests/acceptance/fili-datasource-test.ts
- packages/reports/tests/unit/consumers/request/sort-test.ts
If a column is not `isSortable`, don't sort it.
> Fix: Columns that are not isSortable can still be sorted from column config

- packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/DashboardTest.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/User.kt
Resolves #
- Fix: Allow admins to update dashboard editors
> Fix: Allow admins to update dashboard editors

- packages/dashboards/addon/components/dashboard-actions.hbs
- packages/directory/addon/components/dir-item-favorite-cell.hbs
- packages/directory/addon/components/dir-table.ts
- packages/reports/addon/components/navi-action-list.hbs
Align report and dashboard actions, make favorite section smaller
> Fix: Align asset actions

- packages/core/addon/components/navi-visualization-config/table.ts
- packages/reports/tests/acceptance/report-visualizations-test.js
changes in how visualization changes are merged, deep merges no longer work
- total/subtotal was requiring a deep merge, fixed so that config includes all properties so deep merge no longer is required.
> Fix: Subtotal changes no longer needs deep merge

- packages/core/addon/components/navi-visualization-config/goal-gauge.ts
- packages/core/addon/models/goal-gauge.ts
- packages/core/tests/integration/components/navi-visualization-config/goal-gauge-test.ts
Resolves #1550 
The visualization did not convert the baseLine and goal values to numbers before updating the config 
> Fix: Convert string to number for viz config

- packages/core/addon/components/navi-visualizations/table.ts
- packages/core/tests/unit/components/navi-visualizations/table-test.js
Found bug where rollupMask is calculated incorrectly when there are duplicate dimensions (say they request both id and desc in same report).
- dedupe correctly forehead.
> Fix: Rollup mask is not calculated correctly

- packages/data/addon/models/metadata/dimension.ts
- packages/data/addon/models/metadata/elide/dimension.ts
- packages/data/addon/serializers/metadata/bard.ts
- packages/data/addon/serializers/metadata/elide.ts
- packages/data/tests/unit/models/metadata/dimension-test.ts
- packages/data/tests/unit/serializers/metadata/bard-test.ts
- packages/data/tests/unit/serializers/metadata/elide-test.ts
- packages/reports/addon/components/filter-builders/dimension.ts
Fix: Don't load search valueSourceType NONE dims
- Conform dimension metadata to use `valueSourceType` and remove `storageStrategy`
-  Don't search dimension values when `valueSourceType` is `NONE`
> Fix: Don't load search valueSourceType NONE dims

- package-lock.json
- packages/reports/addon/components/filter-values/time-dimension/range.ts
- packages/reports/tests/integration/components/filter-values/time-dimension/range-test.ts
When updating the start past the end or the end before the start, update both so the interval stays valid
> Fix: Update start or end when they become invalid

- packages/core/addon/mirage/fixtures/dashboard.ts
- packages/core/addon/serializers/dashboard.js
- packages/core/tests/unit/models/dashboard-test.js
- packages/core/tests/unit/serializers/dashboard-test.js
- packages/dashboards/addon/components/dashboard-dimension-selector.js
- packages/dashboards/addon/controllers/dashboards/dashboard/view.ts
- packages/dashboards/addon/services/dashboard-data.ts
- packages/dashboards/addon/templates/components/dashboard-dimension-selector.hbs
- packages/dashboards/addon/templates/components/navi-widget.hbs
- packages/dashboards/tests/acceptance/dashboard-filter-test.js
- packages/dashboards/tests/acceptance/dashboards-test.js
- packages/dashboards/tests/acceptance/mutli-datasource-dashboards-test.js
- packages/dashboards/tests/integration/components/dashboard-dimension-selector-test.js
- packages/data/addon/adapters/facts/bard.ts
- packages/data/addon/gql/schema.graphql
- packages/data/tests/unit/adapters/facts/bard-test.ts
- packages/reports/addon/components/filter-builders/time-dimension.ts
- packages/reports/addon/components/filter-values/dimension-select.hbs
- packages/reports/addon/components/filter-values/multi-value-input.hbs
- packages/reports/addon/components/filter-values/range-input.hbs
- packages/reports/addon/components/filter-values/time-dimension/advanced.hbs
- packages/reports/addon/components/filter-values/time-dimension/current.hbs
- packages/reports/addon/components/filter-values/time-dimension/date.hbs
- packages/reports/addon/components/filter-values/time-dimension/lookback.hbs
- packages/reports/addon/components/filter-values/time-dimension/range.hbs
- packages/reports/addon/components/filter-values/value-input.hbs
- packages/reports/addon/consumers/request/filter.ts
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/fragments/request/DashboardFilter.kt
Add global date filters to dashboards
- Include `timeDimension`s  in the dimension selector (**desirable TODO: Consolidate date dimensions of multiple datasources/tables into one option** while applying correctly to each request)
- Set default operator and filter values according to filter type
- Add filter type to dash filter model, serialize `grain` as `field` for `timeDimension`s
- Parse correctly elide datasources with namespace (`elide.namespace`)
- **Remove fact adapter error when grains don't match and let ws return errors**
- Display request errors in widgets
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright …
> Update: Add global date filters to dashboards

- packages/reports/addon/consumers/request/sort.ts
- packages/reports/tests/unit/consumers/request/sort-test.ts
The original intent was sorts matching the base metric would be removed after a parameter is changed. However that behavior was lost as removal functions became more strict matching parameters. Causing invalid requests.
- Change back to original intent where changing a parameter will remove all base metrics from sort.
- Future update will make this a bit better as we can map the sort to the intended column and update the sort instead of removing it.
> Fix: Sorts removed when params are changed.

- packages/perspective/addon/components/perspective.ts
- packages/perspective/tests/dummy/app/templates/application.hbs
- packages/perspective/tests/integration/components/perspective-test.ts
Manually specify day/week/etc grained time dimensions as 'date' to render without time
> Fix: Perspective specify date schema for day aligned time dims

- packages/core/addon/services/visualization.ts
- packages/core/tests/unit/services/visualization-test.ts
- packages/reports/addon/components/visualization-toggle.hbs
- packages/reports/addon/components/visualization-toggle.ts
Adds a category order to the visualization service
> Fix: Add category order to vis service

- packages/reports/addon/components/common-actions/delete.hbs
- packages/reports/addon/components/common-actions/delete.ts
- packages/reports/tests/integration/components/common-actions/delete-test.js
Change `toggle` helper to `mut`.
`toggle` uses `set`. If `deleteAction` causes the component to be destroyed, an `Assertion Failed: calling set on destroyed object: [object Object].isDeleting = false` error is thrown. (we update `isDeleting` to false once `deleteAction` resolves).
the added test would've thrown when using `toggle`.
> Fix: Delete action that destroys the component blows up

- packages/reports/addon/components/filter-builders/time-dimension.ts
- packages/reports/addon/components/filter-values/time-dimension/advanced.ts
- packages/reports/tests/unit/components/filter-builders/time-dimension-test.ts
Since is a 'gte' operation and advanced filter shouldn't swap to 'since' when end date is pinned to 'current' as having a fixed end date is incompatible with the concept of 'gte' date time filter.
Also advanced filter is frustrating to use as it swaps out filter builders after blurring only one input.
- datetime to current should not be 'Since'
- advanced filter shouldn't update until both advanced inputs blur.
> Fix: Advanced datetime filter builder bugs.

- packages/reports/addon/components/visualization-toggle.hbs
- packages/reports/addon/components/visualization-toggle.ts
- packages/reports/tests/integration/components/visualization-toggle-test.ts
Fixes an issue with the visualization toggle where it would show all categories and try to select a visualization even if it was invalid
> Fix: Hide categories with no valid visualizations

- packages/core/addon/models/delivery-rule.ts
- packages/core/tests/unit/models/delivery-rule-test.js
- packages/webservice/app/src/test/kotlin/com/yahoo/navi/ws/test/integration/DeliveryRulesTest.kt
- packages/webservice/models/src/main/kotlin/com/yahoo/navi/ws/models/beans/DeliveryRule.kt
JobRunner can not update failureCount or isDisabled
- Adding correct Elide permissions on those fields
> Fix: Permissions on DeliveryRules

- packages/reports/addon/components/filter-builders/time-dimension.ts
- packages/reports/addon/consumers/request/fili.ts
- packages/reports/addon/consumers/request/table.ts
- packages/reports/addon/services/request-action-dispatcher.ts
- packages/reports/tests/acceptance/fili-datasource-test.ts
- packages/reports/tests/unit/consumers/request/fili-test.ts
- packages/reports/tests/unit/consumers/request/table-test.ts
Fix for keeping the same dateTime grain/filter for fili reports when switching tables
> Fix: Keep fili dateTimes while switching tables

- packages/reports/addon/components/missing-intervals-warning.hbs
- packages/reports/addon/components/missing-intervals-warning.ts
- packages/reports/app/styles/navi-reports/components/missing-intervals-warning.scss
- packages/reports/app/styles/navi-reports/components/report-builder.scss
- packages/reports/app/styles/navi-reports/components/report-view.scss
Better fix for the missing intervals warning that leaves enough vertical space for the filters.
Make expanded warning go over the visualization.
https://user-images.githubusercontent.com/13946669/168120292-ee791e01-8fe4-421b-aca0-9b87784af596.mov
> Fix missing intervals

- packages/data/addon/gql/fragments/table.graphql
- packages/data/addon/gql/queries/table.graphql
- packages/data/addon/gql/queries/tables.graphql
Resolves #
Fixes the deprecation warning: 
```
[DEPRECATION] Legacy import syntax found in ... See https://git.io/fjym5 for migration details
```
-
> Graphql import

- packages/reports/addon/components/filter-values/multi-value-input.hbs
- packages/reports/addon/components/filter-values/multi-value-input.ts
- packages/reports/app/styles/navi-reports/components/filter-values/multi-value-input.scss
- packages/reports/tests/acceptance/report-test.js
This PR fixes the following issue:
1. add a dimension filter that does not have type ahead
1. type a value into the filter values box
1. press run
1. add another value into the filter values box
1. observe that you're not prompted to press 'run'
1. press 'run'
1. observe that nothing happens
> Fix: Filter model updates correctly on filter-value input

- packages/data/addon/adapters/facts/bard.ts
- packages/data/addon/serializers/facts/elide.ts
- packages/data/tests/unit/adapters/dimensions/elide-test.ts
- packages/data/tests/unit/serializers/facts/elide-test.ts
Removes possibly invalid type imports which are breaking consuming apps. I'm not sure if these are valid and the consuming apps are broken or if these are invalid and should not have published
> Fix: Revert invalid type imports

- packages/client/src/adapters/metadata/interface.ts
- packages/data/addon/adapters/dimensions/bard.ts
- packages/data/addon/adapters/dimensions/elide.ts
- packages/data/addon/adapters/dimensions/interface.ts
- packages/data/addon/adapters/facts/bard.ts
- packages/data/addon/adapters/facts/elide.ts
- packages/data/addon/adapters/facts/interface.ts
- packages/data/addon/serializers/dimensions/elide.ts
- packages/data/addon/serializers/dimensions/interface.ts
- packages/data/addon/services/navi-dimension.ts
- packages/data/addon/services/navi-facts.ts
- packages/data/tests/unit/adapters/dimensions/bard-test.ts
- packages/data/tests/unit/adapters/dimensions/elide-test.ts
- packages/data/tests/unit/adapters/facts/bard-test.ts
- packages/data/tests/unit/adapters/facts/elide-test.ts
- packages/data/tests/unit/services/navi-dimension-test.ts
Use `PromiseLike` values for adapter interfaces so that the implementation can be more generic
> Update: Make facts/dims/meta adapter interfaces generic

- packages/dashboards/addon/components/navi-widget.hbs
- packages/dashboards/addon/components/navi-widget.ts
- packages/dashboards/tests/integration/components/navi-widget-test.js
- packages/reports/addon/components/report-view.hbs
- packages/reports/addon/components/report-view.ts
The report view doesn't render visualizations when there is no data available; this PR fixes the dashboard view match the report view.
Report view:
Dashboard view:
> Fix: Make dashboard view match report view when no data present

- packages/c3/ember-cli-build.js
- packages/client/src/config/datasource-plugins.ts
- packages/client/src/config/service-plugins.ts
- packages/client/src/index.ts
- packages/client/src/models/native-with-create.ts
- packages/client/src/utils/types.ts
- packages/client/test/tests/unit/config/datasources-plugin-test.ts
- packages/client/test/tests/unit/index-test.ts
- packages/core/ember-cli-build.js
- packages/dashboards/ember-cli-build.js
- packages/data/addon/services/navi-dimension.ts
- packages/data/addon/services/navi-facts.ts
- packages/data/addon/services/navi-metadata.ts
- packages/data/addon/services/yavin-client.ts
- packages/data/ember-cli-build.js
- packages/data/tests/unit/services/navi-dimension-test.ts
- packages/data/tests/unit/services/yavin-client-test.ts
- packages/directory/ember-cli-build.js
- packages/notifications/ember-cli-build.js
- packages/perspective/ember-cli-build.js
- packages/reports/ember-cli-build.js
Set up `dataSourcePlugins` to allow adding custom data sources to the client and `servicePlugins` to allow for overriding the default services.
Also creates the plugins for bard/elide from the navi-data config and service overrides so now we can directly use `this.yavinClient.{facts,metadata,dimensions}`
> Update: Set up datasource/service plugins for client

- packages/client/src/adapters/facts/interface.ts
- packages/client/src/config/datasource-plugins.ts
- packages/client/src/index.ts
- packages/client/src/models/native-with-create.ts
- packages/client/src/plugins/elide/adapters/metadata.ts
- packages/client/src/plugins/fili/adapters/facts.ts
- packages/client/src/services/fact.ts
- packages/client/src/utils/task.ts
- packages/client/test/tests/helpers/config.ts
- packages/client/test/tests/helpers/injector.ts
- packages/client/test/tests/unit/config/datasources-test.ts
- packages/client/test/tests/unit/models/metadata/dimension-test.ts
- packages/client/test/tests/unit/models/metadata/elide/dimension-test.ts
- packages/client/test/tests/unit/models/metadata/metric-test.ts
- packages/client/test/tests/unit/plugins/fili/adapters/facts-test.ts
- packages/client/test/tests/unit/services/fact-test.ts
- packages/data/addon/adapters/facts/bard.ts
- packages/data/addon/serializers/facts/bard.ts
- packages/data/addon/services/navi-facts.ts
- packages/data/addon/services/yavin-client.ts
- packages/data/tests/unit/services/navi-facts-test.ts
Moves the fact service to the client package. We currently do not do any cancellation for fact queries from the UI, so we should refactor that later, but I've verified by adding a delay and calling `cancel()` on the task wrapper instance that it cascades down properly
> Update: Move fact service to client and make ember wrapper

- packages/client/src/services/metadata.ts
- packages/data/addon/services/navi-facts.ts
- packages/data/addon/services/navi-metadata.ts
Moves the metadata service to client and adds an ember concurrency wrapper for test waiting/task cancelling (although the metadata service is promise based so it does not yet support it)
> Update: Move metadata service to client

- packages/dashboards/addon/components/navi-widget.hbs
- packages/dashboards/app/styles/navi-dashboards/common.scss
- packages/dashboards/tests/integration/components/navi-widget-test.js
Our tools look for `error-container` in order to detect failed widgets. Empty widgets should not trigger this. So changing this to `empty-container`
- `error-container` -> `empty-container` on widgets with no data.
> Fix: Empty widgets signal an error to tools.

- packages/client/src/plugins/elide/adapters/facts.ts
- packages/client/src/services/fact.ts
- packages/data/tests/unit/adapters/facts/elide-test.ts
- packages/reports/tests/integration/components/common-actions/get-api-test.js
Resolves #
This PR removes the `query` prop wrapper around the elide query in the Get API modal
-
> Fix: Remove elide "query" prop get api query modal

- packages/dashboards/tests/acceptance/explore-widget-test.js
- packages/reports/addon/routes/reports/report/view.ts
Dimension series always try to rebuild so in some situations after pressing save, even though the viz metadata is the same, the user is prompted to save their report/widget again
> Fix: Only update visualization metadata if there are changes

- packages/reports/addon/components/common-actions/schedule.hbs
- packages/reports/app/styles/navi-reports/components/common-actions/schedule-modal.scss
Add a scroll shadow to the schedule modal options to show if more options are hidden below
> Fix: Add scroll shadow to schedule modal

- package-lock.json
- packages/perspective/addon/components/perspective.ts
- packages/perspective/addon/manifest.ts
- packages/perspective/package-lock.json
- packages/perspective/package.json
- packages/perspective/tests/integration/components/perspective-test.ts
- packages/perspective/types/global.d.ts
Adds a polyfill for Intl.supportedValuesOf and Intl.DateTimeFormat and forcefully adds the 'UTC' timeZone to supportedValuesOf if it is supported.
Also reverts the schema change for using `date` on day aligned grains and instead sets the timeStyle to disabled to allow for using UTC timeZone
> Fix: Perspective should default timeDimensions to UTC

- packages/app/config/targets.js
- packages/dashboards/addon/routes/dashboards/dashboard/widgets/new.ts
- packages/dashboards/tests/dummy/config/targets.js
- packages/data/app/utils/metric.js
- packages/data/tests/dummy/config/targets.js
- packages/directory/tests/dummy/config/targets.js
- packages/notifications/tests/dummy/config/targets.js
- packages/perspective/addon/components/perspective.ts
- packages/reports/addon/routes/reports-print/reports/new.ts
- packages/reports/tests/dummy/config/targets.js
Because we add support for `ie 11` in prod builds, babel jumbles with the syntax for `class extends HTMLElement` which is required for defining custom html elements (not just messing with prototypes). So a change in perspective caused us to start pulling in this js file and transpiling it leading to throwing a `TypeError: Illegal Constructor` 
> Fix: Perspective in prod builds and bad imports

- packages/reports/addon/components/visualization-toggle.hbs
- packages/reports/addon/components/visualization-toggle.ts
- packages/reports/tests/integration/components/visualization-toggle-test.ts
crashes if selected category is no longer has any valid visualizations
- Pass empty list to `DenaliToggle` instead of `undefined` in this case.
> Fix: visualization-toggle crash

- packages/core/addon/serializers/visualization.ts
- packages/core/tests/unit/models/report-test.js
- packages/core/tests/unit/serializers/table-test.ts
- packages/core/tests/unit/services/visualization-test.ts
- packages/dashboards/tests/unit/routes/dashboards/dashboard/widgets/new-test.js
- packages/reports/tests/unit/routes/reports/new-test.ts
- packages/reports/tests/unit/routes/reports/report-test.js
- packages/reports/tests/unit/routes/reports/report/view-test.js
- packages/reports/tests/unit/serializers/report-test.js
Serialize v1 visualizations with namespace=null to overwrite any saved namespace saved in the database
> Fix: Set namespace to null when serializing v1 visualizations

- packages/client/src/errors/navi-adapter-error.ts
Abort (like a timeout) causes a DOMException Abort, that is unbound, stringify the exception causes 'Illegal Invocation'
- Temporary workaround
- Do not stringify rootCause for now.
- Fix might be through `ensure` to figure out why it's throwing an unbound DOMException 
> Fix: Abort locks up UI with unbound exception.
